### ISSUE TITLE
Twisted should not depend on mock

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10024]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#10024|
|Type|defect|
|Created|2020-10-17 05:22:59Z|

`setup.cfg` indicates a dev dependency on `mock`:

```
[options.extras_require]
dev =
...
    mock~=4.0
...
```

Twisted shouldn't need this dependency as the functionality is now available as `unittest.mock`. Twisted probably also shouldn't use this library as it usually results in bad tests.

<details><summary>Searchable metadata</summary>

```
trac-id__10024 10024
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1602912179782455 1602912179782455
changetime__1602912179782455 1602912179782455
version__None None
owner__None None

```
</details>

**Comment by twm** [comment]
The dependency is gone now. There is one use of `unittest.mock`, but it's for `sentinel` which isn't the problematic part of the library.
