### ISSUE TITLE
asyncioreactor interop with uvloop?

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10039]
|[<img alt="ShadowJonathan's avatar" src="https://avatars.githubusercontent.com/u/22740616?s=50" width="50" height="50">](https://github.com/ShadowJonathan)| @ShadowJonathan reported|
|-|-|
|Trac ID|trac#10039|
|Type|enhancement|
|Created|2020-10-26 12:19:03Z|

In [ticket:9279#comment:1], interop with `uvloop` was suggested, and indeed, [it somewhat proliferated](https://gist.github.com/ldjebran/4febf298232a6fd86871df25d4dc00dd) as a suggestion and a solution to gain uvloop's "blazing fast" IO performance, with the power of twisted's framework, and the interoperability of `asyncio`.

However, recently, a commit (0e72cc702e4748ec9ff754a004f8d5223b636aef) introduced a strict requirement to use `SelectorEventLoop`, which `uvloop.Loop` does not subclass, it subclasses `AbstractEventLoop`, which does not fly for this check:

```
        if not isinstance(_eventloop, SelectorEventLoop):
            raise TypeError(
                "SelectorEventLoop required, instead got: {}".format(_eventloop)
            )
```

Isn't it possible to flip this check around, and instead only check if it subclasses `ProactorEventLoop` (`if isinstance(_eventloop, ProactorEventLoop)`, and allow any other `AbstractEventLoop` implementation? (such as `uvloop`)

<details><summary>Searchable metadata</summary>

```
trac-id__10039 10039
type__enhancement enhancement
reporter__ShadowJonathan ShadowJonathan
priority__low low
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1603714743785279 1603714743785279
changetime__1603714743785279 1603714743785279
version__None None
owner__None None

```
</details>

**Comment by glyph** [comment]
This is a great idea!  And it's also a duplicate of #9967 :).
