### ISSUE TITLE
twisted/cred/credentials.py uses "==" to compare passwords/hashes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10086]
|[<img alt="giadram's avatar" src="https://avatars.githubusercontent.com/u/78812089?s=50" width="50" height="50">](https://github.com/giadram)| @giadram reported|
|-|-|
|Trac ID|trac#10086|
|Type|defect|
|Created|2021-02-09 17:06:35Z|

It's recommended to use a function with constant compare time for passwords or hashes. Like 'compare_digest' from hmac module.

Attachments:

* [f54ed5ad5d8f3933a2d3bf6c27eec2e668edf6f2.patch.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/720/7205db181158aa3dfc55d22fe521f447ca2e5777/2a046fe2b0de704a2fa16c0cf3c9baffe4dbe8d4.txt) (2584 bytes) - added by giadram on 2021-02-09 17:06:56Z - patch

<details><summary>Searchable metadata</summary>

```
trac-id__10086 10086
type__defect defect
reporter__giadram giadram
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__review review
time__1612890395255613 1612890395255613
changetime__1612895833279940 1612895833279940
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="alex's avatar" src="https://avatars.githubusercontent.com/u/772?s=50" width="50" height="50">](https://github.com/alex)<a name="note_1"></a>|@alex commented|
|-|-|

https://github.com/twisted/twisted/pull/1511

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

This seems like a duplicate of [#4536](https://github.com/twisted/twisted/issues/4536)

**Comment by exarkun** [comment]
Closing as a duplicate.
