### ISSUE TITLE
Migrate documentation to Read The Docs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10117]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10117|
|Type|enhancement|
|Created|2021-03-07 17:37:23Z|

This is a meta ticket to track the progress for Read The Docs migration.

Reason to migrate to Read The Docs:

* No need to host and manage our HTTPS server...and manage the certificates

* A new version of the documentation is automatically generated when a new tag is pushed... no need for SSH key credentials, manually generate the files, create a TAR, scp the TAR, extract the TAR, update permissions, create symlink

* We don't have much work on the automation process itself as it is provided by GitHub Actions / Read The Docs...and is the same process shared by many other projects
 
To do

* DONE - create docs.twistedmatrix.com DNS CNAME
* DONE - also host pydoctor API docs on RTD
* TODO - Add a warning on non-latest RTD narrative pages that a never version exists
* TODO - Add a warning on non-latest RTD API docs pages that a never version exists
* DONE - Create https://docs.twistedmatrix.com/en/stable/ build
* TODO - Redirect https://twistedmatrix.com/documents/current/ to https://docs.twistedmatrix.com/en/stable/
* TODO - Find a way to freeze-host all existing  https://twistedmatrix.com/documents/ files under the same domain and URL ... or create a redirection. Older version of Twisted narrative docs contain hardcoded URL to API docs... We have MS Azure credit so in theory we can host the files on an Azure cloud service.

<details><summary>Searchable metadata</summary>

```
trac-id__10117 10117
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__documentation documentation
time__1615138643730048 1615138643730048
changetime__1633088202872947 1633088202872947
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
This was done here https://github.com/twisted/twisted.github.io/issues/13
