### ISSUE TITLE
support python-subunit in py3.10

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10115]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)| @graingert reported|
|-|-|
|Trac ID|trac#10115|
|Type|task|
|Created|2021-03-03 13:47:56Z|

currently python-subunit does not support py3.10: https://github.com/testing-cabal/subunit/pull/32

we should re-enable the support in Twisted when they land and release this

<details><summary>Searchable metadata</summary>

```
trac-id__10115 10115
type__task task
reporter__graingert graingert
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1614779276762844 1614779276762844
changetime__1614779276762844 1614779276762844
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
The upstream issue appears to be resolved and there have been several releases since the change was merged so I suppose it is released.  What's less clear is whether this actually provides Python 3.10 support since the changeset adds no upstream Python 3.10 testing.

**Comment by graingert** [comment]
@exarkun looks like *our* CI passes with python-subunit installed so I guess we can revert this pin
