### ISSUE TITLE
disttrial for windows communicate with AMP via stdin/stdout

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10158]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10158|
|Type|enhancement|
|Created|2021-03-28 11:52:48Z|

The current distributed trials generates extra pipes (childFDs) on top of stdin/stdout/stderr for AMP communication.

They are not supported by spawn process on Windows.

To have distrial on windows we can rewrite distrial to use stdout/stding for AMP communication.

The side effect is that we need to setup separate capturing for stdout/stdin.

Most tests should not need stdin so the missing stdin in sub-process should be a non-issue.

Also, the tests should not write to stdout ... but we still want to capture and  add a warning or a failure if required.

<details><summary>Searchable metadata</summary>

```
trac-id__10158 10158
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1616932368724323 1616932368724323
changetime__1626936294371694 1626936294371694
version__None None
owner__adiroiban adiroiban

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

PR at https://github.com/twisted/twisted/pull/1573

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set owner to @adiroiban|
|-|-|

Thanks for splitting this work up into multiple reviewable pieces. Sorry that I have to reject it :) But I hope that this will still be useful as an optional / non-default thing that can allow this to work on Windows in a more limited way, until we can figure out how to make childFDs work on Windows in some capacity.

**Comment by exarkun** [comment]
Unfortunately, there is  no way to make communication over stdout reliable.  I plan to add Windows support to disttrial sometime soon.  At the moment my plan is to open some extra SOCK_STREAMs - probably connections over localhost, but those details remain to be determined.

**Comment by adiroiban** [comment]
Thanks for the update.

Yes maybe using TCP connections of the loopback interface is the best option we have on Windows.

So I guess this can be closed, as we don't want to have distrial using stdout/stdin
