### ISSUE TITLE
Add type hints for twisted.internet.task

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10155]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)| @wsanchez reported|
|-|-|
|Trac ID|trac#10155|
|Type|enhancement|
|Created|2021-03-27 19:35:26Z|
|Branch|https://github.com/twisted/twisted/tree/1570|

Add type hints for `twisted.internet.task`

<details><summary>Searchable metadata</summary>

```
trac-id__10155 10155
type__enhancement enhancement
reporter__wsanchez wsanchez
priority__normal normal
milestone__None None
branch__1570 1570
branch_author__ 
status__reopened reopened
resolution__None None
component__core core
keywords__None None
time__1616873726559072 1616873726559072
changetime__1627055790806379 1627055790806379
version__None None
owner__wsanchez wsanchez

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_1"></a>|@wsanchez commented|
|-|-|

PR: https://github.com/twisted/twisted/pull/1570

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set owner to @wsanchez|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)|@wsanchez set status to `closed`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_5"></a>|@adiroiban set status to `reopened`|
|-|-|

Was reverted due to [#10235](https://github.com/twisted/twisted/issues/10235)

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_6"></a>|@wsanchez commented|
|-|-|

Just to clarify… it looks like [#10235](https://github.com/twisted/twisted/issues/10235) was addressed by [PR 1367](https://github.com/twisted/twisted/pull/1637), which reverted part of this ticket, but not all of it.

In particular, it reverts a change related to the use of the now built into supported Python's `__qualname__` attribute on callables, because Python only provides that for functions, and so callables like classes broke.

[Jonathan de Jong comments in the PR](https://github.com/twisted/twisted/pull/1637#pullrequestreview-713010725) that this is easily fixed for classes.  That comment wasn't replied to prior to merging, perhaps because this was just being done to get the release moving.

All that said, this was an opportunistic cleanup of code, and the rest of this ticket was left intact, I'm inclined to close this again.  Sound right?

**Comment by exarkun** [comment]
The DelayedCall `__repr__` changes don't seem strongly related to the task of "Add type hints for twisted.internet.task" so I am closing this again.

#6066 which was closed on the basis of exactly the reverted revision should still be open, though, and I have re-opened it since it was left closed.
