### ISSUE TITLE
TrialRunner and DistTrialRunner runUntilFailure should re-collect before re-run

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10162]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10162|
|Type|defect|
|Created|2021-03-29 22:39:53Z|

The problem is that when a test is re-run it's init is not called again.

One problem is that cleanup is not cleared and the cleanups will continue to accumulate.

One option is to deprecate the current `runUntilFailure(suite)` method and replace it with a new `runUntilFail(suiteLoader)` method.

Then before each re-run suiteLoader can be called. 

We need to see if this new API works with DistTrialRunner

An easy way to trigger this error

```
$ trial -u twisted.trial._dist.test.test_disttrial.DistTrialRunnerTests.test_minimalWorker
```

<details><summary>Searchable metadata</summary>

```
trac-id__10162 10162
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__trial trial
keywords__None None
time__1617057593077465 1617057593077465
changetime__1617057593077465 1617057593077465
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
The one specific problem described sounds like it was the same as #10320 which is now fixed.

Is there still a reason to change how runners collect the suite?

**Comment by adiroiban** [comment]
Thanks. Yes. Duplicate.
