### ISSUE TITLE
t.i.i.IAddress API docs has incomplete list of implementations

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10197]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#10197|
|Type|defect|
|Created|2021-05-17 16:07:07Z|

The [twisted.internet.interfaces.IAddress](https://twistedmatrix.com/documents/current/api/twisted.internet.interfaces.IAddress.html) API documentation page contains this list of implementations:

> Known implementations: twisted.conch.ssh.address.SSHTransportAddress, twisted.internet.stdio.PipeAddress, twisted.internet.stdio.PipeAddress, twisted.pair.tuntap.TunnelAddress, twisted.protocols.loopback._LoopbackAddress, twisted.trial._dist.worker.LocalWorkerAddress, twisted.web.http._XForwardedForAddress

This list omits all the implementations from [t.i.address](https://twistedmatrix.com/documents/current/api/twisted.internet.address.html):

* IPv4Address
* IPv6Address
* HostnameAddress
* UNIXAddress

Since these are the most common and important implementations they should be included.

At the time of this writing the linked page says:

> generated by pydoctor 20.12.1 at 2021-02-28 19:53:36. 

<details><summary>Searchable metadata</summary>

```
trac-id__10197 10197
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__pydoctor pydoctor
keywords__None None
time__1621267627036741 1621267627036741
changetime__1621267685499907 1621267685499907
version__None None
owner__None None

```
</details>

**Comment by tristanlatr** [comment]
All implementations now show up. There is a test in pydoctor to ensure no regressions will be introduced. So I'm closing this issue. 

<img width="985" alt="Capture d’écran, le 2022-11-12 à 12 54 31" src="https://user-images.githubusercontent.com/19967168/201487926-bb224e11-af37-4c9d-bdbd-f51bdbb761e7.png">

**Comment by adiroiban** [comment]
Thanks. I guess that this was fixed by updating pydoctor in a separate PR

I can see the IPv4Address in the list of implementation

https://docs.twistedmatrix.com/en/twisted-22.10.0/api/twisted.internet.interfaces.IAddress.html
