### ISSUE TITLE
Test failures and hang when GTK+4 is installed in the system

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10200]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)| @mgorny reported|
|-|-|
|Trac ID|trac#10200|
|Type|defect|
|Created|2021-05-21 22:52:30Z|

I can reproduce the problem with 21.2.0 and git cae365213868e8226a055f6b5e4d2c0c89c9ab3b.

If GTK+4 is installed, the test runner gives the following warning:

```
$ PYTHONPATH=build/lib python3.9 -m twisted.trial -x twisted 
/tmp/twisted/build/lib/twisted/internet/test/test_gireactor.py:28: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
```

Then a fair number of tests fail, and the test suite eventually seems to hang on NewFetchTests -> testFetchEnvelope.

If I add `-x` option, the first test failures I get is:
```
[ERROR]
Traceback (most recent call last):
  File "/tmp/twisted/build/lib/twisted/internet/test/test_gireactor.py", line 100, in test_gtkApplicationActivate
    reactor = gtk3reactor.Gtk3Reactor()
  File "/tmp/twisted/build/lib/twisted/internet/gtk3reactor.py", line 35, in __init__
    gireactor.GIReactor.__init__(self, useGtk=True)
  File "/tmp/twisted/build/lib/twisted/internet/gireactor.py", line 73, in __init__
    _glibbase.GlibReactorBase.__init__(self, GLib, _gtk, useGtk=useGtk)
  File "/tmp/twisted/build/lib/twisted/internet/_glibbase.py", line 115, in __init__
    self._pending = self._gtk.events_pending
  File "/usr/lib/python3.9/site-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
builtins.AttributeError: 'gi.repository.Gtk' object has no attribute 'events_pending'

twisted.internet.test.test_gireactor.GApplicationRegistrationTests.test_gtkApplicationActivate
```

I'm going to try making a patch for it.

<details><summary>Searchable metadata</summary>

```
trac-id__10200 10200
type__defect defect
reporter__mgorny mgorny
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__review review
time__1621637550918891 1621637550918891
changetime__1627536347422898 1627536347422898
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_1"></a>|@mgorny commented|
|-|-|

https://github.com/twisted/twisted/pull/1600

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_3"></a>|@mgorny commented|
|-|-|

Ping.

**Comment by karlp** [comment]
I'm seeing this too.  Trying a "simple" gtk app developed a while ago, on a newer system with gtk 4 produces the same errors:

A workaround seems to be to add
```
import gi
gi.require_version('Gtk', '3.0')
```
before the ```gtk3reactor.install()``` step in the documents here:  https://docs.twisted.org/en/twisted-22.8.0/core/howto/choosing-reactor.html#gtk-3-0-and-gobject-introspection

(And yes, I now see that's what #1600 does explicitly! yay)

**Comment by adiroiban** [comment]
@karlp if you have time and can test the exact patch from the PR, it would be great.

if the patch works and our CI is green, I think that we can merge the pr... even if we don't have GTK4 tests.


We now have GTK tests on CI... I don't know if GTK2 or GTK3 ... and now it might be easy to add gtk4 tests to the CI

**Comment by karlp** [comment]
For my own application, it _works_ however, I still had to edit my own code.  I had:

```
# blah other imports
from gi.repository import Gtk   # <<< this triggers a gtk import too early!

# Must be before pymodbus is imported!
from twisted.internet import gtk3reactor

reactor = gtk3reactor.install()

# blah, more imports..
```

The patch in #1600 "fails"  on this code with a 
```
  File "/home/karlp/src/cbms3/desktop/softbar2/.env3/lib64/python3.10/site-packages/twisted/internet/gireactor.py", line 73, in __init__
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.10/site-packages/gi/__init__.py", line 117, in require_version
    raise ValueError('Namespace %s is already loaded with version %s' %
ValueError: Namespace Gtk is already loaded with version 4.0
```

This is... maybe fine?  I fixed it by just moving the ```from gi.repository import Gtk``` line to _after_ the gtk3reactor.install() call?
With that ordering change, I get a functional app again.  And that error message is a _lot_ easier to try and understand (IMO) than the ```'gi.repository.Gtk' object has no attribute 'events_pending'``` garbage :)

Unfortunately this is _really_ not my area of expertise, so I can't say much further on what's "right".

**Comment by adiroiban** [comment]
Thansk for the test.

If the patch doens't work for you, I think that it needs changes

I think that the goal of #1600 is have Twisted works with GTK4 without any extra modifications.

**Comment by glyph** [comment]
See #11706 for a draft of fixes to this cluster of issues.

The short version is "we don't need to import gtk at all any more, everything goes through the `Gio.Application` interface nowadays"

**Comment by adiroiban** [comment]
https://github.com/twisted/twisted/pull/11706 is now ready for review, if some of you guys want to check it.

**Comment by glyph** [comment]
See the PR; #11705 is landed.
