### ISSUE TITLE
In conch _kex.getSupportedKeyExchanges use backend.ed25519_supported()

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10206]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10206|
|Type|defect|
|Created|2021-05-26 00:26:31Z|

The current code uses `supported = backend.x25519_supported()` ... but we don't need X25519 , but Ed25519. 

In theory Ed25519 is supported since OpenSSL 1.1.1 at the same level as X25519

In practice it needs OpenSSL 1.1.1b 

See https://github.com/pyca/cryptography/issues/5164

<details><summary>Searchable metadata</summary>

```
trac-id__10206 10206
type__defect defect
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__None None
time__1621988791695611 1621988791695611
changetime__1626936776804252 1626936776804252
version__None None
owner__adiroiban adiroiban

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

pr at https://github.com/twisted/twisted/pull/1605

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph set owner to @adiroiban|
|-|-|

The PR is closed, so removing from the queue.

**Comment by adiroiban** [comment]
I think that this can be closed. The issue was with Ubuntu 18.04, which it's now EOL

**Comment by cjwatson** [comment]
FWIW, even Launchpad (on whose behalf I'd been routinely making an annoyance of myself by needing support on old versions of Ubuntu) is deployed on Ubuntu 20.04 now.

I no longer work on Launchpad, so I probably won't be annoying you from here on in, but perhaps one of my former colleagues will. :-)
