### ISSUE TITLE
python 3.10b4

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10224]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)| @graingert reported|
|-|-|
|Trac ID|trac#10224|
|Type|release blocker: release process bug|
|Created|2021-07-11 21:13:46Z|

<details><summary>Searchable metadata</summary>

```
trac-id__10224 10224
type__release_blocker__release_process_bug release blocker: release process bug
reporter__graingert graingert
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1626038026033637 1626038026033637
changetime__1643280111409709 1643280111409709
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="richvdh's avatar" src="https://avatars.githubusercontent.com/u/1389908?s=50" width="50" height="50">](https://github.com/richvdh)<a name="note_1"></a>|@richvdh commented|
|-|-|

can this be closed? looks like it was handled in https://github.com/twisted/twisted/pull/1625.

**Comment by exarkun** [comment]
Looks like it to me.
