### ISSUE TITLE
ssh key negotiation bug

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10241]
|[<img alt="cocobear's avatar" src="https://avatars.githubusercontent.com/u/181942?s=50" width="50" height="50">](https://github.com/cocobear)| @cocobear reported|
|-|-|
|Trac ID|trac#10241|
|Type|defect|
|Created|2021-07-28 01:51:54Z|

I'm using SSHServerTransport connect to my server, it failed, then I found there is a problem in ssh key negotiation.

```
        # These are the server directions
        outs = [encSC, macSC, compSC]
        ins = [encCS, macSC, compCS]
```

this piece of code is wrong, should be:

```
        # These are the server directions
        outs = [encSC, macSC, compSC]
        ins = [encCS, macCS, compCS]
```

<details><summary>Searchable metadata</summary>

```
trac-id__10241 10241
type__defect defect
reporter__cocobear cocobear
priority__highest highest
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__conch conch
keywords__review_ssh_key_negotiation review ssh key negotiation
time__1627437114799030 1627437114799030
changetime__1627439054122231 1627439054122231
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="cocobear's avatar" src="https://avatars.githubusercontent.com/u/181942?s=50" width="50" height="50">](https://github.com/cocobear)<a name="note_1"></a>|@cocobear commented|
|-|-|

Here is PR :
https://github.com/twisted/twisted/pull/1643

**Comment by adiroiban** [comment]
Fixed in https://github.com/twisted/twisted/pull/1643
