### ISSUE TITLE
t.c.checkers.UNIXAuthorizedKeysFiles passes bytes to getpwnam

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10286]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#10286|
|Type|defect|
|Created|2021-12-27 20:26:57Z|
|Branch|https://github.com/twisted/twisted/tree/10286-pwd-checkers-types|

Per [chat](https://gitter.im/twisted/twisted?at=61c73ee65ee4df335ab336fe) `twisted.conch.checkers.UNIXAuthorizedKeysFiles` passes `bytes` to getpwnam, which only accepts `str`. Appears to be a Python 3 porting/mocking error.

https://github.com/twisted/twisted/blob/dee676b040dd38b847ea6fb112a712cb5e119490/src/twisted/conch/checkers.py#L452

Similar to [#9130](https://github.com/twisted/twisted/issues/9130)

<details><summary>Searchable metadata</summary>

```
trac-id__10286 10286
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__10286_pwd_checkers_types 10286-pwd-checkers-types
branch_author__ 
status__closed closed
resolution__fixed fixed
component__conch conch
keywords__None None
time__1640636817513431 1640636817513431
changetime__1653284950572131 1653284950572131
version__None None
owner__twm twm

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_2"></a>|@twm commented|
|-|-|

WIP PR here: https://github.com/twisted/twisted/pull/1678

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

ticket:10335 was a duplicate of this, and I made a branch there to fix it as well

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_4"></a>|@twm set status to `closed`|
|-|-|

Merged in: https://github.com/twisted/twisted/commit/14f36c228a83ecb9fd45cf28c83a07fa6e9cf749

**Comment by glyph** [comment]
Just saw this on 22.8.0.rc1, with the equivalent of `twist conch --auth=sshkey` .

```
2022-08-29T07:31:45+0000 [twisted.conch.ssh.userauth.SSHUserAuthServer#critical] Error checking auth for user b'user'
	Traceback (most recent call last):
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/ssh/userauth.py", line 285, in auth_publickey
	    return self.portal.login(c, None, interfaces.IConchUser)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/cred/portal.py", line 120, in login
	    ).addCallback(self.realm.requestAvatar, mind, *interfaces)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 531, in addCallback
	    return self.addCallbacks(callback, callbackArgs=args, callbackKeywords=kwargs)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 511, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
	    current.result, *args, **kwargs
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/ssh/userauth.py", line 208, in _ebMaybeBadAuth
	    reason.trap(error.NotEnoughAuthentication)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/python/failure.py", line 480, in trap
	    self.raiseException()
	  File "/code/env/lib/pypy3.8/site-packages/twisted/python/failure.py", line 504, in raiseException
	    raise self.value.with_traceback(self.tb)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
	    current.result, *args, **kwargs
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/unix.py", line 49, in requestAvatar
	    user = UnixConchUser(username)
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/unix.py", line 57, in __init__
	    self.pwdData = pwd.getpwnam(self.username)
	builtins.TypeError: expected str, got bytes object
```

**Comment by adiroiban** [comment]
I guess that since this was reopened, we need to auto revert the merge for the associated PR

That is revert commit https://github.com/twisted/twisted/commit/14f36c228a83ecb9fd45cf28c83a07fa6e9cf749

And do the same revert in the release branch.

Is that correct?

**Comment by twm** [comment]
> I guess that since this was reopened, we need to auto revert the merge for the associated PR

Are the changes in the patch incorrect, or merely incomplete?

**Comment by twm** [comment]
@glyph This doesn’t look like what I was trying to fix here:

```
	  File "/code/env/lib/pypy3.8/site-packages/twisted/conch/unix.py", line 57, in __init__
	    self.pwdData = pwd.getpwnam(self.username)
	builtins.TypeError: expected str, got bytes object
```

Here is the offending line:

https://github.com/twisted/twisted/blob/26c3c04e55d0b25532709e1e1dc5d1433dde80f3/src/twisted/conch/unix.py#L57

I didn't touch this file. I only fixed `UNIXAuthorizedKeysFile`.

Incidentally this may have worked before in PyPy (only PyPy) but as part of this project I reported the behavioral discrepancy upstream: https://foss.heptapod.net/pypy/pypy/-/issues/3624 So... you're welcome and please forgive me?

As it doesn't appear that there's evidence that `UNIXAuthorizedKeysFile` has regressed I'm reclosing this ticket and reopening #10335. I do not see any reason to revert here &mdash; fixing the Conch CLI was never the goal.

**Comment by twm** [comment]
See #11626 which I just filed based on @glyph's comment. I don't think this is a release blocker as it has been broken for many releases.
