### ISSUE TITLE
It is difficult for applications to take advantage of `async def` for interface methods defined as maybe returning a Deferred

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10327]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#10327|
|Type|enhancement|
|Created|2022-04-06 23:53:01Z|

Presently Twisted exposes quite a few interface with methods which are explicitly documented as maybe or maybe not returning a Deferred.

Within Twisted, and usually in application code consuming these interfaces, the most common implementation technique for consuming these interfaces is to call the method using `twisted.internet.defer.maybeDeferred` which will pass a Deferred result through unmodified and convert all synchronous results into the corresponding Deferred result.

For the time when these interfaces were defined, this was kind of okay.  Increasingly, it is clear that this Deferred-or-not behavior is more of a hindrance than a help to good code.  `maybeDeferred` does a serviceable job of papering over the difference but callers need to remember to use it every time and then consider how many of the cases it covers they want to write automated tests for.

Conveniently, `async def` completely eliminates the "or-not" cases by forcing the result to *always* be a "coroutine".  This allows for a simplified return type and gives you a function that requires no helper to safely and easily call.

In a world where `async def` is prevalent, there is no need for `maybeDeferred` at all.

How, though, does an application implementing a Twisted interface with a method that is declared as returning Deferred-or-not make the transition to this new world?

Strictly speaking, an `async def` function returns a coroutine - which is *not* a Deferred.  Therefore, to correctly implement the interface, the caller should handle the result as if the coroutine itself is the value... *Practically* speaking, this is nonsense and no one is writing code that wants this behavior.

If Twisted were to follow the compatibility policy to the letter, the solution here would be to introduce new interfaces (or maybe just new interface methods) everywhere there is a Deferred-or-not return type.  The new interfaces would dictate a coroutine return type and no "or-not" return case.

Then, optionally, the old interfaces would be deprecated and later removed.

To follow this path, a lot of maintenance work is required inside Twisted itself.  Then, more work is required in all application code that implemented any of these interfaces.  Later, more Twisted maintenance work is required to remove the deprecated interfaces and related support code.

The deprecation and removal steps *could* be skipped (that is, leave in support for the non-coroutine cases) to save some maintenance work inside Twisted itself.  However, this leaves two parallel universes in Twisted forever which increases the difficulty of learning to use Twisted and of maintaining all Twisted-based software - forever.

Since, *practically*, there is no application code out there expecting to be able to return a coroutine and have that coroutine itself be the result of the function, there is an easier route.

That is for every interface which Twisted declares as "Deferred-or-not" to become "Deferred-or-coroutine-or-not".  With no modification to application code, there is no change in behavior for the cases where the the application code returned a Deferred or a non-coroutine value.  For application code that returned a coroutine (approximately: defines the method with `async def`), Twisted would schedule the coroutine and adapt it to Deferred so that the resulting behavior is like the application code had been a normal `def` function that returned a Deferred.

The implementation change in Twisted that would most easily create this result would be to have `maybeDeferred` itself add a case for coroutine return values.  Of course, Twisted could also leave `maybeDeferred` alone, add a new function with the new behavior, and then change all of its internal uses of `maybeDeferred` to use the new function instead.  This would have the upside of more strictly preserving compatibility in a different area (`maybeDeferred`, as opposed to in the handling of results from all of the affected interfaces) but the downside that any application code calling Deferred-or-not methods with `maybeDeferred` would not inherit the behavior.

Looking further forward, since this provides a low-effort and extremely incremental path to completely replacing Deferred-or-not APIs with coroutine APIs, it means that it is a big step towards a time when we can deprecate the Deferred-or-not case, then remove it, then remove `maybeDeferred` itself.

The proposal here is potentially a breaking change for application code that returns a coroutine from a Deferred-or-not method and *means* to return the coroutine, not use the coroutine as a mechanism to communicate the eventual result of an asynchronous operation.  I suggest that there is practically no such code that does this and the cost of updating it to work with the change is much less (to all involved parties) than the cost of the other options - and so it is worth breaking the compatibility policy for this change.

<details><summary>Searchable metadata</summary>

```
trac-id__10327 10327
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__review review
time__1649289181451560 1649289181451560
changetime__1650908725446183 1650908725446183
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Here the diff giving a possible implementation:

```
diff --git a/src/twisted/internet/defer.py b/src/twisted/internet/defer.py
index 802dad5ee0..a6db7acaa5 100644
--- a/src/twisted/internet/defer.py
+++ b/src/twisted/internet/defer.py
@@ -195,6 +195,8 @@ def maybeDeferred(
         return result
     elif isinstance(result, Failure):
         return fail(result)
+    elif iscoroutine(result) and not isinstance(result, GeneratorType):
+        return Deferred.fromCoroutine(result)
     else:
         return succeed(result)
```

This passes as much of the Twisted test suite as current trunk@HEAD in my dev env.

The `GeneratorType` check was a surprise to me (and is required to avoid some failures).  I initially thought `defer.py` had imported `inspect.iscoroutine` but it actually imports `asyncio.iscoroutine` which is maddeningly different.

Possibly a different implementation based on `inspect.iscoroutine` would be preferable for identifying the cases where the new behavior is desired.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

https://github.com/twisted/twisted/pull/1718

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @exarkun|
|-|-|

Reviewed on github.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph removed owner|
|-|-|

Except… wait, it still needs to be in review because other committers need to look at it?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun set status to `closed`|
|-|-|

Fixed in https://github.com/twisted/twisted/commit/09fa825d195562e98b9603da184ad8c0f6424d84

**Comment by exarkun** [comment]
This was a duplicate of #9813
