### ISSUE TITLE
Get support for Python 3.11

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#10343]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#10343|
|Type|enhancement|
|Created|2022-05-11 20:27:34Z|

Some info at https://github.com/twisted/twisted/pull/1723#issuecomment-1107654772 from Colin

BTW, I haven't attempted to add test runs for 3.11 yet because there are some other problems.  We need a Cython release with cython/cython[#4667](https://github.com/twisted/twisted/issues/4667), an Automat release with glyph/automat[#7453](https://github.com/twisted/twisted/issues/7453), there are some weird `builtins.TypeError: __dict__ must be set to a dictionary, not a '_Dereference'` test failures that I don't understand, and there are a few fairly trivial test failures due to https://docs.python.org/3.11/whatsnew/3.11.html#enhanced-error-locations-in-tracebacks.  But it's generally looking closer, and this on its own is enough to let me get the testtools test suite passing.

<details><summary>Searchable metadata</summary>

```
trac-id__10343 10343
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1652300854237229 1652300854237229
changetime__1652425385864237 1652425385864237
version__None None
owner__None None
cc__mgorny
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="mgorny's avatar" src="https://avatars.githubusercontent.com/u/110765?s=50" width="50" height="50">](https://github.com/mgorny)<a name="note_1"></a>|@mgorny commented|
|-|-|

You can run tests using cython from 0.29.x git branch.  In virtualenv it's a bit of PITA because of the new fancy PEP517 logic that insists on building using pypi's current cython but it's doable if you use `setup.py install` instead.

**Comment by adiroiban** [comment]
From gitter https://gitter.im/twisted/twisted?at=63529430bad3c73752e7654a

from @DMRobertson

> Hi all. I've been trying to run Synapse in CI against Python 3.11 RCs, but I'm running into some new errors. One class of [errors involves `code` objects](https://github.com/matrix-org/synapse/actions/runs/3275412420/jobs/5390339185#step:7:3808), and I [think](https://github.com/matrix-org/synapse/pull/13812#issuecomment-1247083641) is fixed in recent Twisted releases provided you use a sufficiently new version of `automat`. (See https://github.com/glyph/automat/issues/139#issuecomment-1273146975)
> 
> I reached out [here](https://github.com/glyph/automat/issues/139) to ask if there were plans to make a new release but haven't heard back. Does anyone here know more?

**Comment by eevelweezel** [comment]
I've created a PR for enabling tests against Python 3.11. There's still a huge number of failing tests.  There's a ticket for fixing the jelly tests, should I create others for fixing the rest?
