### ISSUE TITLE
Add documentation search to site (including searching API)

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#11343]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#1546|
|Type|enhancement|
|Created|2006-03-06 15:48:17Z|

The trac search doesn't cover these pages.

<details><summary>Searchable metadata</summary>

```
trac-id__1546 1546
type__enhancement enhancement
reporter__itamarst itamarst
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__website website
keywords__documentation documentation
time__1141660097000000 1141660097000000
changetime__1612488691832290 1612488691832290
version__ 
owner__ 
cc__tekNico cc__thijs cc__khorn
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun commented|
|-|-|

http://www.google.com/search?hl=en&q=site%3Atwistedmatrix.com%2Fdocuments%2Fcurrent%2Fapi%2F+conch&btnG=Google+Search

Sure, I suppose we could add a form that posts to google.

**Comment by twisted-trac** [comment]
|[<img alt="teknico's avatar" src="https://avatars.githubusercontent.com/u/172521?s=50" width="50" height="50">](https://github.com/teknico)|@teknico set owner to @teknico|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="teknico's avatar" src="https://avatars.githubusercontent.com/u/172521?s=50" width="50" height="50">](https://github.com/teknico)|@teknico set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

This should be fixed if/when we switch to Sphinx..

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @khorn<br>@thijstriemstra set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_7"></a>|@khorn commented|
|-|-|

I have a "cunning plan" for this, but I'm trying to get the Sphinx convo done first.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_9"></a>|@adiroiban commented|
|-|-|

See https://github.com/twisted/pydoctor/issues/356 as one option, with Twisted docs hosted by Read The Docs

**Comment by adiroiban** [comment]
We have a new site https://twisted.org/ 

The docs (narrative and api) are hosted on Read the docs.
RTD has its own embedded elastic search feature.
I think that we should rely on that.

There is a ticket for pydoctor to integrate with Read The Docs search - https://github.com/twisted/pydoctor/issues/356

-----------

I think that this can be closed.

The plan is not to have any Twisted/twisted specific search code.

Instead use RTD code.

-----------

I hope that pydoctor will implement that search feature soon.

And by just upgrading to pydoctor, we can have this feature.

--------

I think that this ticket can be closed.

We don't have enough resources to create our custom search tools
