### ISSUE TITLE
GitHub based review workflow

### ISSUE THREAD

**Issue by danuker** [twisted/twisted#11564]
So let's talk about workflow requirements.  Here are the requirements that must be met in order to migrate:

1. Reviewers (members of @twisted/twisted-contributors) must be able to enumerate the PRs available for review, so that they can use their limited code-review time to look only at things that need attention and not get overwhelmed with the much larger number of tickets that do not need review, either because they're just drafts so far or because they have been had changes requested but the author has not indicated that they're ready again. So we need a link that people can go to.
2. External contributors (people who open PRs who are not members of the aforementioned team) must be able to request re-reviews when they have addressed feedback.  This is where github's native workflow falls down: for some reason, "requesting a review" is a privileged operation.  ( See here: [Note: Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) )

(I will talk about our proposed solutions in a second comment.)

_Originally posted by @glyph in https://github.com/twisted/twisted-trac-migration/issues/1#issuecomment-1146884597_

**Comment by danuker** [comment]
The ideal solution here is to integrate with Github's native workflow.  We can do this with only one feature: add the ability (probably via a special comment) for a PR author to request a review from the contributors team.

If this is the case:

1. Reviewers can simply look at https://github.com/pulls/review-requested and get requested reviews from *all* their projects, or https://github.com/twisted/twisted/pulls/review-requested to find the ones specifically for Twisted.
2. Contributors can leave a comment saying "review please" and get back into the relevant queue.

The one extra detail here is that reviewers are then responsible for dismissing any needs-changes review when they give an approval.  This will be possible for any member of twisted-contributors because [as documented here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/dismissing-a-pull-request-review):

> … repository administrators or people with write access can dismiss a review.

_Originally posted by @glyph in https://github.com/twisted/twisted-trac-migration/issues/1#issuecomment-1146885274_

**Comment by danuker** [comment]
Will delete the migration test repositories, so I posted these here to keep in mind.

**Comment by adiroiban** [comment]
I guess that this is about defining the review process based on Github.

See what automation / helpers are required outside of GitHub and see what we can automated using GitHub actions.

Also, while working on this, I think we should move/document this process somewhere here https://docs.twistedmatrix.com/en/stable/core/development/policy/index.html

**Comment by adiroiban** [comment]
We can look at "issues" workflow in a separate ticket. For example when a ticket is closed, automatically removed the "new" label.

**Comment by glyph** [comment]
Do we have the "review please" bot yet?

**Comment by adiroiban** [comment]
not yet. but I think the bot should be a top priority.

We already have the foundation code for the bot.

it needs to be deployed and enabled for twisted/twisted and looks into the security details.

The problem is that for someone to assign reviewers, that someone or that token needs admin permissions to the repo... at least when using PAT... or maybe it's just a github UI issue and we can generate a token with limited permissions

**Comment by adiroiban** [comment]
We have deployed a testing PR/issue labeler robot for twisted/twisted

I will look to update the review documentation and create a PR that we can use to test  the robot.

**Comment by glyph** [comment]
I don't see any discussion here about why labels were selected rather than native review state. What happened there?

**Comment by danuker** [comment]
Sorry for not discussing.

The reason is "mere mortal" people (not-yet-contributors) can neither request a review, nor assign people, nor be assigned to a ticket, nor set labels. To test, see a public project you're not a contributor/member of. Even tickets you open yourself can't be labeled or assigned.

We can not assign a PR to a "mere mortal" either, to indicate that we want more feedback or changes from them.

At Chevah we use a bot managing labels and assignees. We have commands like "please review" or "please change" or "please merge".

Then, it sets a label like needs-merge (green) or needs-review (yellow) or needs-changes (beige), so the status of the PR can be seen at a glance, in the [big list](https://github.com/twisted/twisted/pulls). Also, it sets an assignee where possible (@adiroiban suggested assigning twisted/twisted-contributors when someone needs a review).

The bot is mostly implemented, it is a question of a few adaptations for Twisted: https://github.com/chevah/github-hooks-server/issues/33

We think it would benefit Twisted until we find a better solution (or **if** we find one).

Feedback is most appreciated!

**Comment by glyph** [comment]
I understood 90% of that, I was just literally asking why it was using labels as opposed to having "please review" acutally request the review from the team.

It sounds like the answer to that question is "because we already have code that implements this using labels" which is absolutely a fine answer for me :).

I think we should eventually shift to something that (A) uses github actions to avoid having yet another thing to host, and (B) can integrate more natively with github's code review workflow, but that is undoubtedly a ton of work, so this is a great interim state.

**Comment by danuker** [comment]
> "because we already have code that implements this using labels" which is absolutely a fine answer for me :).

> (B) can integrate more natively with github's code review workflow

I know what you know now :)

Indeed, that is most of the answer, but also we did not know about the [review requests API](https://docs.github.com/en/rest/pulls/review-requests). ~~Perhaps it is new~~ [It is not new](https://stackoverflow.com/a/40398678/235463) - we did not know about it, and maybe we will move towards a workflow including it.

> (A) uses github actions

It could address the initial opening of a PR, but not subsequent feedback rounds. But a problem is that we can't react to PR comments or reviews through Actions.

**Comment by glyph** [comment]
> It could address the initial opening of a PR, but not subsequent feedback rounds. But a problem is that we can't react to PR comments or reviews through Actions.

Here's an example action that reacts to PR comments: https://github.com/marketplace/actions/pull-request-comment-trigger

And here's an example that reacts to reviews: https://github.com/Piidro/pr-review-trigger

**Comment by danuker** [comment]
Well, that is amazing. Thanks for the info! We will steer that way (eventually).

**Comment by adiroiban** [comment]
@glyph have you seen those actions deployed in real life for an open source project?

The problem with action-based tools is that they only works for "collaborators".
They are designed to prevent privilege elevation.

our problem here is that normal (non-team) users can't assign tickets or reviewers, so we need a gatekeeper with higher permissions.

Actions triggered by external team members or forks will not have admin access to the PR meta-data.

GitHub solution for this is using "GitHub Apps"  ... but GitHub actions can't help.

**Comment by adiroiban** [comment]
@danuker I think that the top priority for now is getting https://github.com/chevah/github-hooks-server/issues/42 fixed 

step2 would be that instead of assigning users, we should "request review" using this api https://docs.github.com/en/rest/pulls/review-requests#request-reviewers-for-a-pull-request

----------

The initial code for the robot was written more than 10 years ago when GitHub PR tool was very basic...so labels and "assignees"  were the only meta-data available.
