### ISSUE TITLE
Python 3.10.5 with Twisted 22.4.0 will not connect with TLSv1

### ISSUE THREAD

**Issue by vai-brma** [twisted/twisted#11594]
Making a SSL connection fails when TLSv1 is specified. Works Ok for TLSv1_2 or higher.

Use a listenSSL server and a connectSSL client

setting the client method to SSL.SSLv23_METHOD works fine
setting the client method to  SSL.TLSv1_0 or SSL.TLSv1_1 always fails 

(https://gist.github.com/BMtthws/edf52dba3d07e2c951e8cb146799243a)

**Testing environment**
Windows 10
Python 3.10.5
Twisted 22.4.0
iocpreactor
 
This all worked fine in Python 3.8.6 and twisted 20.3.0

**Comment by adiroiban** [comment]
Thanks for the report

Which [cryptography](https://github.com/pyca/cryptography/) version do you use?
Is the OpenSSL library that you use compiled to support TLS 1.0 and 1.1 ?

What error do you get?

**Comment by adiroiban** [comment]
Is this related to #11568

Have you also try running latest Twisted from the `trunk` branch ?

**Comment by vai-brma** [comment]
Yes i believe it is the same as #11568. Cryptography version is 37.0.4
I am wondering if the _openssl.pyd in cryptography has been linked against an OpenSSL compiled with no-tls1 and no-tls1_1
I am going to try a custom build of OpenSSL to rebuild cryptography with.
The cryptography I am currently using was installed with a pip wheel.

**Comment by vai-brma** [comment]
I added some debug callback to the server side. This is what i got
2022-08-10 10-42-09.094 [Host Listener] [MainThread] [DEBUG] SSL handshake: where = 8193, RC = 1
2022-08-10 10-42-09.094 [Host Listener] [MainThread] [DEBUG] SSL handshake: where = 16392, RC = 592
2022-08-10 10-42-09.094 [Host Listener] [MainThread] [DEBUG] SSL handshake: fatal: "internal error" at "b'error'"
2022-08-10 10-42-09.095 [Host Listener] [MainThread] [DEBUG] SSL handshake: failed - TLSv1
2022-08-10 10-42-09.095 [Host Listener] [MainThread] [DEBUG] SSL handshake: where = 8194, RC = -1

**Comment by glyph** [comment]
TLS 1.0 is deprecated and OpenSSL doesn't support it any longer. We probably need to update our documentation to explain current supported versions, and I don't know the authoritative source offhand where OpenSSL said they did this, but #10337 had to do a bunch of updates to get our test suite even passing on recent OpenSSLs to remove even references to TLS1.0.

See for example this article from early 2020: https://www.globalsign.com/en/blog/disable-tls-10-and-all-ssl-versions

As such, we won't be adding this functionality back in.

**Comment by vai-brma** [comment]
The problem is TLSv1 is mentioned all over the docs. Both in twisted and OpenSSL. nobody says it is not supported anymore.
Taking it out might be the better way to do it, but it ignores the fact that not every connection is for Users on browsers. Many machines use embedded code with this stuff in it. This causes a large amount of scrambling to get all the various embedded systems upgraded too. Surely a better way could have been found.
Also, in twisted options like 'insecurelyLowerMinimumTo' no longer make any sense.

**Comment by adiroiban** [comment]
Twisted still works with TLSv1.
The OpenSSL library and Python cryptography library have dropped support for TLS v1 in the latest versions.

You can compile your own OpenSSL and cryptography libraries and then you should have TLSv1 available in Twisted.

---------

Regarding the docs issue. Yes. Updating the docs would be nice.
If you have time to help with the docs, I would be happy to review and merge such a change.
Thanks
