### ISSUE TITLE
"API reference" link should be local to the build documentation

### ISSUE THREAD

**Issue by twm** [twisted/twisted#11599]
On [this page](https://twisted--11598.org.readthedocs.build/en/11598/core/index.html) (built based on PR #11598) the "API reference" link points at `https://twistedmatrix.com/documents/current/api/` but it should it be a relative link that points at the version that was built as part of the PR, `https://twisted--11598.org.readthedocs.build/en/11598/api/index.html`

**Comment by adiroiban** [comment]
Thanks.

Maybe also have this, since the docs are no longer hosted by us.
Maybe also add that the docs are hosted by Read The Docs

```diff
- An [API reference](https://twistedmatrix.com/documents/current/api/) is available on the twistedmatrix web site.
+ An [API reference](../) is available as part of the documentation site.
```


```diff
- An [API reference](https://twistedmatrix.com/documents/current/api/) is available on the twistedmatrix web site.
+ An [API reference](../) is available as part of the documentation site, hosted by Read The Docs.
```

**Comment by twm** [comment]
When viewing this page the user is already on Read the Docs so I'm not sure what that would add?
