### ISSUE TITLE
The GitHub pull request template advises use of the wrong magic words to summon the bot

### ISSUE THREAD

**Issue by exarkun** [twisted/twisted#11606]
`.github/PULL_REQUEST_TEMPLATE` says to use "please review" but investigation reveals that "needs-review" is required instead.

**Comment by adiroiban** [comment]
yes... this is broken as the robot code is not yet implemented.
WIP over here https://github.com/chevah/github-hooks-server/pull/43

the plan is to create the main code and test it via the "chevah-robot"

once all is ok, the code should be deployed via a separated dedicated "twisted-robot"
