### ISSUE TITLE
linux cpu 100% 

### ISSUE THREAD

**Issue by Hudiaov587** [twisted/twisted#11618]
Run twisted for web server

1、After a lots of http requests
2、CPU 100% 
3、Stop http request ( CPU still 100% )

`strace -tp 17816` result:

17:58:57 gettimeofday({1661507937, 757678}, NULL) = 0
17:58:57 gettimeofday({1661507937, 757793}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 59) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 758156}, NULL) = 0
17:58:57 gettimeofday({1661507937, 758301}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 58) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 760410}, NULL) = 0
17:58:57 gettimeofday({1661507937, 760517}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 56) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 760892}, NULL) = 0
17:58:57 gettimeofday({1661507937, 760991}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 56) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 761343}, NULL) = 0
17:58:57 gettimeofday({1661507937, 761408}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 55) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 761745}, NULL) = 0
17:58:57 gettimeofday({1661507937, 761854}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 55) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 762249}, NULL) = 0
17:58:57 gettimeofday({1661507937, 762354}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 54) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 762713}, NULL) = 0
17:58:57 gettimeofday({1661507937, 762774}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 54) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 763116}, NULL) = 0
17:58:57 gettimeofday({1661507937, 763247}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 53) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
17:58:57 gettimeofday({1661507937, 763566}, NULL) = 0
17:58:57 gettimeofday({1661507937, 763638}, NULL) = 0
17:58:57 epoll_wait(3, {{EPOLLOUT, {u32=92, u64=10026390458596327516}}}, 10, 53) = 1
17:58:57 sendto(92, "", 0, 0, NULL, 0)  = 0
......

1.`epoll_wait` and `sendto` loop forever here and waste all cpu time.
2.socket fd 92  state is CLOSE_WAIT.

**Comment by adiroiban** [comment]
Thanks for the report.

Can you share a minimum functional example code.

I am interested in reproducing these parts:

* Run twisted for web server - how, what CLI do you use, what script
* After a lots of http requests - do you have a script to generate that "lots" of requests. what "lots" means  10 requests per second, 10.000 requests per second.

Cheers
