### ISSUE TITLE
Auto-revert the merge commit when an issue is re-opened

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted#11623]
This is an idea dump.

In Trac, we were manually commiting a revert for the merge commit associated with a ticket.
The commit message containd the ticket ID and Trac would automatically reopened the ticket.

-------

For GitHub maybe we can have something different.

If you find that a commit needs to be reverted you search for the original ticket/issue and just reopen it using GitHub UI.

in the background, a GitHub action is triggered with the credentials of the user that did the re-open.

The action can try to find the association PR ... then find the merge commit message for the PR and automatically commit a reverse for that merge. 

If there are any issues, it can send an automatic comment , with info about the error and a reminder to manually revert the merge.

-----------

The reminder and error message should work with any GitHub users.

The reverse can only be done by users who have write access to the repo.

The issue is that the revert commit will normally fail due to:
* Not having a news fragment
* Not having an associated PR
* Not having an approved PR

We need to see if there is a way to bypass the branch protection for this revert commit.

**Comment by adiroiban** [comment]
On GitHub I see this option... which now is enabled

![image](https://user-images.githubusercontent.com/204609/187198344-23e3dafb-3a0f-42fb-bb2c-e9f66dd4743e.png)


and this documentation https://github.blog/changelog/2022-08-18-bypass-branch-protections-with-a-new-permission/

but I don't see if this is available on public cloud, or only on GitHub enterprise server

**Comment by twm** [comment]
A few thoughts: 

1. Does this come up often enough to merit automation?
2. Reverts can result in logical conflicts. Are they truly so routine that they should bypass review? 
3. The confusion on https://github.com/twisted/twisted/issues/10286 seems like evidence that any revert automation shouldn't be linked to the act of reopening an issue.

If automation is desirable I suggest it take the form of a script or bot command rather than something that happens in response to reopening a ticket.

**Comment by adiroiban** [comment]
Thanks for the feedback.

This was something discussed over gitter/irc and I wanted to have something recorded.

I do think that is a lot of work.


Yes. I was thinking to have it implemented as a bot command. When you reopen, also add a command text like "please revert" or something like that.

I don't think that this is very common.

The issues is that is easy to reopen and forget about reverting the merge.

What can the action do at first, is send a reminder as a comment, to consider reverting the PR associated with the issue.

**Comment by adiroiban** [comment]
OK. I will close this. I will open a new one to document and fix the manual revert process.
