### ISSUE TITLE
Update package metadata

### ISSUE THREAD

**Issue by ofek** [twisted/twisted#11655]
**Is your feature request related to a problem? Please describe.**

The Python packaging ecosystem has standardized on the interface for build backends ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 660](https://peps.python.org/pep-0660/)) and the format for metadata declaration ([PEP 621](https://peps.python.org/pep-0621/)/[PEP 631](https://peps.python.org/pep-0631/)). As a result, the execution of `setup.py` files is now [deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

**Describe the solution you'd like**

Use modern packaging standards

**Describe alternatives you've considered**

Doing nothing is an option for now

**Comment by adiroiban** [comment]
Reopening this as the PR will be reverted.
