### ISSUE TITLE
Run tests with `-j` in the tox environments on Linux

### ISSUE THREAD

**Issue by exarkun** [twisted/twisted#11699]
`python -m twisted.trial -j20 twisted` completes successfully on my NixOS development system.  Instead of taking 230 seconds or more, it takes 30 seconds.

The tox environment for running the test suite could provide a `-j...` argument to speed up test suite runs.  This would presumably be a benefit for local development (for those who use tox) as well as on CI (but the number of workers used on CI should be considered and probably tailored to the CI execution environment).

**Comment by adiroiban** [comment]
I think the tox environment already allows injecting the -j

This is what we do for CI ... to allow simple runs on Windows and -j4 on Linux and macOS.

it is called `TRIAL_ARGS`

**Comment by adiroiban** [comment]
now... the TRIAL_ARGS is a generic variable... it is also create to allow selecting what reactor is used by trial.

So maybe you want something simple like TRIAL_JOBS.

**Comment by exarkun** [comment]
I think a developer running tox to run the test suite shouldn't have to add any arguments at all to get _some_ parallelism.  Right now the default developer experience is that the test suite is very slow and wastes most capacity of any modern system.  Instead, the default developer experience should be that the test suite is fast and uses the capabilities of most systems commonly in use today.

Maybe there should also be some options that can be used to tune _how much_ parallelism (or completely disable it) but we should try to make the default behavior good enough that few people ever need to reach for those options.

**Comment by exarkun** [comment]
Thanks for pointing out that CI already does something in this area.  We can leave CI behavior alone and just focus on the local developer experience for this issue.

**Comment by adiroiban** [comment]
OK. So it looks like I thought that we run `-j4` on CI... but I think that is active only for non-coverage

https://github.com/twisted/twisted/blob/3314a7c1a74cfd3315855c40aa085b1a1af00077/tox.ini#L96-L105

We now have an empty TRIAL_ARGS.

maybe for local development we can have a default like this... and CI should alwasy overwrite it.

```diff
-{env:TRIAL_ARGS:} 
+{env:TRIAL_ARGS:-j8}
```

Would that work for you?

**Comment by exarkun** [comment]
That seems reasonable, yea.

Separately we might want to teach trial to be able to discover an appropriate number of workers to run on its own so we don't have to keep fiddling with numbers like `4` and `8` in the config.

**Comment by adiroiban** [comment]
I will try to create a pr for this.
