### ISSUE TITLE
NameVirtualHost Host header injection

### ISSUE THREAD

**Issue by twm** [twisted/twisted#11716]
See GHSA-vg46-2rrj-3647.

**Comment by adiroiban** [comment]
I think that this can now be made public

it was merged in https://github.com/twisted/twisted/commit/f2f5e81c03f14e253e85fe457e646130780db40b

This is the issue for https://github.com/twisted/twisted/security/advisories/GHSA-vg46-2rrj-3647

One thing to take into consideration when working on security advisories PR.
The fork + PR + pr comments are automatically removed and lost of after the "security PR" is merged into the main repo.

Just to keep and mind and don't leave any important info only on the "security PR"

**Comment by twm** [comment]
Fun, the PR from the advisory completely disappeared, so the text for this issue I drafted there is gone. I guess the advisory text will have to do.
