### ISSUE TITLE
Dep on attrs should be >= 21.3.0

### ISSUE THREAD

**Issue by twm** [twisted/twisted#11737]
`import attrs` (vs. `import attr`) was introduced in [attrs 21.3.0](https://www.attrs.org/en/stable/changelog.html#id17).

We currently depend on attrs >= 19.2.0:

https://github.com/twisted/twisted/blob/8e7857d08355273179ca330c55f41713c65254c2/pyproject.toml#L38

We import from the `attrs` module in many places:

```
src/twisted/python/systemd.py:from attrs import Factory, define
src/twisted/trial/_synctest.py:from attrs import frozen
src/twisted/trial/runner.py:from attrs import define
docs/web/howto/listings/render_slots_attrs.py:from slots_attributes_1 import ExampleElement
docs/web/howto/listings/render_slots_attrs.py:from twisted.web.template import flattenString
src/twisted/application/runner/_runner.py:from attr import Factory, attrib, attrs
src/twisted/trial/_dist/disttrial.py:from attrs import define, field, frozen
src/twisted/trial/_dist/disttrial.py:from attrs.converters import default_if_none
src/twisted/trial/_dist/stream.py:from attrs import Factory, define
src/twisted/trial/_dist/worker.py:from attrs import frozen
src/twisted/trial/_dist/workerreporter.py:from attrs import Factory, define
src/twisted/application/runner/test/test_runner.py:from attr import Factory, attrib, attrs
src/twisted/trial/_dist/test/test_disttrial.py:from attrs import Factory, assoc, define, field
```

We should update our minimum dep.

**Comment by adiroiban** [comment]
A similar issue with our invalid minimum deps at #11740

I will create a PR and see how we can detect such errors

**Comment by adiroiban** [comment]
Thanks for the suggestion. I have applied the updated attr version here https://github.com/twisted/twisted/pull/11741

**Comment by adiroiban** [comment]
Thanks for the suggestion. I have applied the updated attr version here https://github.com/twisted/twisted/pull/11741
