### ISSUE TITLE
typing_extensions minimum version should be at least 3.10.0.0

### ISSUE THREAD

**Issue by malerichc** [twisted/twisted#11740]
As of version 22.10.0, typing_extensions.ParamSpec is imported in several places:

src/twisted/internet/defer.py:from typing_extensions import Literal, ParamSpec, Protocol
src/twisted/internet/defer.py:_P = ParamSpec("_P")
src/twisted/trial/runner.py:from typing_extensions import ParamSpec, Protocol, TypeAlias, TypeGuard
src/twisted/trial/runner.py:_P = ParamSpec("_P")
src/twisted/trial/util.py:from typing_extensions import ParamSpec
src/twisted/trial/util.py:_P = ParamSpec("_P")

ParamSpec was introduced in typing_extensions 3.10.0.0 but setup.cfg still
lists typing_extensions 3.6.5 as a minimum version:

https://github.com/twisted/twisted/blob/twisted-22.10.0/setup.cfg#L36

I noticed this issue while trying to use Twisted 22.10.0 with typing_extensions 3.7.4. Here is a reproduction of the error:

```
$ python3.10 -m venv venv
$ ./venv/bin/pip install -q typing_extensions==3.7.4
$ ./venv/bin/pip install -q Twisted==22.10.0
$ ./venv/bin/python -c "from twisted.internet import defer"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/malerichc/venv/lib/python3.10/site-packages/twisted/internet/defer.py", line 42, in <module>
    from typing_extensions import Literal, ParamSpec, Protocol
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/home/malerichc/venv/lib/python3.10/site-packages/typing_extensions.py)
```
`

**Comment by adiroiban** [comment]
Many thanks for the report.

I think we have a similar issue with `attrs >= 19.2.0`

Would updating setup.cfg to a newer version work for you?

**Comment by malerichc** [comment]
Yes of course.

**Comment by adiroiban** [comment]
Your suggestion was applied here https://github.com/twisted/twisted/pull/11741

If you have time, please take a look.

I tried to update the minimum dependency, but at the same time create a CI check, to prevent introducing similar issues in the future.
