### ISSUE TITLE
twisted-iocpsupport 3.11 wheels

### ISSUE THREAD

**Issue by elandorr** [twisted/twisted#11785]
You have many repos, and the link in the other one 404s, so I'm posting here.

Would you consider updating twisted-iocpsupport with windows wheels for 3.11?

To build it on windows, you are forced to install microsoft spyware obliterating the target system's integrity.

I understand 3.11 is very new, but maybe it's as simple as incrementing a number in this case?

Thanks

**Comment by exarkun** [comment]
For reference, here's the Python 3.10 version of this ticket (with some PRs linked) - https://github.com/twisted/twisted/issues/10250

**Comment by mssalvatore** [comment]
I would also find 3.11 wheels to be very valuable. Thanks in advance!

**Comment by elandorr** [comment]
@mssalvatore You might find this useful meanwhile: https://github.com/throwawaymicrosoft1/Visual-CPP-Build-Tools-OFFLINE-installer

I resorted to this (in a VM) to make my own wheels. It's the only standalone version on the internet, but I still don't want their crapware on prod. Besides letting this monster bloatware install, pip+building only takes 5mins. A little annoying, but at least you get to use twisted.

**Comment by mssalvatore** [comment]
Thanks, @elandorr

**Comment by melihsunbul** [comment]
Hey, is there any estimated date to solve the compatibility issue?

**Comment by adiroiban** [comment]
There is a new release (1.0.3) on https://pypi.org/project/twisted-iocpsupport/ 

The work was done  by Glyph here https://github.com/twisted/twisted-iocpsupport/pull/13

I see that Twisted is configured to accept anything above 1.0.2 ... so I think that we are good.

https://github.com/twisted/twisted/blob/525da4a0becad1e814c74f12c365f15fe9cd10de/pyproject.toml#L39-L41

Thanks a lot Glyph 

I think that this can be closed.
Please reopen if you think this is not fixed.

**Comment by adiroiban** [comment]
FYI twisted-iocpsupport 1.0.3  was released with support for 3.12 https://github.com/twisted/twisted-iocpsupport/pull/18
