### ISSUE TITLE
some ciphers for conch triggered deprecation warning with `cryptography>=37`

### ISSUE THREAD

**Issue by llouislu** [twisted/twisted#11793]
**Describe the incorrect behavior you saw**
Some ciphers triggered deprecation warning with `cryptography>=37` when using conch. They are
* `CAST5`
* `SEED`
* `IDEA`
* `Blowfish`
from `cryptography.hazmat.primitives.ciphers.algorithms`.

**Describe how to cause this behavior**
`cryptography>=37` has deprecated these ciphers which will be removed in a future version.
More details https://github.com/pyca/cryptography/pull/6922.

**Describe the correct behavior you'd like to see**
Deprecation warning should be gone.

**Testing environment**
`Twisted==22.10.0` on Mac 12.6 (21G115).

**Comment by adiroiban** [comment]
I know that this ticket was raised first.

I am closing this as duplicate for https://github.com/twisted/twisted/issues/12138

It looks like there is more info there, about what can be done to fix it.
