### ISSUE TITLE
isort is broken

### ISSUE THREAD

**Issue by ghost** [twisted/twisted#11806]
a transitive dependency broke isort (and thus pre-commit and CI)

5.12.0 fixes a bug that was breaking CI everywhere.

https://github.com/PyCQA/isort/releases/tag/5.12.0

**Comment by adiroiban** [comment]
I saw that the branch for the associated PR was removed.

I did a re-run on trunk and I can see that the static checks are now failing 

https://github.com/twisted/twisted/actions/runs/3977849975/jobs/7037202205

-----

The initial commit on trunk from 22 Jan was green, but now at a manual rerun it is red :(

![image](https://user-images.githubusercontent.com/204609/216560897-78c82bd8-fcec-4790-9bb9-fcb0c24ed475.png)

**Comment by felipemelendez** [comment]
> I saw that the branch for the associated PR was removed.

I tried to solve it but the fix turned out to be more involved than I originally thought. I `might` come back to it later, but not sure I'll be able to do it anytime soon.
