### ISSUE TITLE
Unable to use DeferredList as a type hint

### ISSUE THREAD

**Issue by wRAR** [twisted/twisted#11803]
As, quoting the comment in defer.py, "we pretend that DeferredList is a function that returns a Deferred" under `TYPE_CHECKING`, it's not possible to declare that something has a type of `DeferredList`:

> error: Variable "twisted.internet.defer.DeferredList" is not valid as a type  [valid-type]

**Comment by exarkun** [comment]
DeferredList is *actually* a subclass of Deferred so I wonder if it makes sense to just annotate these things as having type Deferred, instead.

What's the use-case for exposing DeferredList as a different type from Deferred?

**Comment by wRAR** [comment]
> DeferredList is actually a subclass of Deferred so I wonder if it makes sense to just annotate these things as having type Deferred, instead.

That's indeed what I thought of as a second-best approach after filing this.

> What's the use-case for exposing DeferredList as a different type from Deferred?

Just making it more precise I guess. I've confirmed that in my case typing functions that return DeferredLists as returning a Deferred works.

**Comment by wRAR** [comment]
Back to this, do you think it's possible to use `Deferred[...]` with proper parameters for `DeferredList` vars without copying `_DeferredListResultItemT` and `_DeferredListResultListT` from `twisted.internet.defer`? Does it make sense to make those public?

**Comment by glyph** [comment]
> Does it make sense to make those public?

I don't think so? They're *repeated* a lot in that code so an alias locally makes sense, but an application that wants to say `Deferred[list[tuple[bool, str]]]` it would not be any more convenient to do

```python3
from twisted.python.defer import DeferredListResultListT

Deferred[DeferredListResultListT[str]]
```

As client code, this is just longer and more tedious and more specific coupling. (You might want `Awaitable[Deferred[list[tuple[bool, str]]]` after all, and `Deferred` doesn't need to get involved as an import.)
