### ISSUE TITLE
fromCoroutine type annotation should probably say it accepts an Awaitable

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#11832]
**Describe the incorrect behavior you saw**
`fromCoroutine` is documented as accepting a `Coroutine` or `Generator` in its type annotations.

However, looking at https://docs.twisted.org/en/stable/api/twisted.internet.defer.Deferred.html#fromCoroutine, its example has it taking the result of an `async fn`, which is an `Awaitable`, I think.

**Comment by glyph** [comment]
The result of calling an `async def` is a `Coroutine`: https://mypy-play.net/?mypy=latest&python=3.11&gist=eebcef1ea7a9c68878d743c065001ab2

**Comment by glyph** [comment]
(`fromCoroutine` explicitly does not support all types of `Awaitable`, which specifically includes `Future` and `Deferred`.)
