### ISSUE TITLE
File opened by _FileDescriptorReservation is not closed

### ISSUE THREAD

**Issue by Stimim** [twisted/twisted#11842]
https://github.com/twisted/twisted/blob/525da4a0becad1e814c74f12c365f15fe9cd10de/src/twisted/internet/tcp.py#L1325

The `_reservedFD` is opened and not closed.  This will trigger resource warning when we set environment variable `PYTHONWARNINGS="error::ResourceWarning"`.

**Comment by exarkun** [comment]
It is closed when it needs to be closed - by the `_reservedFD` context manager implementation.
