### ISSUE TITLE
Calling a sip Client 

### ISSUE THREAD

**Issue by brainhasan** [twisted/twisted#11851]
I want please a small example , i used now Linephone program with standart setting , where i wrote for example ( sip:77794623@10.40.4.209  ) 
and i can calling the client .
i want to do it in python now .
I Know that Twisted Library can doing the call 
could you please write for me an Example !?

**Comment by adiroiban** [comment]
Hi


We use GitHub issues to track defects in twisted code or track development changes.

This looks like a very generic support request.

Please see our documentation page about getting support and help for using Twisted

https://docs.twisted.org/en/latest/community.html

---------

To me, this requests sound like: "Here is what the teacher said, please do my homework."

Are you familiar with the SIP protocol?
Are you familiar with Twisted network protocol development in general?

-----------

I am going to close this.

If you think this is a development-related request, please reopen.

Regards
