### ISSUE TITLE
Enable python 3.12 rc on GitHub Actions

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted#11857]
GHA has 3.12 alpha 

I think that we can give it a try and prepare Twisted for the future Python version.

@hrnciar has already started some cleanup for deprecated and now removed functions.

I think that more will be removed ... crypto / spwd 

List of modules here https://peps.python.org/pep-0594/#deprecated-modules

For 3.12 I think that we are ok, so I expect this to be easy.

3.13 will be more complicated with the removal of `cgi` and `spwd`

**Comment by graingert** [comment]
closing in favour of https://github.com/twisted/twisted/issues/11888
