### ISSUE TITLE
SelectReactor's select should unblock when a new writer or reader is added

### ISSUE THREAD

**Issue by TheCycoONE** [twisted/twisted#11863]
**Describe the incorrect behavior you saw**
When doSelect is called it blocks on the existing set of readers and/or writers or the timeout to occur. I have a situation where a read happens, it is processed on a separate thread which tries to send. This calls addWriter but (depending on timing) not before doSelect is called again with only the read socket. This causes it to block on the timeout rather than send the message.

**Describe how to cause this behavior**
See the description above. As this is a race condition timing is very important; it may be easier to write a harness which calls the SelectReactor methods directly.

**Describe the correct behavior you'd like to see**
A signal socket could be added to the select which is written to when we call addReader or addWriter; this would release the _select call so that the mainLoop can run again with the new reader or writer considered.

Consider the description here: https://stackoverflow.com/a/5206121/749115

**Testing environment**
 - Operating System and Version; paste the output of these commands:
```
ProductName:		macOS
ProductVersion:		13.3.1
ProductVersionExtra:	(a)
BuildVersion:		22E772610a
```
 - Twisted version [e.g. 22.2.0]
`twisted==20.3.0` - though I have verified that the code is the same in the current master as of this ticket.
 - Reactor: SelectReactor

**Comment by exarkun** [comment]
`addWriter` is not a thread-safe API.  You may only call it from the reactor thread.  If you have code in another thread that needs to use it, use `reactor.callFromThread`.

This will wake the reactor and avoid the blocking you describe.

**Comment by TheCycoONE** [comment]
@exarkun that doesn't appear to be the case. I modified freepy with `self.transport.reactor.callInThread(lambda: self.transport.write(serialized_command.encode('utf-8')))` and observe two things:

a) the write still happens in a separate thread from the main loop, it just happens to be from the reactor's twisted.python.threadpool now.
b) no signal is sent to interrupt the socket

**Comment by TheCycoONE** [comment]
Deleted my earlier comment because I mixed up callInThread and callFromThread. callFromThread indeed works. Thanks!
