### ISSUE TITLE
New way to publish to PyPI

### ISSUE THREAD

**Issue by gabibguti** [twisted/twisted#11869]
**Is your feature request related to a problem? Please describe.**
PyPI has created a new and more secure way to publish packages. It's called [Trusted Publishing](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) and it's more secure because it uses short-lived tokens instead of long-lived tokens. Currently, twisted is published using a long-lived token, stored in a GitHub secret, in [`test.yml`](https://github.com/twisted/twisted/blob/trunk/.github/workflows/test.yaml#L375-L379) workflow.

**Describe the solution you'd like**
I'd like us to delete the `PYPI_UPLOAD_TOKEN` secret and make a small change in `test.yml` workflow to do Trusted Publishing.

**Describe alternatives you've considered**
None.

**Additional context**
Hi! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by adiroiban** [comment]
Thanks, Gabriela for the report.

I was planning to enable the new publishing method.
I was helping as release manager in the past...but I don't have access to the token or the Twisted pypi org... the release was done automatically via GitHub Actions tag trigger.

@glyph do you think it would be possible to give me access to twisted/twisted https://pypi.org/project/Twisted/ ? Thanks

**Comment by adiroiban** [comment]
@gabibguti do you have an example in which Trusted Publishing is deployed via a GitHub Action dedicated environment?

I am trying to implement this first in a different project from Twisted Org https://github.com/twisted/towncrier/pull/515

but each CI run is now blocked and needs manual approval.

We would like to trigger the PyPI job only for tags.

Thanks

**Comment by gabibguti** [comment]
@adiroiban

Yes! Here's a good example https://github.com/pypa/pip-audit/blob/main/.github/workflows/release.yml.

Taking a look at https://github.com/twisted/towncrier/pull/515 and PyPI Docs, I've found out that you do need access to the project on PyPI to configure Trusted Publishing to an existing project as in https://docs.pypi.org/trusted-publishers/adding-a-publisher/. Sorry, I was not aware of this configuration previously.

About each CI run being blocked and needing manual approval, I believe that's happening due to the usage of GitHub environment `release-pypi` because the settings can be requiring reviewers. Using GitHub environment does add extra protection for publishing but it's not technically required to use it.

**Comment by adiroiban** [comment]
Thanks for the followup. I will try to get admin rights for PyPI.

Thanks again for the headup. If you want, I think is safe to unsubscribe from this thread and we should be able to do it :) ... GitHub notification are driving me crazy :)

As a general rule for Twisted, we try to have a test run that is as CI-agnostic as possible.
I am not happy at all to trigger the release only when a GitHub release is created or using a separate workflow dispatch event.

This is why, we have the release triggered by a tag creation that matches the version expression.

**Comment by adiroiban** [comment]
@glyph @graingert  - I forgot to setup the new PyPI publishing when doing the 2023.8 release.

I hope I will not forget about this and we can do it in the 2023.9 release, once the HTTP security fixes are merged.
