### ISSUE TITLE
broken out of the box

### ISSUE THREAD

**Issue by jpelletier** [twisted/twisted#11867]
Installing twisted with pip failed:

pip install twisted
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hs9mF9/twisted/

uname -a
Linux bpi-iot-ros-ai 4.4.55-BPI-M2Z-Kernel #1 SMP PREEMPT Fri Apr 10 16:05:55 HKT 2020 armv7l GNU/Linux

cat /etc/lsb-release
cat: /etc/lsb-release: No such file or directory

**Comment by jpelletier** [comment]
pip install --upgrade incremental
   still failed
   Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8BC1XK/twisted/

python -m pip install --upgrade pip
   still failed
ImportError: No module named typing
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Tried with pip3 instead of pip, 
pip3 install twisted
    Worked!

**Comment by adiroiban** [comment]
I guess that this is not an issue.

python2 is no longer supported.

Free free to reopen if this is still an issue.
