### ISSUE TITLE
Clean huge backlog

### ISSUE THREAD

**Issue by chrysle** [twisted/twisted#11864]
**Is your feature request related to a problem? Please describe.**

There are many open issues that do not seem to be of any relevance today. A lot of them (oldest are from 2003), have been opened by an old bug-tracking system (?) named _twisted-trac_. Activity on most of these issues has long since opening ceased. 

**Describe the solution you'd like**

I think it could really help with maintenance and contributing (especially first-time contributors) if the issue tracker is cleansed and it is looked through the old PRs. I personally feel a bit overwhelmed.

**Describe alternatives you've considered**

Being happy with 2.600+ issues and more than hundred PRs open.

**Additional context**

**Comment by exarkun** [comment]
Please start a discussion on the mailing list.
