### ISSUE TITLE
`test_multipleDelayedCalls` fails on openSUSE Tumbleweed aarch64

### ISSUE THREAD

**Issue by ggardet** [twisted/twisted#11882]
**Describe the incorrect behavior you saw**
`test_multipleDelayedCalls` fails on openSUSE Tumbleweed aarch64

**Describe how to cause this behavior**
Build and run test suite on openSUSE Tumbleweed aarch64

Error log:
```
[  451s] [ERROR]
[  451s] Traceback (most recent call last):
[  451s]   File "/usr/lib/python3.9/site-packages/twisted/internet/test/test_posixbase.py", line 55, in tearDown
[  451s]     self.assertEqual(
[  451s]   File "/usr/lib/python3.9/site-packages/twisted/trial/_synctest.py", line 441, in assertEqual
[  451s]     super().assertEqual(first, second, msg)
[  451s]   File "/usr/lib64/python3.9/unittest/case.py", line 837, in assertEqual
[  451s]     assertion_func(first, second, msg=msg)
[  451s]   File "/usr/lib64/python3.9/unittest/case.py", line 830, in _baseAssertEqual
[  451s]     raise self.failureException(msg)
[  451s] twisted.trial.unittest.FailTest: 5 != 0 : Warnings found at the end of the test:
[  451s] [{'message': 'unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>', 'category': <class 'ResourceWarning'>, 'filename': '/usr/lib64/python3.9/asyncio/base_events.py', 'lineno': 686}, {'message': 'unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>', 'category': <class 'ResourceWarning'>, 'filename': '/usr/lib64/python3.9/asyncio/base_events.py', 'lineno': 686}, {'message': 'unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>', 'category': <class 'ResourceWarning'>, 'filename': '/usr/lib64/python3.9/asyncio/base_events.py', 'lineno': 686}, {'message': 'unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>', 'category': <class 'ResourceWarning'>, 'filename': '/usr/lib64/python3.9/asyncio/base_events.py', 'lineno': 686}, {'message': 'unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>', 'category': <class 'ResourceWarning'>, 'filename': '/usr/lib64/python3.9/asyncio/base_events.py', 'lineno': 686}]
[  451s] 
[  451s] twisted.internet.test.test_posixbase.IterationTimeoutTests.test_multipleDelayedCalls
```

**Describe the correct behavior you'd like to see**
Test should pass.

**Testing environment**
 - Operating System and Version: openSUSE Tumbleweed aarch64
 - Twisted version: 22.10.0

**Additional context**
N/A

**Comment by adiroiban** [comment]
Thanks for the report.
Right now openSUSE Tumbleweed aarch64 is not an supported environment.

We only support the environmnets for which we run GitHub Actions tests.

I think that by using docker, we can run tests with Linux on ARM64.

So the first step would be to add a test run for Linux or openSUSE Tumbleweed  with `--platform linux/arm64`

Let me know if you are still interested in having this bug fixed and we can work to get this done.

**Comment by ggardet** [comment]
Current package in openSUSE Tumbleweed build fine and passes all tests. 
But that would be interesting to get arm64 tests to be future proof.

**Comment by glyph** [comment]
@ggardet fwiw, no need to close this — we'd be happy to address this (and I've even got an aarch64 computer personally) but figuring out how to add it to CI is step 1
