### ISSUE TITLE
asyncio.get_running_loop() throws a RuntimeError

### ISSUE THREAD

**Issue by systocrat** [twisted/twisted#11896]
**Describe the incorrect behavior you saw**
When calling get_running_loop upon reactor start (through run() or twisted.task.react), asyncio throws a runtime error stating that there isn't an event loop running.

**Describe how to cause this behavior**

Here's a gist demonstrating this.

https://gist.github.com/systocrat/e2ba109c6de392d51c4323c7a841a39f

**Describe the correct behavior you'd like to see**

I'd assume this probably shouldn't fail as long as the Twisted reactor is running and the asyncio reactor is installed? But if there's something I'm doing wrong I'd love to know.

**Testing environment**
`Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux`
Debian Bullseye

I tried running this example on CPython 3.11.3, 3.10.1, 3.9.16, 3.8.14 and none worked.

**Comment by glyph** [comment]
Thanks for the detailed bug report!
