### ISSUE TITLE
twisted.internet.test.test_endpoints.WrapClientTLSParserTests.test_tls fails

### ISSUE THREAD

**Issue by exarkun** [twisted/twisted#11892]
```
[FAIL]
Traceback (most recent call last):
  File "/nix/store/z26m0k7lr3v5qaqx5yc75z7gzxyak7xl-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/internet/test/test_endpoints.py", line 4280, in test_tls
    self.assertFalse(plainClient.transport.disconnecting)
  File "/nix/store/z26m0k7lr3v5qaqx5yc75z7gzxyak7xl-python3.10-twisted-22.10.0/lib/python3.10/site-packages/twisted/trial/_synctest.py", line 386, in assertFalse
    super().assertFalse(condition, msg)
  File "/nix/store/5a457g4zr7q11b4mz0ifc9z88kwcp8g7-python3-3.10.12/lib/python3.10/unittest/case.py", line 681, in assertFalse
    raise self.failureException(msg)
twisted.trial.unittest.FailTest: True is not false

twisted.internet.test.test_endpoints.WrapClientTLSParserTests.test_tls
```

**Describe how to cause this behavior**

```
nix build github:exarkun/tahoe-lafs?ref=reproducer-for-twisted
```

**Testing environment**

NixOS 22.11.4147

**Comment by glyph** [comment]
I'm sorry that this traceback wasn't properly included in the issue that reported it, so you probably couldn't find it while reporting on this.  This is a duplicate of https://github.com/twisted/twisted/issues/11877 .

Should we make NixOS a supported platform?  I am not the biggest fan, but y'all are obviously pretty significant users and it would be good if something in CI validated this

**Comment by adiroiban** [comment]
I think since JP has already create some "recipes" for NixOS, we can have that code in Twisted and run then via a docker test.


I am happy to review or work together with JP to get this merge.

For reference, the nixos code for Twisted is at https://github.com/exarkun/tahoe-lafs/tree/reproducer-for-twisted

**Comment by exarkun** [comment]
> I think since JP has already create some "recipes" for NixOS, we can have that code in Twisted and run then via a docker test.
> 
> I am happy to review or work together with JP to get this merge.
> 
> For reference, the nixos code for Twisted is at https://github.com/exarkun/tahoe-lafs/tree/reproducer-for-twisted

That code is a bit more than you need for Twisted in NixOS in general - it includes some package upgrades that demonstrate the Twisted / service-identity incompatibility which is specific to just this issue.

**Comment by adiroiban** [comment]
Do we need to build on nixOS to reproduce these tests or it's enough to run Twisted inside nix on ubuntu 22.04 ?

**Comment by exarkun** [comment]
Since this ticket really isn't related to NixOS, maybe it would be better to continue discussion on a new ticket that is directly about to some kind of Nix-related support.
