### ISSUE TITLE
Where are the examples from:  https://docs.twisted.org/en/stable/core/examples/index.html in twisted github?

### ISSUE THREAD

**Issue by coderextreme** [twisted/twisted#11906]
This is a feature request on making examples from https://docs.twisted.org/en/stable/core/examples/index.html available on something besides a web browser (my browser, Edge, frowns at .py extensions...don't laugh).

I will look under the twisted organization.

**Comment by coderextreme** [comment]
I looked here:  https://github.com/twisted/twisted.github.io

I'm looking for things like:

https://docs.twisted.org/en/stable/_downloads/9fe9af011ef010816107fb635bc15d71/simpleclient.py

Something that my web browser isn't going to flag, and I'd like to download more than one example at time.

https://docs.twisted.org/en/stable/_downloads/9fe9af011ef010816107fb635bc15d71/simpleclient.py

Thanks!

**Comment by adiroiban** [comment]
I am not sure what needs to be done here

The example source files are at https://github.com/twisted/twisted/tree/trunk/docs/core/examples

this is the first file suggested by github search https://github.com/search?q=repo%3Atwisted%2Ftwisted%20simpleclient.py&type=code

**Comment by coderextreme** [comment]
I guess my `find` command didn't work.  I must have fumble fingered it, or my eyes were crossed.  While I have you here, do you have a streaming client example?  I'd like to use it on my local system. I will try a server in python.  The other end will be Java.  I'm not doing more than one client and one server right now.  It's easier if Python contact my multi-user server, which already works very well, so I'd like a streaming client, if possible.

**Comment by coderextreme** [comment]
Here's my use case, in case you're wondering.  I'm using MediaPipe Holistic to capture hand motion in video, which will hopefully be Protactile sign language (but think mocap--motion capture, I'm not sending the video over the network, just "bones"--line segments, and "joint" locations). I want something simple (a client) that I can shovel data to a server in a Java. I don't want to bog python down with a server as well, and that will make the code more complex, the code is already doing object detection, but if it gets around any problems with my system, I may try it.

If this somehow "breaks" twisted or python, please let me know. I realize already that a streaming client would be good for a DOS attack.  I'm not doing that.   I've already sent 1000000 random numbers from server to client, so that's a fallback.

I'm seeing systems like Faust and Kafka, if you want to send me in that direction.    I've tried way too many attempted solutions with standard sockets in python, but I didn't try asyncio yet, which seems to be python's streaming solution. They have some streaming server  examples at the end of this page:  https://docs.python.org/3/library/asyncio-stream.html but I don't see streaming client.

**Comment by coderextreme** [comment]
I was able to construct a Twisted python client using ChatGPT/Shell-GPT.  Whew!  I have a Python asyncio server, that's confusing.  I guess I'll try ChatGPT for the Twisted server as well.  It worked about as well as the asyncio server, with some garbling of output with 1000000 messages sent from client, like this:

Message 999185
Me
Received data: ssage 999186
Message 999187

That could be a windows or python problem unrelated to networking.  I will close the issue!

Thanks!
