### ISSUE TITLE
Python 3.12: Deprecated utcnow and utcfromtimestamp

### ISSUE THREAD

**Issue by pmisik** [twisted/twisted#11908]
**Describe the incorrect behavior you saw**
`datetime.datetime.utcnow` and `datetime.datetime.utcfromtimestamp` raise deprecation warnings in Python 3.12.

**Describe how to cause this behavior**

While running trial on buildbot this generates lots of deprecation warnings like:
```
Traceback (most recent call last):
  File "C:\P\twisted\src\twisted\logger\_observer.py", line 81, in __call__
    observer(event)
  File "C:\P\twisted\src\twisted\logger\_legacy.py", line 90, in __call__
    self.legacyObserver(event)
  File "C:\P\twisted\src\twisted\python\log.py", line 544, in emit
    timeStr = self.formatTime(eventDict["time"])
  File "C:\P\twisted\src\twisted\python\log.py", line 514, in formatTime
    tzOffset = -self.getTimezoneOffset(when)
  File "C:\P\twisted\src\twisted\python\log.py", line 493, in getTimezoneOffset
    offset = datetime.utcfromtimestamp(when) - datetime.fromtimestamp(when)
builtins.DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.fromtimestamp(timestamp, datetime.UTC).
E           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Running buildbot trial with current HEAD & current trunk of twisted.

**Describe the correct behavior you'd like to see**
No deprecation warning reported while running trial under python 3.12.

**Testing environment**
 - Operating System and Version; paste the output of these commands:
```
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Microsoft Corporation
BIOS Version:              Microsoft Corporation 15.11.140, 8. 7. 2022
```
 - Twisted version
   22.10.0.post0
   https://github.com/twisted/twisted/commit/a9ee8e59a5cd1950bf1a18c4b6ca813e5f56ad08
 - Reactor [e.g. select, iocp]
  `twisted-iocpsupport           1.0.4`

**Additional context**
 - Deprecate utcnow and utcfromtimestamp python/cpython#103857
 - https://blog.ganssle.io/articles/2019/11/utcnow.html

**Comment by adiroiban** [comment]
Thanks for the report.

Happy to receive a PR with a fix for this :)

**Comment by adiroiban** [comment]
@pmisik not that until just now, twisted/twisted was not working/supported on 3.12

You can now try to install Twisted over git and see if this is still an issue. Thanks!
