### ISSUE TITLE
Sometime reactor.callLater getting missed and never runs, if added from methods run under threads.

### ISSUE THREAD

**Issue by LalitTarsariya** [twisted/twisted#11901]
**Describe the incorrect behavior you saw**
A program which running multiple jobs in thread and adding callLater, some of the callLater never getting execute.

**Describe how to cause this behavior**

Below is the sample code which can reproduce the issue every time, adding 1000 callLater from 10 different threads and out of 1000 near 970 getting execute.

```
job_done = 0

def delayed_job():
    global job_done
    job_done += 1
    print(job_done)

def main():
    lp_call = task.LoopingCall(lambda: None)
    lp_call.start(0.001)
    for i in range(10):
        threads.deferToThread(thread_job)

def thread_job():
    for i in range(100):
        time.sleep(random() / 200)
        reactor.callLater(0.0001, delayed_job)

if __name__ == '__main__':
    reactor.callLater(1, main)
    reactor.run()
```

```
971
972
973
974
975
[lalitkumar : scripts]$ 
```

**Describe the correct behavior you'd like to see**
Every callLater which added from threads or from main thread should execute.

**Testing environment**
 - Operating System and Version; paste the output of these commands:
   - DISTRIB_ID=Ubuntu
   - DISTRIB_RELEASE=22.04
   - DISTRIB_CODENAME=jammy
   - DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
 - Python 2.7.18
 - Twisted==20.3.0
 - Reactor: EPollReactor

**Additional context**
callLater missing while moving from _newTimedCalls to _pendingTimedCalls in _insertNewDelayedCalls method in ReactorBase class.

```
def _insertNewDelayedCalls(self):
    for call in self._newTimedCalls:
        if call.cancelled:
            self._cancellations-=1
        else:
            call.activate_delay()
            heappush(self._pendingTimedCalls, call)
    self._newTimedCalls = []
```

Because of multiple thread running parallel the callLater may get added in _newTimedCalls after the loop ends and before the _newTimedCalls initiate with empty list will get missed.
Changing code to below is solving problem most of the cases, but still sometime missing the 1 or 2 callLater.

```
def _insertNewDelayedCalls(self):
    new_callLaters = self._newTimedCalls
    self._newTimedCalls = []
    for call in new_callLaters:
        if call.cancelled:
            self._cancellations-=1
        else:
            call.activate_delay()
            heappush(self._pendingTimedCalls, call)
```

Need to have some better solution, may be converting the _newTimedCalls to set and using the pop method can may solve the problem.

**Comment by adiroiban** [comment]
> Every callLater which added from threads ...

I don't think that this should be the expected behaviour.

From the main thread, yes.
From other "custom" threads, no.


-----------

I think that `reactor.callLater(0.0001, delayed_job)` should only be called from the main (control) thread.

As a general rule, if you are doing work in a thread, that work should be independent from the main non-blocking work done in the main reactor thread.

If you are already in a thread, I guess that you can just call `sleep()` , or something similar.

**Comment by adiroiban** [comment]
The main thread handling documentation for Twisted is here https://docs.twisted.org/en/stable/core/howto/threading.html

Is there anywhere in that documentation suggesting that callLater and other non-threading functions are thread-safe ?

The docs contains

> Methods within Twisted may only be invoked from the reactor thread unless otherwise noted. Very few things within Twisted are thread-safe.

-------

I am closing this as wont fix for now.

We might need to fix the documentation, but I don't think that it is expected for callLater to work outside of the reactor thread.
