### ISSUE TITLE
python.failure.Failure doesn't save frames properly

### ISSUE THREAD

**Issue by ghost** [twisted/twisted#11900]
**Describe the incorrect behavior you saw**
`Failure.__init__` doesn't properly saved frames.
The only part in `__init__` which sets `self.frames` and `self.stack` is:
https://github.com/twisted/twisted/blob/a9ee8e59a5cd1950bf1a18c4b6ca813e5f56ad08/src/twisted/python/failure.py#L338-L339
Below, although `frames` and `stacks` modified, them doesn't write to `self.frames` and `self.stacks`. So `self.frames` and `self.stacks` keeps empty.
_______
Another one:
https://github.com/twisted/twisted/blob/a9ee8e59a5cd1950bf1a18c4b6ca813e5f56ad08/src/twisted/python/failure.py#L313-L339
`__init__` function end by return before initialize `self.frames` and `self.stack`, so `self._extrapolate` won't work.

**Describe how to cause this behavior**
Normally instance a Failure.

**Describe the correct behavior you'd like to see**
Set them correctly.

**Testing environment**
 - Operating System and Version
```
Linux iZuf67dod2jl91zl0x9rnaZ 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
```
 - Twisted version 22.10.0
 - Reactor select

**Additional context**
[Possible fix](https://pastebin.com/VTtZTye0)

**Comment by adiroiban** [comment]
thanks for the report

for reference, the content from paste bin 

```diff
diff --git a/src/twisted/python/failure.py b/src/twisted/python/failure.py
index 23ab24fc8..395a5d5fe 100644
--- a/src/twisted/python/failure.py
+++ b/src/twisted/python/failure.py
@@ -310,6 +310,9 @@ class Failure(BaseException):
             self.type = exc_type
             self.value = exc_value
 
+        frames = self.frames = []
+        stack = self.stack = []
+
         if isinstance(self.value, Failure):
             self._extrapolate(self.value)
             return
@@ -335,9 +338,6 @@ class Failure(BaseException):
                 # Python 3
                 tb = self.value.__traceback__
 
-        frames = self.frames = []
-        stack = self.stack = []
-
         # Added 2003-06-23 by Chris Armstrong. Yes, I actually have a
         # use case where I need this traceback object, and I've made
         # sure that it'll be cleaned up.
@@ -422,6 +422,9 @@ class Failure(BaseException):
         else:
             self.parents = [self.type]
 
+        self.frames = frames
+        self.stack = stack
+
     def _extrapolate(self, otherFailure):
         """
         Extrapolate from one failure into another, copying its stack frames.
 
```

**Comment by exarkun** [comment]
The lists are mutated in-place.  The instance attributes refer to the same lists so the information ends up reachable from the instance.

**Comment by ghost** [comment]
> The lists are mutated in-place. The instance attributes refer to the same lists so the information ends up reachable from the instance.

Sorry :)
But what about the second one?

**Comment by exarkun** [comment]
> > The lists are mutated in-place. The instance attributes refer to the same lists so the information ends up reachable from the instance.
> 
> Sorry :) But what about the second one?

What is "the second one"?

**Comment by ghost** [comment]
Nothing... Maybe I read allthing wrong
