### ISSUE TITLE
drop support for eol python 3.7

### ISSUE THREAD

**Issue by graingert** [twisted/twisted#11913]
**Is your feature request related to a problem? Please describe.**
3.7 is eol we should no longer support it

**Describe the solution you'd like**
drop support for 3.7

**Comment by adiroiban** [comment]
We can have this done after 2023.08 release

I am not sure what is the scope of this ticket.

Is the purpose of this ticket to do a purge or run pyupgrade 38+  ?

Or it's just to make the announcement?
I think the announcement can be done as part for the release work

**Comment by graingert** [comment]
@adiroiban pyupgrade got removed in 380696ecea3fe63dc5da194a4124186a56005d59

**Comment by graingert** [comment]
@adiroiban the scope is to remove _PY37PLUS, update the trove classifiers and requires-python and other config files, always import contextvars because it's always available

**Comment by adiroiban** [comment]
> @adiroiban pyupgrade got removed in https://github.com/twisted/twisted/commit/380696ecea3fe63dc5da194a4124186a56005d59

Well, pyupgrade was removed from automated pre-commit CI.
But we can continue to use it with manual PRs and manual reviews.
