### ISSUE TITLE
reactor.connectSSL doesn't connect right for all kinds of was backend

### ISSUE THREAD

**Issue by Pborz** [twisted/twisted#11928]
There are 2 wss:

1. "wss://wspap.okex.com:8443/ws/v5/public?brokerId=9999"
2. "wss://wspap.okx.com:8443/ws/v5/public?brokerId=9999"

**Describe the incorrect behavior you saw**
reactor.connectSSL can connect right 1 but has error in 2

**Describe how to cause this behavior**

Compared with `pip install websockets`
`websockets` connects well with both 1 and 2
but reactor.connectSSL only 1
it is unusual because wss should all be connected well.  it is also a chance for Twisted team to have a simple check between 
1. "wss://wspap.okex.com:8443/ws/v5/public?brokerId=9999"
2. "wss://wspap.okx.com:8443/ws/v5/public?brokerId=9999"

because someone pointed out that not so clearly, that some port-like issue maybe cause difference between `websockets` and `Twisted reactor connectSSL` 
really thankful for all the team to communicate with me  

```
WsClientFactory execute clientConnectionLost. Reason: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly.
],retried 1 times
```

.......

p.s:   a package called `autobahn` made a so-called `from autobahn.twisted.websocket import connectWS`
using 
 ```
@public
def connectWS(factory, contextFactory=None, timeout=30, bindAddress=None):
.......

    if factory.proxy is not None:
        factory.contextFactory = contextFactory
        conn = reactor.connectTCP(factory.proxy['host'], factory.proxy['port'], factory, timeout, bindAddress)
    else:
        if factory.isSecure:
            conn = reactor.connectSSL(factory.host, factory.port, factory, contextFactory, timeout, bindAddress)
        else:
            conn = reactor.connectTCP(factory.host, factory.port, factory, timeout, bindAddress)
    return conn
```

so really thankful for all the team to communicate with me  if this `autobahn` is designed in the wrong way

**Comment by Pborz** [comment]
@oberstet  truly sorry, Mr. Oberstet. It might be necessary to inform you briefly here, and I apologize for any disruption. I am currently in communication with the Twisted team regarding some rather significant issues with `connectSSL`. This is because a widely-used library in the market named `websockets` is functioning properly.

**Comment by oberstet** [comment]
> It might be necessary to inform you briefly here

why do you think so?

> This is because a widely-used library in the market named websockets is functioning properly.

well, I don't care? I am author of Autobahn, not above library ...

**Comment by oberstet** [comment]
just one comment rgd `connecWs`: this is stone age old code, only used in the beginnings of websocket (2012), and a better way is using better/newer Twisted APIs - which Autobahn contains in that same file: Twisted Endpoints, Services/Agents ..

**Comment by glyph** [comment]
> @oberstet truly sorry, Mr. Oberstet. It might be necessary to inform you briefly here, and I apologize for any disruption. I am currently in communication with the Twisted team regarding some rather significant issues with `connectSSL`. This is because a widely-used library in the market named `websockets` is functioning properly.

The solution here is to stop using `connectSSL`; you should be using `HostnameEndpoint`.

If there's something to be fixed in Twisted here, it's to deprecate `connectSSL` and remove it entirely.

We may want to add some kind of reactor-level API, or at least something more contextually pluggable when we add multiple TLS backends, but it would not look like `connectSSL`.

Right now with only OpenSSL supported on top of regular sockets, this is the interface you should be using:

https://docs.twistedmatrix.com/en/stable/api/twisted.internet.endpoints.HostnameEndpoint.html

**Comment by Pborz** [comment]
> > @oberstet truly sorry, Mr. Oberstet. It might be necessary to inform you briefly here, and I apologize for any disruption. I am currently in communication with the Twisted team regarding some rather significant issues with `connectSSL`. This is because a widely-used library in the market named `websockets` is functioning properly.
> 
> The solution here is to stop using `connectSSL`; you should be using `HostnameEndpoint`.
> 
> If there's something to be fixed in Twisted here, it's to deprecate `connectSSL` and remove it entirely.
> 
> We may want to add some kind of reactor-level API, or at least something more contextually pluggable when we add multiple TLS backends, but it would not look like `connectSSL`.
> 
> Right now with only OpenSSL supported on top of regular sockets, this is the interface you should be using:
> 
> https://docs.twistedmatrix.com/en/stable/api/twisted.internet.endpoints.HostnameEndpoint.html

sorry seems that `HostnameEndpoint` doesn't return a IConnector and even thought return it just within connectTCP,
is there anything really capable to replace this structure ?:

old:
```
conn = reactor.connectSSL(factory.host, factory.port, factory, contextFactory, timeout, bindAddress)
```

want:

```
(some IConnector) =(some endpoint).(some SSL connect) (factory)
return (some IConnector) 
```

really thx

**Comment by glyph** [comment]
Nope, `IConnector` is not a great interface and that's one reason why `connectSSL` is discouraged.

I'm sorry if we haven't been proactively communicating this well enough, but `wrapClientTLS` was added in 2016, so there has been a *lot* of time to adopt this API.

**Comment by glyph** [comment]
If you're looking for an `IConnector` because you are using `ReconnectingClientFactory` and you just need to maintain a persistent outgoing connection, have a look at https://docs.twistedmatrix.com/en/stable/api/twisted.application.internet.ClientService.html

**Comment by oberstet** [comment]
maybe any `connectSSL` use (and consequently autobahn's `connectWs`) should also simply be removed from autobahn as well. it's been there since it was a thing I guess 10 years ago when I started autobahn. maybe there was sth newer even at that time already. but in any case, +1 for pointing to `ClientService` which works nicely, has a lot of knobs and is used in autobahn of course, so the modern variant of what the OP talks about corresponds to this https://github.com/crossbario/autobahn-python/blob/359f868f9db410586cf01c071220994d8d7f165a/autobahn/twisted/wamp.py#L332

**Comment by Pborz** [comment]
> maybe `connectSSL` should also simply be removed from autobahn as well. it's been there since it was a thing I guess 10 years ago when I started autobahn. maybe there was sth newer even at that time already. but in any case, +1 for pointing to `ClientService` which works nicely, has a lot of knobs and is used in autobahn of course, so the modern variant of what the OP talks about corresponds to this https://github.com/crossbario/autobahn-python/blob/359f868f9db410586cf01c071220994d8d7f165a/autobahn/twisted/wamp.py#L332

really thx for autobahn long term contributions.
I'm currently stuck in some concept new and old, cuz it've been afk several years.
last period my connectSSL return an IConnector and got the callback well.
now I've tried to start with endpoint but, with the origin `WebSocketClientFactory` and `WebSocketClientProtocol` seems that not capable to easy-move to.
really thx for advice about how to make up a was by interface above and capable the callback and protocol easily THXXXX

**Comment by Pborz** [comment]
@okxapi
my friend's wss is still working on this issue, let me introduce for him little.
maybe helpful for us to upgrade the reactor.connectSSL most easily.
THX everyone.
