### ISSUE TITLE
License for the latest version (23.8.0) has not been added in PyPI

### ISSUE THREAD

**Issue by fmavb** [twisted/twisted#12005]
License for the latest version (23.8.0) has not been added in PyPI. Could you please add it, thanks.
https://pypi.org/project/Twisted/

**Comment by adiroiban** [comment]
thanks for the report. I think this is low priority.
There is the licence info in the README.

I now also see that there is not much LICENCE info on https://docs.twisted.org/

So maybe we can also add a note about the licence on the first page of the docs

Do you have any hints about how to add the licence info to PyPI ?

Thanks

**Comment by graingert** [comment]
the license is set here: https://github.com/twisted/twisted/blob/3f34c2894d34a7879aeb23ef5467e4b1a199fb07/pyproject.toml#L18

**Comment by graingert** [comment]
looks like we should be using `license = {text = "MIT License"}`

https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#license

**Comment by adiroiban** [comment]
Thanks Thomas for the info.

@fmavb would you have time to create a PR and update the licence definition in Twisted?

Thanks

**Comment by fmavb** [comment]
Sure I have the change ready to push

**Comment by fmavb** [comment]
https://github.com/twisted/twisted/pull/12010 - PR is raised
