### ISSUE TITLE
Read The Docs documentation website search not working

### ISSUE THREAD

**Issue by adiroiban** [twisted/twisted#12012]
You can test this link

https://docs.twisted.org/en/twisted-23.8.0/search.html?q=threads&check_keywords=yes&area=default#

it looks like jquery is not included

**Comment by glyph** [comment]
It looks like this is still an issue on 23.8, but not on `latest` or `stable`

**Comment by adiroiban** [comment]
This was [fixed in 23.10](https://github.com/twisted/twisted/blob/HEAD/NEWS.rst#twisted-23100-2023-10-31)


We don't re-generate and re-publish the documentation for older versions.
