### ISSUE TITLE
Performance issue in TLS: assert that each written chunk of a data is not a str

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12011]
This check is in the hot path, and can slow down writing when there are lots of small writes: https://github.com/twisted/twisted/blob/88172f74de390f148ec2a44829090718cdfd43c5/src/twisted/protocols/tls.py#L452

Fixing it will be done as followup to #11989

**Comment by itamarst** [comment]
I did some testing with latest code. On Python 3.11 there's no meaningful difference in performance; that is, there may be an impact, but it's overwhelmed by noise, so presumably not particularly significant. On Python 3.10 it's a small improvement. Insofar as this does make debugging easier, and insofar as there's no reason for people not to upgrade to Python 3.11 or later in general, this is probably unnecessary.

**Comment by adiroiban** [comment]
Thanks for the follow up.
Happy to hear there is no significant performance impact.

**Comment by itamarst** [comment]
I did some more benchmarking and decided I was wrong, there is actually a meaningful performance impact. So I will submit a PR.
