### ISSUE TITLE
twisted uses deprecated three-argument form of generator.throw

### ISSUE THREAD

**Issue by AdamWill** [twisted/twisted#12026]
**Describe the incorrect behavior you saw**
`src/twisted/python/failure.py` does `return g.throw(self.type, self.value, self.tb)`. This is deprecated in Python 3.12: https://github.com/python/cpython/issues/96348 , https://docs.python.org/3.12/whatsnew/3.12.html#deprecated . This is a particular problem for https://github.com/fedora-infra/fedora-messaging consumers - they print a deprecation warning about once a second.

**Describe how to cause this behavior**
Try using twisted with Python 3.12, in a way that hits this codepath (I'm not sure precisely how to do that other than "use a fedora-messaging consumer", sorry). You get a deprecation warning:

```
Oct 27 23:11:08 openqa-lab01.iad2.fedoraproject.org fedora-messaging[172628]: /usr/lib/python3.12/site-packages/twisted/python/failure.py:518: DeprecationWarning: the (type, exc, tb) signature of throw() is deprecated, use the single-arg signature instead.
Oct 27 23:11:08 openqa-lab01.iad2.fedoraproject.org fedora-messaging[172628]:   return g.throw(self.type, self.value, self.tb)
```

**Describe the correct behavior you'd like to see**
No deprecation warning.

**Testing environment**
Python 3.12 on Fedora 39, don't think anything else is relevant. The code is still using the deprecated form on current git trunk.

**Additional context**
I would send a pull request changing this, but I'm unclear on [whether it's safe to just use the modern one-argument form on Python 3.8](https://github.com/python/cpython/issues/96348#issuecomment-1783626480).

**Comment by glyph** [comment]
> I would send a pull request changing this, but I'm unclear on [whether it's safe to just use the modern one-argument form on Python 3.8](https://github.com/python/cpython/issues/96348#issuecomment-1783626480).

Would it be possible to prepare two PRs, one which does the one-argument form, and one which suppresses the deprecation so we don't get the log spam until we can drop 3.8?  It would be nice to get it churning through CI in the meanwhile so we can land it quickly, whichever approach works.  (And if it's not actually safe on 3.8, presumably CI will tell us fairly loudly)

**Comment by AdamWill** [comment]
well, possibly CI wouldn't catch it - even with the three-argument form, the last two arguments are optional, so it's not just flat-out *invalid* to pass it only one argument on 3.8.

It's just that, at least as documented, if you pass it one argument on 3.8, it expects that argument to be an exception type, not an instance. Presumably, whenever the one-argument-that's-an-instance signature was actually introduced, it was set up so that if you pass it one argument it checks whether it's a type or an instance and behaves appropriately.

But at least as documented, doing `generator.throw(exception_instance)` on 3.8 is *syntactically* valid but the actual consequences of doing it are unclear...I guess it would depend what those consequences are, and whether the tests are sophisticated enough to catch it if the consequences are wrong?

It's a bit late here now, so I think I'll maybe see if we get any comments on my questions in https://github.com/python/cpython/issues/96348 today or tomorrow...

**Comment by AdamWill** [comment]
well, I guess sending the PRs can't hurt, so there they are.

**Comment by glyph** [comment]
Thanks, much appreciated!
