### ISSUE TITLE
twisted-iocpsupport: release including linux binaries

### ISSUE THREAD

**Issue by abij** [twisted/twisted#12020]
Currently there are Windows-only binaries: https://pypi.org/project/twisted-iocpsupport/#files

Can you update the [workflow](https://github.com/twisted/twisted-iocpsupport/blob/default/.github/workflows/github-deploy.yml) and add Linux binaries, like has been done for windows using `cibuildwheel`?

This would be great!

**Comment by exarkun** [comment]
twisted-iocpsupport is a Windows-only project.  It binds Windows APIs for the IOCP reactor.  It is never used on Linux.
