### ISSUE TITLE
Does Twisted Python have any runtime issues on MacOS?

### ISSUE THREAD

**Issue by MacDaddy1660B** [twisted/twisted#12051]
Hi everybody,

This is a broad question, and not really a bug report. I have an application that uses Twisted to handle socket communications over a network. I've run it on Linux and Windows, but for some reason this application doesn't work on MacOS.

The TCP4ClientEndpoint connects successfully, and some data come through, but then the Twisted backend seems to hang, the CPU usage goes way high, and acts like it's stuck in an infinite loop and I'm unable to send or receive data over my connection. The rest of the application, GUI, and all that, seem to continue functioning normally. 

If I switch my socket communications to a different framework, all is good. So the issue is with Twisted, or how it's implemented in my application.

I don't see a stack trace or any errors anywhere.

Is there a good way to turn on verbose debugging somewhere? How might I start tackling this? Really I'm just asking for ideas here. Thanks for any help!

I'm using:
- Python 3.11.7
- Twisted 23.10.0
- MacOS v13 (Ventura)

**Comment by glyph** [comment]
In a word, "no", but this is an interesting bug report because macOS is my primary development platform and I do use Twisted a fair amount :).

Do you have a reproducible example you can share?

**Comment by MacDaddy1660B** [comment]
I do have a reproducible example, which is the application itself. I'm unable to scale-down our application and also reproduce the hanging issue, which makes me think the problem might be somewhere else in our application. I really just needed a place to ask the broad question if Twisted plays nicely with MacOS as it does with Linux, for example. Thanks for your fast response @glyph !

**Comment by MacDaddy1660B** [comment]
By the way, this is a GUI application that uses tkinter as below. The tk instance is installed into the reactor. Does that change anything with regards to my question above? Thanks.
```
root=tkinter.Tk()
import twisted.internet.tksupport
twisted.internet.tksupport.install(root)
import twisted.internet
reactor = twisted.internet.reactor
reactor.run()
```

**Comment by MacDaddy1660B** [comment]
OK, so I tried running my application using a Python v3.8.8 build for Intel 64, MacOS and my issues seem to have been resolved.
My machine has an intel chip.

Does twisted play OK with the MacOS universal2 builds?

**Comment by glyph** [comment]
> Does twisted play OK with the MacOS universal2 builds?

Yep, Twisted is pure-python and all its binary dependencies ought to be universal2-friendly

**Comment by MacDaddy1660B** [comment]
OK, so I believe this is likely an issue with TclTk on Mac. Thank you for your help @glyph .

**Comment by glyph** [comment]
> OK, so I believe this is likely an issue with TclTk on Mac. Thank you for your help @glyph .

It's quite possible that we have a bug in our `tksupport` module; it's hard to have automated tests that make sure it works, so something may have broken.  If you can reproduce this with a minimal code example, please feel free to open a more specific bug report.
