### ISSUE TITLE
Make Failure and (to the extent possible) its exception immutable

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12111]
### Background

`Failure` is used in two use cases:

1. As a wrapper for an _unexpected_ exception, with potentially unlimited exception types. Either some internal state or some external input is unexpected. In these situations the traceback can be helpful for debugging.
2. As a wrapper for a _fixed_, limited set of expected situations. For example, an HTTP body can end in 3 states: finished successfully, not all data received, and no way to know (HTTP/1.0 only if memory serves). If Twisted were written today these cases might well be handled by a simple `Enum`, rather than a wrapper around an exception.

This issue focuses only on the second case.

### Motivation

Given a fixed set of values in a `Failure`, and the fact that a `Failure` might be created per event, the fact that `Failure` is expensive to create is a performance bottleneck. For example, every HTTP response involves creating a `Failure`.

One solution is to change the API so it doesn't take a `Failure`. This is a pretty significant change, and backwards compat would in practice mean few people would benefit from the performance improvement.

Another is to reuse a single `Failure`. You don't really need more than one `Failure` for a `ResponseDone`, you can just reuse it. This works fine... unless someone is relying on mutating `Failure` objects, or their contained `Exception`.

By making `Failure` and (to the extent possible) its exception immutable, we can reuse the same cached `Failure` object and get a big performance boost in some cases without changing the API significantly.

### How to implement

There are different options for enforcing immutability, focusing on `Failure`.

There are multiple ways of doing this at runtime:

* **RUNTIME-ALL:** The `Failure` class is modified so `__setattr__` and friends don't really work. This impacts all usage of `Failure`, and is enforced at runtime.
* **RUNTIME-OPTIONAL:** Add a flag to `Failure` that allows turning on this behavior.
* **RUNTIME-NONE:** No enforcement is done at runtime. This means either **TYPE-CHECK-ALL** or **TYPE-CHECK-OPTIONAL** below need to be chosen.

And multiple ways of doing this via type checking:

* **TYPE-CHECK-ALL:** The `Failure` class type annotations are marked with [`typing.Final`](https://mypy.readthedocs.io/en/stable/final_attrs.html) such that they can't be changed.
* **TYPE-CHECK-OPTIONAL**: A `typing.Protocol` is defined that makes a `Failure` read-only for type-checking purposes. A new method `freeze()` is then added to `Failure` that just return `self` as a `FrozenFailure`.
* **TYPE-CHECKING-NONE:** No read-only enforcement for type checking. This option is not worth pursuing.

Additionally, for cases where immutability is definitely desirable, the corresponding exception classes (semantically similar `Enum` variants) would need to be marked as immutable with some combination of the equivalent of the above, probably the **-ALL** variants.

### Backwards compatibility concerns

Unfortunately Python has no way to mark things as immutable, so whether mutation is acceptable is governed by (usually unwritten) convention and user assumptions. Twisted already has cases where exceptions are assumed to be immutable, given the existence of `CONNECTION_LOST` and `CONNECTION_DONE` global instances of the corresponding exception classes.

I have found one case in the Twisted codebase with quick grepping of mutating a `Failure` directly, in Trial, but that should be implementable some other way, and it's not something external users should hopefully rely on.

There is also a `Failure.cleanTraceback()` method that explicitly mutates the `Failure` and wrapped exception.

**Comment by exarkun** [comment]
is `cleanFailure` at odds with `TYPE-CHECK-ALL`?  It certainly violates the _spirit_ of a "Final" Failure but I don't know if it violates the letter of the type checking laws.

If it is at odds, or we don't like violating the spirit, but we like TYPE-CHECK-ALL, then I suppose we would deprecate `cleanFailure` and replace it with a version that returns a new `Failure` instead of mutating the existing one in place?  Or does leaving the original Failure "not clean" defeat the purpose?

**Comment by adiroiban** [comment]
I would go for `runtime-all`, as the final goal.

I guess that as a first step, we should raise a deprecation warning if setattr and delete are called... and continue to allow the operation.

-------

For type checking, I think `TYPE-CHECK-ALL - typing.Final` is a good option.

**Comment by glyph** [comment]
Thank you, @itamarst, for this amazingly thorough write-up.

My preference reading this is to begin with `TYPE-CHECK-ALL` / `RUNTIME-OPTIONAL`.

I want to avoid a `freeze` method because this places the onus on the application to make a choice which doesn't strike me as meaningful, and adds API surface that we will then need to manage (and probably deprecate). The reason to have a *generally* mutable `Failure` is really just to avoid backwards-compatibility breakage; I can't think of *use-cases* for mutability.

**Comment by glyph** [comment]
So, for `cleanTraceback` specifically: this is technically mutation, but also, the traceback isn't and cannot be a compatibility surface; it's there to manage a balance between things like debuggers and the performance of the garbage collector.

In the case you describe, the *point* of immutability is:

> we can reuse the same cached Failure object 

presumably a shared, cached Failure object will already have a "cleaned" traceback (i.e.: no traceback) and so this one-way mutability doesn't actually create a problem?

**Comment by itamarst** [comment]
What glyph said is accurate, and in fact I would expect immutable Failures to not have a traceback at all. And mechanically `cleanTraceback()` can be fixed with `# type: ignore` for typechecking.

**Comment by itamarst** [comment]
I think I am going to go with `TYPE-CHECK-ALL`, since really it's a nice constraint to have that these objects are always immutable, for future optimizations. And also `RUNTIME-OPTIONAL` so that if people are doing runtime mutation, they'll get an explicit error rather than silent state corruption, and doing it in optional/opt-in way so as to minimize breakage surface.

**Comment by itamarst** [comment]
Unfortunately I found a place where Twisted sets a random attribute on a random exception inside Failure, https://github.com/twisted/twisted/blob/dabf4622f0ecdd4f0587ae103b23982c4c83bd77/src/twisted/internet/defer.py#L1179

This basically means you cannot re-use exception instances, which means you cannot re-use Failure instances, possibly making this whole issue pointless to implement.

So I will try to figure out a different way to implement this.

**Comment by itamarst** [comment]
More broadly, one can... reraise exceptions, which mutates them :cry:

**Comment by itamarst** [comment]
Starting to think this is fundamentally not realistic given how mutatey Python is.
