### ISSUE TITLE
Verification: Ok even for protocols disabled 

### ISSUE THREAD

**Issue by KaviHarjani** [twisted/twisted#12131]
**Describe the incorrect behavior you saw**

openssl s_client -connect localhost:8443 -tls1
CONNECTED(00000003)
139698017736000:error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:1112:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
**Verification: OK**
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

**Describe how to cause this behavior**
Simply running the server and checking against it

What did you do to get it to happen?
Does it happen every time you follow these steps, sometimes, or only one time?
Everytime

**Describe the correct behavior you'd like to see**
When it fails in Angular or Reat using NPM server, 

The client written bytes are 0 and I don't get verification:ok there

I except to see verification failed or something as such

I am only enabling TLS1.2

```
        context = ssl.DefaultOpenSSLContextFactory(
            certificateFileName='/path/to/cert.pem',
            privateKeyFileName='/path/to/key.pem',
            sslmethod=SSL.TLSv1_2_METHOD,
        )


```

**Testing environment**
 Linux LAPTOP-UQG6V4BJ 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - Twisted version - 24.3.0
 - Reactor [e.g. select, iocp] select

**Comment by adiroiban** [comment]
Hi

Thanks for the report.

Can you please share a complete example for your code using Twisted as HTTPS server?

Have you tried `openssl s_client -tls1_1 ` ? I think that `-tls1` means any V1 of TLS and not only TLS 1.0

**Comment by KaviHarjani** [comment]
Hi @adiroiban 

Thanks for your reply, appreciate it


```
        from twisted.internet import reactor, ssl
        from twisted.web.server import Site
        from twisted.web.wsgi import WSGIResource
        from OpenSSL import SSL
        from django.core.wsgi import get_wsgi_application
        import os

        # Create WSGI resource
        wsgi_resource = WSGIResource(reactor, reactor.getThreadPool(), get_wsgi_application())

        # Create HTTPS context with SSL/TLS rejection settings
        context = ssl.DefaultOpenSSLContextFactory(
              certificateFileName='/path/to/cert.pem',
              privateKeyFileName='/path/to/key.pem',
            sslmethod=SSL.TLSv1_2_METHOD,
        )


        # Create HTTPS server
        site = Site(wsgi_resource)
        reactor.listenSSL(8443, site, context)

        print('Server running')

        # Run the Twisted reactor
        reactor.run()

```



This is my code for using Twisted as HTTPS server


**-tls1_1**

```
~$ openssl s_client -connect localhost:8443 -tls1_1
CONNECTED(00000003)
140211323364672:error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:1112:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
```

**Comment by adiroiban** [comment]
A complete and self containted example  http://www.sscce.org/


Generate the key+cert

```
$ openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj "/CN=localhost"
```

get the python code

```python
from twisted.internet import reactor, ssl
from twisted.web.server import Site
from twisted.web.resource import Resource
from OpenSSL import SSL

# Create HTTPS context with SSL/TLS rejection settings
context = ssl.DefaultOpenSSLContextFactory(
        certificateFileName='cert.pem',
        privateKeyFileName='key.pem',
    sslmethod=SSL.TLSv1_2_METHOD,
)

class Simple(Resource):
    isLeaf = True
    def render_GET(self, request):
        return b"<html>Hello, world!</html>"

# Create HTTPS server
site = Site(Simple())
reactor.listenSSL(8443, site, context)

print('Server running')

# Run the Twisted reactor
reactor.run()

```


Try with tls1.1 ... it fails

```
$ openssl s_client -connect localhost:8443 -tls1_1 -msg

CONNECTED(00000003)
>>> TLS 1.2, RecordHeader [length 0005]
    15 03 03 00 02
>>> TLS 1.3, Alert [length 0002], fatal protocol_version
    02 46
40D7A6BC4D780000:error:0A0000BF:SSL routines:tls_setup_handshake:no protocols available:../ssl/statem/statem_lib.c:104:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

EXIT CODE 1
```

try with tls 1.2, it works

```
$ openssl s_client -connect localhost:8443 -tls1_2 -msg

You see the whole server certificate and stuff :)
```

I am closing this.

Freel fre to add more info if you think that this is still an issue.

The openssl output is misleading.

**Comment by KaviHarjani** [comment]
It is working for me with tls_2 actually
```
SSL handshake has read 2272 bytes and written 281 bytes
Verification error: self signed certificate
```
but it shows error then, and my problem was and still is why does it show **Verification: OK**  with tls1_1

Why not failed or an error?
Also with this will it be only available for TLS1_2

**Comment by adiroiban** [comment]
`Verification: OK` is something from the openssl ouput. This is not related to Twisted.

I expect that you will get the same output with any server.

From my tests, `openssl s_client` fails with exit code 1.

and the error is clear

```
139698017736000:error:141E70BF:SSL routines:tls_construct_client_hello:no protocols available:../ssl/statem/statem_clnt.c:1112:
```


I got the same output with google.com for example, if I try tls 1.1

```
$ openssl s_client -connect google.com:443 -tls1_1 -msg
CONNECTED(00000003)
>>> TLS 1.2, RecordHeader [length 0005]
    15 03 03 00 02
>>> TLS 1.3, Alert [length 0002], fatal protocol_version
    02 46
4027D35B4D790000:error:0A0000BF:SSL routines:tls_setup_handshake:no protocols available:../ssl/statem/statem_lib.c:104:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 7 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

and now try and see the difference in output

```
 openssl s_client -connect google.com:443 -tls1_2 -msg
```

----------

I am leaving this close for now.

Please double-check.

I am happy to reopen if it's the case.

To me, it still looks like Twisted is ok.

The `openssl s_client` is a bit confusing... but it fails.
