### ISSUE TITLE
Idea: Remove `_get_async_param` method

### ISSUE THREAD

**Issue by gudnimg** [twisted/twisted#12130]
**Is your feature request related to a problem? Please describe.**

An idea to cleanup the project. `_get_async_param()` was added in Twisted 18.9.0 to mitigate an issue where Python 3.7 introduced the `async` keyword which caused problem where variables were trying to use that name also. 

Now that Twisted supports only Python 3.8+ would it make sense to remove this method since all supported Python versions now include the `async` keyword? Or is Twisted stuck with this API change?

See: https://github.com/twisted/twisted/issues/9384

If it is acceptable to remove it, I can submit a PR for it.

**Comment by adiroiban** [comment]
Hi, Thanks for the ticket.
Any cleanup PR is much appreciated.

Looking forward to review the PR. Thanks again!
