### ISSUE TITLE
t.w.h.HTTPClient parses Content-Length laxly

### ISSUE THREAD

**Issue by twm** [twisted/twisted#12159]
**Describe the incorrect behavior you saw**

The `twisted.web.http.HTTPClient` protocol accept invalid integers for the `Content-Length` header, such as `+1`. (It also suffers from the issue described in #9064, but we shouldn't bother fixing that because of 

**Describe the correct behavior you'd like to see**

Reject invalid values. See the tests and `_decint` function introduced in #735.

**Comment by adiroiban** [comment]
Do we want to fix this, or just deprecate the code?

**Comment by twm** [comment]
It has been deprecated, so I'll close this.
