### ISSUE TITLE
Deprecate t.w.h.HTTPClient

### ISSUE THREAD

**Issue by twm** [twisted/twisted#12158]
**Is your feature request related to a problem? Please describe.**

I think this speaks for itself:

https://github.com/twisted/twisted/blob/dd3b1f38a60f960efeda1388536ff50512878591/src/twisted/web/http.py#L626-L628

It looks like we forgot to deprecate and remove this along with `getPage` and friends (in #10295).

**Describe the solution you'd like**

Deprecate it, and file a ticket to remove it per policy.

**Describe alternatives you've considered**

Leave it sitting there like a footgun. :man_shrugging: 

**Additional context**

See https://github.com/twisted/twisted/pull/735#discussion_r1588776725 and note #12159.

**Comment by adiroiban** [comment]
+1 deprecate it... and I think that we should just skip trying to fix the [existing bugs](https://github.com/twisted/twisted/issues?q=is%3Aissue+is%3Aopen+HTTPClient
)

**Comment by glyph** [comment]
👍

**Comment by glyph** [comment]
FWIW I think the reason it has lingered on so long is that it's the backing for `getPage`, which the docs use a bunch

**Comment by twm** [comment]
`getPage` was removed in #10295 so I'll clean up any lingering references as part of this.
