### ISSUE TITLE
absorb twisted-infra/twisted-benchmarks into a codspeed benchmark

### ISSUE THREAD

**Issue by glyph** [twisted/twisted#12193]
We have a bunch of existing microbenchmarks in https://github.com/twisted-infra/twisted-benchmarks.  Now that we have codspeed set up to give us some performance baselines, it seems like it would be worthwhile to copy all these over, update them as necessary (I'm sure they don't all work any more, as it's been 5 years since they've seen any maintenance at all) and get them integrated with our benchmark runs.

cc @itamarst of course

* [ ] amp.py
* [x] deferred_await.py
* [x] deferred_callback_chains.py
* [ ] deferred_yieldfrom.py (I am not sure I even know what this means, so skipping —@itamarst)
* [ ] int16receiver.py
* [ ] iteration.py (need to figure out how to deal with benchmarks that require reactor)
* [x] lineonlyreceiver.py
* [x] linereceiver.py
* [ ] names.py
* [ ] pb.py
* [ ] ssh_connect.py
* [ ] sshendpoint.py
* [ ] ssh_throughput.py
* [ ] sslbio_connect.py
* [ ] sslbio_throughput.py
* [ ] ssl_connect_contextfactory.py
* [ ] ssl_connect.py
* [ ] ssl_throughput.py
* [ ] tcp_connect.py
* [ ] tcp_throughput.py
* [ ] threads.py
* [ ] web.py
* [ ] web_template.py

**Comment by itamarst** [comment]
I probably won't do all of them, but can do a bunch that are relevant to my paid work.
