### ISSUE TITLE
Auto redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by KaviHarjani** [twisted/twisted#12214]
I am trying to redirect all traffic from http 3000 to https 3000

If there is an auto redirect then it's great otherwise I will have to ask the api users to upgrade to https and simultaneously push the upgrade 

An alternative would be to use a web server or reverse proxy by Twisted but I am trying to avoid those

Is it possible?

**Comment by adiroiban** [comment]
Thanks for the report

I think that this is a duplicate for #7338

A way to somehow mitigate this is to use Strict-Transport-Security ... but it will still not work for hte first connection.

I am using this patch https://github.com/twisted/twisted/pull/1483 ... it's not perfect.

If you have time, you can take a look at the feedback for that PR and try to submit a bette PR to fix the issue/

I am closing this as a duplicate

We can continue to conversation at #7338 or over a PR
