### ISSUE TITLE
Speed up Deferred: isinstance() is slow

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12223]
Deferred callback does an `instance(result, Deferred)` in the hot path, which is a pretty expensive operation.

**Comment by glyph** [comment]
IIRC we used to have a `type(...) is` check here, and changed it because we didn't have benchmarks to justify it being all that slow, at around the time `DeferredList` got added.  I gather inheriting from `Awaitable` might have changed the calculus here?

**Comment by arnimarj** [comment]
I got curious and created this:

```shell
import timeit


setup = 'from twisted.internet.defer import Deferred\nx = Deferred()\nb=False'

fast = '''
if x.__class__ is Deferred or isinstance(x, Deferred):
	b = True
'''


slow = '''
if isinstance(x, Deferred):
	b = True
'''

N = 10_000_000

T = timeit.timeit(stmt=fast, number=N, setup=setup)
print(T)

T = timeit.timeit(stmt=slow, number=N, setup=setup)
print(T)
```

...which gave me approximately this:

```shell
0.09645763300068211
0.1443577739992179
```

**Comment by glyph** [comment]
> I got curious and created this:

The problem with this benchmark is that it goes faster *only* if `x` _is_ a `Deferred`. In the case we are doing the `isinstance` check, it's actually much more common that `x` is *not* a `Deferred`.
