### ISSUE TITLE
twisted.web parses header names too permissively

### ISSUE THREAD

**Issue by kenballus** [twisted/twisted#12235]
# Description of the bug
twisted.web does not sufficiently validate HTTP/1.1 header names.

The RFCs permit the following bytes within header names:
> "!" / "#" / "$" / "%" / "&" / "'" / "*"
                 / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                 / DIGIT / ALPHA

twisted.web does not enforce this rule. Instead, it allows all bytes within header names, except
- CR and LF, because they're translated to SP (which also isn't permitted),
- and colon, because it's the field separator.

In the past, being too permissive with header name parsing has led to vulnerabilities, in particular with SP and NUL bytes, both of which are permitted by twisted.web

# To reproduce

1. Start a twisted.web server that echos headers, such as [this one](https://github.com/narfindustries/http-garden/blob/main/images/twisted/server.py)
2. Send it a request containing all of the bytes that are not valid in header names (except CR, LF, and colon for the reasons listed above):
```sh
(printf 'GET / HTTP/1.1\r\n\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0b\x0c\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f\x20\x22\x28\x29\x2c\x2f\x3b\x3c\x3d\x3e\x3f\x40\x5b\x5c\x5d\x7b\x7d\x7f\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89\x8a\x8b\x8c\x8d\x8e\x8f\x90\x91\x92\x93\x94\x95\x96\x97\x98\x99\x9a\x9b\x9c\x9d\x9e\x9f\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff: test\r\n\r\n'; sleep 1) \
    | nc localhost 80 \
    | grep '"headers"' \
    | jq '.["headers"][0][0]' \
    | xargs echo \
    | base64 -d \
    | xxd
```
3. Observe that the invalid header name is preserved:
```
00000000: 0001 0203 0405 0607 0809 0b0c 0e0f 1011  ................
00000010: 1213 1415 1617 1819 1a1b 1c1d 1e1f 2022  .............. "
00000020: 2829 2c2f 3b3c 3d3e 3f40 5b5c 5d7b 7d7f  (),/;<=>?@[\]{}.
00000030: 8081 8283 8485 8687 8889 8a8b 8c8d 8e8f  ................
00000040: 9091 9293 9495 9697 9899 9a9b 9c9d 9e9f  ................
00000050: a0a1 a2a3 a4a5 a6a7 a8a9 aaab acad aeaf  ................
00000060: b0b1 b2b3 b4b5 b6b7 b8b9 babb bcbd bebf  ................
00000070: c0c1 c2c3 c4c5 c6c7 c8c9 cacb cccd cecf  ................
00000080: d0d1 d2d3 d4d5 d6d7 d8d9 dadb dcdd dedf  ................
00000090: e0e1 e2e3 e4e5 e6e7 e8e9 eaeb eced eeef  ................
000000a0: f0f1 f2f3 f4f5 f6f7 f8f9 fafb fcfd feff  ................
```

# The correct behavior I'd like to see
This request should be rejected with a 400 response. This is what nearly all other HTTP implementations do, including AIOHTTP, Apache httpd, Apache Traffic Server, Cheroot, FastHTTP, Go net/http, Gunicorn, H2O, HAProxy, Hyper, Hypercorn, Jetty, Lighttpd, Mongoose, Netty, Nginx, Node.js, LiteSpeed, Passenger, Puma, Apache Tomcat, OpenWrt uhttpd, Uvicorn, Waitress, WEBrick, OpenBSD httpd, nghttpx, Pingora, Pound, Squid, Varnish, Akamai GHost, Google Classic Application Load Balancer, Envoy, and OpenBSD relayd.

# Versions
 - Operating System and Version; paste the output of these commands:
   - `Linux de3e554c0340 6.9.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000 x86_64 GNU/Linux`
 - Twisted version [e.g. 22.2.0]
   - 24.3.0.post0

**Comment by twm** [comment]
Thank you again for the report, @kenballus! I've addressed this in #12246 by validating that header names are `token`s per RFC 9110.
