### ISSUE TITLE
Disordered HTTP pipeline response in twisted.web, again

### ISSUE THREAD

**Issue by twm** [twisted/twisted#12248]
https://github.com/twisted/twisted/security/advisories/GHSA-c8m8-j448-xjx7

**Comment by adiroiban** [comment]
This was merge here https://github.com/twisted/twisted/commit/4a930de12fb67e88fefcb8822104152f42b27abc

The PR discussion was lost as the private fork was also removed.

----------

We need to see if there is a way to make the PR conversation public.
