### ISSUE TITLE
Replace Failure._findFailure dependency on bytecode with some mechanism that doesn't rely on bytecode

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12288]
The problem:

* As seen in #12061, changes to generated bytecode can break `Failure`'s special `inlineCallbacks` related code(and quite possibly async functions too).
* In a world where a CPython JIT is a possibility, it's not clear if any of this will work at all in the future.

It would be better to have a mechanism for finding the current failure that is less tied to obscure implementation details of Python. Perhaps contextvars might do the trick?

**Comment by itamarst** [comment]
:scream: that is all

**Comment by itamarst** [comment]
Notes for the PR:

* It also fixes #12061 and #12234.
* This doesn't yet use use Python's nicer traceback printing (column indicators), mostly to keep the PR limited. #12289 is the followup to do so.

**Comment by glyph** [comment]
@itamarst uhhh; presumably you meant something other than #12016?

**Comment by itamarst** [comment]
Yep, updated.
