### ISSUE TITLE
Automat 24.8.0 breaks with Twisted 23.8.0

### ISSUE THREAD

**Issue by RazvanLiviuVarzaru** [twisted/twisted#12295]
Hello!

It's a bit unclear for me if this should be addressed here or to Automat. I've opened an issue also for Automat.
It seems that the yesterday release of **automat** won't work anymore with Twisted 23.8.0. I am using Buildbot.

Environment:
    OS: Debian GNU/Linux 10 (buster)
    python version: 3.7.3
    twisted version: 23.8.0
    buildbot-worker version: 4.0.2
    automat version: 24.8.0
 

**Will lead to:**
`Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python3.7/dist-packages/twisted/scripts/twistd.py", line 29, in runApp
    runner.run()
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 370, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 437, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/app.py", line 446, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/service.py", line 404, in loadApplication
    application = sob.loadValueFromFile(filename, "application")
  File "/usr/local/lib/python3.7/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "buildbot.tac", line 9, in <module>
    from buildbot_worker.bot import Worker
  File "/usr/local/lib/python3.7/dist-packages/buildbot_worker/bot.py", line 20, in <module>
    from buildbot_worker.pb import Worker
  File "/usr/local/lib/python3.7/dist-packages/buildbot_worker/pb.py", line 23, in <module>
    from twisted.application.internet import ClientService
  File "/usr/local/lib/python3.7/dist-packages/twisted/application/internet.py", line 44, in <module>
    from automat import MethodicalMachine  # type: ignore[import]
  File "/usr/local/lib/python3.7/dist-packages/automat/__init__.py", line 5, in <module>
    from ._typed import TypeMachineBuilder, pep614, AlreadyBuiltError, TypeMachine
builtins.SyntaxError: invalid syntax (_typed.py, line 511)
`

Rollback to automat 22.10 solves the issue.

The problematic automat version is installed automatically when:
`pip3 --no-cache-dir install 'twisted[tls]'`

**Comment by adiroiban** [comment]
Hi Răzvan.
Thanks for the report.

Maybe this is related to https://github.com/twisted/twisted/pull/12236

I don't know what we can do here... with calver, it's hard to prevent such errors.

Reference to automat issue https://github.com/glyph/automat/issues/159

In Twisted we have this dependency definition

https://github.com/twisted/twisted/blob/fd305d631295d3e0748518cf5374b8f5dea88f7b/pyproject.toml#L37

I don't want to update it and add an upper limit

------

I guess that the only fix is to get #12236 merged and released

**Comment by RazvanLiviuVarzaru** [comment]
> Hi Răzvan. Thanks for the report.
> 
> Maybe this is related to #12236
> 
> I don't know what we can do here... with calver, it's hard to prevent such errors.
> 
> Reference to automat issue [glyph/automat#159](https://github.com/glyph/automat/issues/159)
> 
> In Twisted we have this dependency definition
> 
> https://github.com/twisted/twisted/blob/fd305d631295d3e0748518cf5374b8f5dea88f7b/pyproject.toml#L37
> 
> I don't want to update it and add an upper limit
> 
> I guess that the only fix is to get #12236 merged and released

Thanks @adiroiban for the fast reply. I pinned the `automat` version to 22.10 for the affected container images on my side.
Having at my disposal a diverse CI system with many OS's and arch's I can say that the issue is not reproduced in all cases.
For example, I cannot reproduce it on:

OS -> OpenSUSE Leap 15.6
Twisted --> 24.7.0
buildbot-worker -> 4.0.2
automat --> 24.8.0
python --> 3.12

I don't know exactly what is causing it but newer twisted versions seems to be bug free on this matter.

**Comment by adiroiban** [comment]
I am closing this as I don't think there is anything we can do on Twisted side.

Note, that we only support 24.7.0

Even if there is a fix, we don't plan to do a bugfix release for 23.8.0

**Comment by altendky** [comment]
https://github.com/glyph/automat/pull/158 would avoid your Python 3.7 install from trying to use this version of automat that is 3.8+.

Is the issue here really an automat twisted incompatibility?  Or just a 3.7 incompatibility in automat that now claims 3.8+?

**Comment by glyph** [comment]
This has been addressed in Automat.
