### ISSUE TITLE
deprecated ciphers causing runtime messages

### ISSUE THREAD

**Issue by TFarrell89** [twisted/twisted#12308]
Runtime usage in opencanary on ubuntu 22.04

/usr/local/lib/python3.10/dist-packages/twisted/conch/ssh/transport.py:97: CryptographyDeprecationWarning: Blowfish has been deprecated
  b"blowfish-cbc": (algorithms.Blowfish, 16, modes.CBC),
/usr/local/lib/python3.10/dist-packages/twisted/conch/ssh/transport.py:101: CryptographyDeprecationWarning: CAST5 has been deprecated
  b"cast128-cbc": (algorithms.CAST5, 16, modes.CBC),
/usr/local/lib/python3.10/dist-packages/twisted/conch/ssh/transport.py:106: CryptographyDeprecationWarning: Blowfish has been deprecated
  b"blowfish-ctr": (algorithms.Blowfish, 16, modes.CTR),
/usr/local/lib/python3.10/dist-packages/twisted/conch/ssh/transport.py:107: CryptographyDeprecationWarning: CAST5 has been deprecated
  b"cast128-ctr": (algorithms.CAST5, 16, modes.CTR),

delete lines per pull request to follow. 

confirmed as good: 
Linux honeypooh 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"

**Comment by TFarrell89** [comment]
PR: https://github.com/twisted/twisted/pull/12309

**Comment by TFarrell89** [comment]
automated tests: 

failed newsfragment - I don't get why [details]([url](https://github.com/twisted/twisted/actions/runs/10761811130/job/29841420007?pr=12309))

> No new newsfragments found on this branch.
> ERROR: InvocationError for command /home/runner/work/twisted/twisted/.tox/newsfragment/bin/python -m towncrier check --compare-with=origin/trunk (exited with code 1)
> 
> =================================== log end ====================================
> ✖ FAIL newsfragment in 21.[134](https://github.com/twisted/twisted/actions/runs/10761811130/job/29841420007?pr=12309#step:5:137) seconds

**Comment by TFarrell89** [comment]
PR: https://github.com/twisted/twisted/pull/12310

**Comment by adiroiban** [comment]
This looks like a duplicate for https://github.com/twisted/twisted/issues/12138

**Comment by TFarrell89** [comment]
please review
