### ISSUE TITLE
Disable Nagle in HTTP client and server

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12311]
After spending a bunch of time trying to figure out why Tahoe-LAFS is spending a surprising amount of time idle while doing HTTP interactions, I discovered it was Nagle adding 40ms to small queries. 

The argument for disabling Nagle / enabling TCP_NODELAY:

* HTTP is often used for small, RPC-like queries, so delaying queries by 40ms is bad.
* Large bodies typically won't benefit Nagle anyway.
* HTTPS is all anyone uses in practice these days, and Twisted's TLS layer already does some minimal buffering to reduce small writes: https://github.com/twisted/twisted/blob/f0afc5eb9850eda242beefb178dd481e28926f08/src/twisted/protocols/tls.py#L818

**Comment by itamarst** [comment]
https://brooker.co.za/blog/2024/05/09/nagle.html argues that TCP_NODELAY should be enabled by default (==Nagle disabled by default) everywhere.

**Comment by glyph** [comment]
This sounds like a really good rationale for disabling nagle. I think this sort of rationale is why HTTP/3 is UDP based.
