### ISSUE TITLE
After the TLS protocol is configured, there is a 10-minute delay in continuous data transmission

### ISSUE THREAD

**Issue by wqc01202410** [twisted/twisted#12315]
Is anyone can help me?

A TCP link is set up to transmit data between the client and server. After the TLS certificate is configured, the next data object cannot be sent immediately when the data object is sent continuously. The second data object cannot be sent immediately after frame freezing for 10 minutes. According to the tcpdump tool, there is a delay when the client sends the second data object. Not sure the reason for the 10 minute delay.

The client uses endpoints.SSL4ClientEndpoint, the server uses endpoints.SSL4ServerEndpoint, the protocol type is TLSv1_2, the SSL certificate is self-signature certificate, the Python version is Python 3.8, and the twisted version is 24.7.0. The server is running in Linux and runs normally on Windows.

client code is [here](https://gitee.com/ascend/mstt/blob/master/debug/accuracy_tools/msprobe/pytorch/api_accuracy_checker/tensor_transport_layer/client.py)
server code is [here](https://gitee.com/ascend/mstt/blob/master/debug/accuracy_tools/msprobe/pytorch/api_accuracy_checker/tensor_transport_layer/server.py)

**Comment by exarkun** [comment]
The mailing list would be a better forum for getting help with something like this.

The linked code mixes multi-threading with Twisted in ways that aren't supported.  It's not clear to me that there's a bug in Twisted here.  Instead, the problem probably comes from calling Twisted APIs that aren't thread-safe from multiple threads.
