### ISSUE TITLE
mypy suddenly started failing

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12329]
Not sure why.

e.g. https://github.com/twisted/twisted/actions/runs/11276233177/job/31359524493

**Comment by itamarst** [comment]
These are legit errors, mind, I'm just not sure why mypy didn't catch them before.

**Comment by itamarst** [comment]
Oh, new mypy release.

**Comment by glyph** [comment]
c.f. #12114

**Comment by itamarst** [comment]
I think this is some weird resolver bug, though.

**Comment by glyph** [comment]
> I think this is some weird resolver bug, though.

No bug. We have a constraint of `~=1.8` which literally just pins to the `1.x` series, so a straight `pip install 'mypy~=1.8'` gives me mypy 1.11.2.  We need exact constraints, `~=` is only for religious observances about semver. Given that we are not practicing members of that religion, we forgot that its use in such rituals must be accompanied by a 3-segment version to have any use
