### ISSUE TITLE
Link to installation docs (and maybe other docs?) in PyPI description is broken

### ISSUE THREAD

**Issue by itamarst** [twisted/twisted#12327]
https://pypi.org/project/Twisted/ has link to https://docs.twisted.org/en/latest/installations.rst ("the installation instructions") which 404s. Might be other broken links as well.

**Comment by adiroiban** [comment]
Thanks for the report


I think that those links are extracted from our project definition

https://github.com/twisted/twisted/blob/075191d3fd03193e48247fff39e108c784962da2/pyproject.toml#L148-L154


We should have them fixed before the next release

I think that the only way to update the PyPI project page is to push a new package version

I have marked this as a release blocker to server as reminder

**Comment by adiroiban** [comment]
Also look for the links in the README file ... this was the original error report from Itamar

PR ready for review at https://github.com/twisted/twisted/pull/12336
