### ISSUE TITLE
Critical bug in 24.10.0 that gets hit by django's daphne

### ISSUE THREAD

**Issue by karolyi** [twisted/twisted#12347]
Hello,

upon updating to 24.10.0, I started to see exceptions coming in production servers. It took a bit of investigation to figure out that it seems to originate from twisted, and not daphne.

Please look into https://github.com/django/daphne/issues/535

**Comment by carltongibson** [comment]
Here's the bottom of the traceback from @karolyi's report on Daphne: 

```
  File "/home/karolyi/project/ticketshop/venv/lib/python3.10/site-packages/daphne/http_protocol.py", line 230, in finish
    http.Request.finish(self)
  File "/home/karolyi/project/ticketshop/venv/lib/python3.10/site-packages/twisted/web/http.py", line 1240, in finish
    self._cleanup()
  File "/home/karolyi/project/ticketshop/venv/lib/python3.10/site-packages/twisted/web/http.py", line 966, in _cleanup
    self.channel.requestDone(self)
  File "/home/karolyi/project/ticketshop/venv/lib/python3.10/site-packages/twisted/web/http.py", line 2643, in requestDone
    self._networkProducer.resumeProducing()
AttributeError: 'HTTPChannel' object has no attribute '_networkProducer'
```

Plus, relevant extract: 

> So the issue clearly can be linked to running daphne (and not django's runserver) with a socket passed, e.g.:
> 
>    env DJANGO_SETTINGS_MODULE=project.settings daphne --websocket_timeout=43200 --access-log=logs/daphne.log -u=/tmp/asgi-daphne-project.sock --proxy-headers --proxy-headers-host X-Real-IP project.asgi:application
> 
> This way I can reproduce the bug locally too. But in order to test this, you'll need a minimally configured nginx (which I luckily have) that will listen on the actual http port and forward the messages to the unix socket.

**Comment by adiroiban** [comment]
Many thanks for the report

The thing is that from what I see, `daphne` uses a custom `twisted.web.http.Request` implementation... which also makes some changes to the private API

https://github.com/django/daphne/blob/06afd9b94aa82ebdfea945a1810ce25d32d3593b/daphne/http_protocol.py#L17

---------

I think that for the scope of Twisted, we should look to reproduce this error using only `twisted.web.http.Request`

**Comment by adiroiban** [comment]
You can check the implementation of resumeProducing in the HTTP channel

I see there is a conditional call to `self._networkProducer.resumeProducing()`

In `requestDone()`, the condition is `if not self._waitingForTransport:` while in `resumeProducing()` the condition is `if not self._handlingRequest:`

https://github.com/twisted/twisted/blob/c3e5f0293824ecca68960a3b5e4c7154d461307a/src/twisted/web/http.py#L2895-L2912


-------

I guess the issue is with `requestDone()`  

Maybe somehow the connection is lost before `requestDone()` is called...and we no longer have a transport.

**Comment by itamarst** [comment]
I looked through the PRs merged since 24.7: https://github.com/twisted/twisted/pulls?page=1&q=is%3Apr+is%3Aclosed

1. None of them seemed to obviously be the cause. I could have missed something obvious though, someone else should do the same!
2. https://github.com/twisted/twisted/pull/12312/files does change those codepaths, but not sure in way that would cause an issue.
3. That same PR makes twisted.web _respond faster_ when it's running over TCP. In general, this is a good thing. However, it's possible there's a pre-existing race condition that was exposed by this extra speed. But... the reproducer involves a unix socket, not TCP? Does nginx just proxy to the unix socket, or does it transfer the original TCP file descriptor over the unix socket?

**Comment by itamarst** [comment]
Oh, reading the original report, there's some intermittent failures with 24.7 too? I'll dig deeper.

**Comment by itamarst** [comment]
https://github.com/twisted/twisted/pull/12157/files is another candidate, as is https://github.com/twisted/twisted/pull/12149/files

**Comment by carltongibson** [comment]
@itamarst I'm not sure about the failures for 24.7, O don't think that's confirmed. 

(I hit test errors initially because I had a bad branch checkout, but that's not related.)

As I understand it, both reporters said pinning to 24.7 resolved the issue. 

I'm currently trying to get a reproduce so I can bisect.

**Comment by karolyi** [comment]
@carltongibson here's a minimal nginx config:

```
worker_processes  1;
pid tools/dev-nginx/nginx.pid;
daemon off;
master_process off;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;
    types_hash_bucket_size 256;
    types_hash_max_size 1024;
    client_body_temp_path /tmp/project/client-body;
    fastcgi_temp_path /tmp/project/fastcgi;
    uwsgi_temp_path /tmp/project/uwsgi;
    scgi_temp_path /tmp/project/scgi;
    access_log /dev/stdout;
    error_log /dev/stdout info;

    upstream backend {
        server 127.0.0.1:8000 fail_timeout=1s;
    }

    server {
        http2 on;
        listen       *:8081         ssl;
        listen       [::]:8081      ssl;
        server_name  test.localdomain;

        ssl_certificate             cert.pem;
        ssl_certificate_key         key.pem;

        location /api/media {
            alias /tmp/project/media;
        }

        location /ws/ {

            # proxy_pass          http://unix:/tmp/asgi-daphne-project-test.sock;
            proxy_pass          http://test.localdomain:8000;
            proxy_http_version  1.1;
            proxy_set_header    Upgrade $http_upgrade;
            proxy_set_header    Connection 'Upgrade';

            proxy_redirect      off;
            proxy_set_header    Host $host;
            proxy_set_header    X-Forwarded-Host $server_name;
            proxy_set_header    X-Forwarded-Proto $scheme;
            proxy_set_header    X-Forwarded-For '';
            proxy_set_header    X-Real-IP $remote_addr;
        }

        location /static/assets/ {
            try_files $uri @django;
        }

        location @django {
            # proxy_pass          http://unix:/tmp/asgi-daphne-project-test.sock;
            proxy_pass          http://backend;
            proxy_read_timeout  600s;

            proxy_redirect      off;
            proxy_set_header    Host $host;
            proxy_set_header    X-Forwarded-Proto $scheme;
            proxy_set_header    X-Forwarded-For '';
            proxy_set_header    X-Forwarded-Host $server_name;
            proxy_set_header    X-Real-IP $remote_addr;
        }

        location / {
            try_files '' @django;
            # error_page 404 = @django;
        }

    }
}

```

dd your local self-signed certificates (I did that) and comment/uncomment the `proxy_pass` lines, and in general, adjust it to your needs.

then you can use nginx to test the bug.

**Comment by p12tic** [comment]
Can this be the same as https://github.com/twisted/twisted/issues/12365? In the example config I see unix sockets. Support for those on HTTP has been definitely broken since 24.10.0.

**Comment by carltongibson** [comment]
With a reproduce for the Daphne issue, @smithdc1 [bisected](https://github.com/django/daphne/issues/535#issuecomment-2481424857) the issue to a7bf9331f78b216e1f00322fabb34de64a91ea85 which was part of #12312, identified as the likely cause of #12365.

**Comment by itamarst** [comment]
If it turns out it's not the unix sockets thing, that specific commit mostly just made Twisted faster in many scenarios :grimacing:, which would suggest a race condition somewhere?

**Comment by glyph** [comment]
> If it turns out it's not the unix sockets thing, that specific commit mostly just made Twisted faster in many scenarios 😬, which would suggest a race condition somewhere?

So, I have seen a traceback about producers from Twisted Web in the past, usually while seeking around in video files. (In particular, most recently, when downloading some videos from PyCon and playing them back from a twisted webserver on my trip home.)  Looks like I never filed it so I will have to go reproduce it, but this could be in the same vicinity.

**Comment by glyph** [comment]
> If it turns out it's not the unix sockets thing, that specific commit mostly just made Twisted faster in many scenarios 😬, which would suggest a race condition somewhere?

There's a known race condition where sometimes you can't set nodelay while a socket is connecting, and that would manifest the same way (`connectionMade` tracebacks, state on the connection is corrupted and that attribute doesn't exist, things expect it to exist) so the same fix would fix it?

**Comment by hagen00** [comment]
Running `Twisted==24.11.0rc1` works for me. No errors!
