### ISSUE TITLE
endpoints.clientFromString doesn't work with "tls:..." after Twisted 24.10.0

### ISSUE THREAD

**Issue by fujii** [twisted/twisted#12350]
The following code works with Twisted 24.7.0, but with Twisted 24.10.0.

~~~
from twisted.internet import defer, endpoints, protocol, ssl, task
from twisted.python.modules import getModule
from twisted.protocols.basic import LineReceiver

class EchoClient(LineReceiver):
    def connectionMade(self):
        print("connectionMade")

    def lineReceived(self, line):
        print("receive:", line)

@defer.inlineCallbacks
def main(reactor):
    factory = protocol.Factory.forProtocol(EchoClient)
    endpoint = endpoints.clientFromString(reactor, "tls:twisted.org:443")
    echoClient = yield endpoint.connect(factory)

    done = defer.Deferred()
    echoClient.connectionLost = lambda reason: done.callback(None)
    yield done

if __name__ == "__main__":
    task.react(main)
~~~

~~~
main function encountered error
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\twisted\internet\defer.py", line 2013, in _inlineCallbacks
    result = context.run(
  File "C:\Python312\Lib\site-packages\twisted\python\failure.py", line 467, in throwExceptionIntoGenerator
    return g.throw(self.value.with_traceback(self.tb))
  File "C:\home\tmp\test3\echoclient_ssl_str.py", line 16, in main
    echoClient = yield endpoint.connect(factory)
  File "C:\Python312\Lib\site-packages\twisted\internet\endpoints.py", line 674, in _resolvedHostConnect
    self._reactor.connectTCP(
  File "C:\Python312\Lib\site-packages\twisted\internet\posixbase.py", line 368, in connectTCP
    c.connect()
  File "C:\Python312\Lib\site-packages\twisted\internet\base.py", line 1266, in connect
    self.transport: Optional[Client] = self._makeTransport()
  File "C:\Python312\Lib\site-packages\twisted\internet\tcp.py", line 1530, in _makeTransport
    return Client(self.host, self.port, self.bindAddress, self, self.reactor)
  File "C:\Python312\Lib\site-packages\twisted\internet\tcp.py", line 731, in __init__
    if abstract.isIPv6Address(bindAddress[0]):
  File "C:\Python312\Lib\site-packages\twisted\internet\abstract.py", line 539, in isIPv6Address
    return isIPAddress(addr, AF_INET6)
  File "C:\Python312\Lib\site-packages\twisted\internet\abstract.py", line 510, in isIPAddress
    addr = addr.split("%", 1)[0]
builtins.AttributeError: 'NoneType' object has no attribute 'split'
~~~

**Testing environment**

OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Dell Inc. 2.19.0, 9/6/2024
Time Zone:                 (UTC+09:00) Osaka, Sapporo, Tokyo
                           [02]: VirtualBox Host-Only Ethernet Adapter

**Comment by adiroiban** [comment]
Many thanks for the report... I guess that this is related to https://github.com/twisted/twisted/pull/12326

I didn't had time to investigate more

We have this test

https://github.com/twisted/twisted/blob/b894b2375ee14c15711828b4ee859f594e580824/src/twisted/internet/test/test_endpoints.py#L2730-L2733

**Comment by adiroiban** [comment]
We have this function that expects a string ... and now receives None

https://github.com/twisted/twisted/blob/b894b2375ee14c15711828b4ee859f594e580824/src/twisted/internet/abstract.py#L545-L557


---------

For `endpoints.HostnameEndpoint(self.drr, b"example.com", 80, bindAddress=None)` ,  instead of setting up an internal address as None, maybe is best to see a placehoder addresss like `0.0.0.0:0` 


Not sure how to handle IPv6 


----------

I was expecting that we already have automated tests for this use case, as it looks basic

```
endpoint = endpoints.clientFromString(reactor, "tls:twisted.org:443")
echoClient = yield endpoint.connect(factory)
```

**Comment by glyph** [comment]
so this is a type-confusion bug and we are missing type annotations throughout here, so I've started a branch to add some of them in (and do some type refactorings, and get rid of the `bytes is str` stuff that this code is super concerned with)

**Comment by glyph** [comment]
okay, I just kept adding lots of types until I saw the type error, and now mypy is failing over on #12351 :)

**Comment by glyph** [comment]
PR is up for review, I think it should thoroughly address the issue here.

**Comment by glyph** [comment]
@fujii If you have time, it would be great if you could confirm that trunk addresses your issue.

**Comment by fujii** [comment]
I confirmed the bug was fixed. Thank you very much.
