### ISSUE TITLE
task: enable trusted publishing

### ISSUE THREAD

**Issue by graingert** [twisted/twisted#12376]
**Is your feature request related to a problem? Please describe.**
we should enable trusted publishing and attestations - invalidate and drop the PyPI api key from our secrets

**Describe the solution you'd like**
Go to https://pypi.org/manage/project/twisted/settings/publishing/ configure trusted publishing for https://github.com/twisted/twisted/ in the test.yaml file and the release environment (that I just created)

**Describe alternatives you've considered**
just continue without it

**Additional context**
we should configure some protection rules on the release environment

**Comment by adiroiban** [comment]
I think that this should already be setup.

It's just that I forgot to update it ...

We can only test it during a pre-release or release process ... and I alwasy forgot to enable it as part of a release PR.

maybe we can have it done as part of 24.10.0 release

**Comment by adiroiban** [comment]
Thanks Thomas for the report

I am closing this as I think that this is a duplicate for https://github.com/twisted/twisted/issues/11869
