### ISSUE TITLE
task: twitter URL fails with a 403, we should remove it

### ISSUE THREAD

**Issue by graingert** [twisted/twisted#12377]
**Is your feature request related to a problem? Please describe.**
```
curl -IL https://twitter.com/twistedmatrix
HTTP/2 403 
date: Tue, 26 Nov 2024 07:51:20 GMT
perf: 7402827104
server: tsa_f
set-cookie: guest_id=v1%3A173260748026692071; Max-Age=34214400; Expires=Sat, 27 Dec 2025 07:51:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None
x-powered-by: Express
cache-control: no-cache, no-store, max-age=0
x-transaction-id: 2a56c257200c02dd
strict-transport-security: max-age=631138519
x-response-time: 121
x-connection-hash: cd234d2ed6d69c6431c98c5dc8b1fc139e9af702cbffb8098e2d800d0d68056c
```
seems it went down for some reason

**Describe the solution you'd like**
We should remove the dead link from the metadata and docs

**Describe alternatives you've considered**
we could replace the twitter link with a fediverse link

**Additional context**
It seems like twitter could be under new management, and this issue was caused during this process

**Comment by adiroiban** [comment]
the account is up... but I think that is behind a login wall

I think that for Twisted project we should not use communication channels that require a login to read
