### ISSUE TITLE
Unable to add File path in putchild

### ISSUE THREAD

**Issue by KaviHarjani** [twisted/twisted#12382]
**Describe the incorrect behavior you saw**

```
REACT_APP = os.path.abspath(os.path.join(BASE_DIR, "..", "dist", "index.html"))
REACT_APP_STATIC = os.path.abspath(os.path.join(BASE_DIR, "..", "dist", "assets"))

wsgi_resource = wsgi.WSGIResource(reactor, reactor.getThreadPool(), application)
root_resource = Resource()
api_resource = wsgi_resource

class CustomOpenSSLContextFactory(DefaultOpenSSLContextFactory):
    def getContext(self, hostname=None, port=None):
        context = super().getContext()
        cipher_string = "!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK"
        context.set_cipher_list(cipher_string.encode("utf-8"))
        return context


root_resource.putChild(b"", File(REACT_APP))
root_resource.putChild(b"api", api_resource)
root_resource.putChild(b"/assets", File(REACT_APP_STATIC))
site = server.Site(root_resource)

reactor.listenSSL(8443, site, CustomOpenSSLContextFactory(key_file, cert_file))


```
I have a cert and the site works but it does not load any of the files in /assets 
and if i remote 'index.html' from REACT_APP location path, even that does not work, i get no resource found 

I went through the docs and found 

```
resource = File(REACT_APP_STATIC )
factory = Site(resource)
reactor.listenTCP(8888, factory)
reactor.run()

```
This example works but I need to add wsgi app to it

What i am trying is to start a SPA index.html (React - app) front page with Django backend

What did you do to get it to happen?
Just tried to run the above code

Does it happen every time you follow these steps, sometimes, or only one time?
It happens every single time

**Comment by glyph** [comment]
HI @KaviHarjani !

Thanks for reporting the issue. Unfortunately as stated, it's impossible to say what's going on here.  It's not clear if there is a Twisted bug here, or if your files are laid out in the wrong way.

If you could please include a minimal, runnable example that demonstrates the issue (including, for example, all necessary import statements, and a few files arranged in a way that should be served) then we would be happy to take a look at it.
