### ISSUE TITLE
Add sibling of TestCase.addCleanup that runs registered callbacks after tearDown()

### ISSUE THREAD

**Issue by p12tic** [twisted/twisted#12387]
Currently Twisted unit tests have the following flow:

 - `setUp` function
 - test function
 - any callbacks registered via `addCleanup`
 - `tearDown` function

This offers limited possibilities to automatically clean up resources. Specifically, it is not possible to make any part of resource cleanup to happen after `tearDown`. This is unfortunate, because the resources may be allocated deep inside some call chain started within `setUp` or test function. In such situation the developer would be out of luck if the resources need to be cleaned up after `tearDown`. The only solution would be not to use `addCleanup`.

However, even more unfortunate is that `addCleanup` is in fact really useful. It guarantees that the cleanup function is called regardless of whether previous cleanup functions failed, or whatever happened in the rest of the test. It is cumbersome to reimplement addCleanup-after-tearDown without help from the test framework. Not only the developer would need to ensure that each test that does resource allocation has paired cleanup at the end of `tearDown`, but also there would need to be at least one `try ... finally` to ensure it actually is guaranteed to run. If there are multiple cleanup functions, the developer will need to add multiple `try ... except` blocks to any code that may fail:

```
try:
    await myCleanup1()
except BaseException as e:
    log.err(e, 'while cleaning up the test')
try:
    await myCleanup2()
except BaseException as e:
    log.err(e, 'while cleaning up the test')
...
```

Given the above, it likely makes sense to provide this functionality as part of Twisted.

Proposed solution is to add `addDelayedCleanup` function that works exactly like `addCleanup`, but runs the callbacks after `tearDown` has completed. That is, the proposed test flow is as follows:

 - `setUp` function
 - test function
 - any callbacks registered via `addCleanup`
 - `tearDown` function
 - any callbacks registered via `addDelayedCleanup`

Some preparatory refactoring has already been done in https://github.com/twisted/twisted/pull/12375.

**Comment by adiroiban** [comment]
Hi. Thanks for the feedback.

I don't think I understand the need for this method.

When writing tests I am trying to avoid using setup and teardown and just use `addCleanup`.
This includes using `addCleanup` for any resource that is created inside `setUp`.
The cleanup for the resource createed inside setup will be called after any other cleanup added by the test method.

----------

I am using setup and teardown only when I need to create a reusable TestCase class.
For example, one that will start a docker container at the start of all tests and will close it at the end of all tests.

Can you give an example when such a method is needed?

Thanks

**Comment by p12tic** [comment]
>  I am using setup and teardown only when I need to create a reusable TestCase class.
> For example, one that will start a docker container at the start of all tests and will close it at the end of all tests.

Consider the case where this reusable test case requires some XYZ setup before starting the docker container and needs some additional cleanup after they are cleaned up. That is, the flow is:

```
setup xyz
setup docker
...
teardown docker
teardown xyz
```

 `addCleanup` cannot be used for this flow and thus XYZ setup must have `setUpXYZ` and `tearDownXYZ` methods that would be called from `setUp` and `tearDown`. If XYZ setup is something that is also widely used across the codebase, that forces all tests using XYZ to have `tearDown` even if they aren't using docker.

What's worse, this limitation forces all other setup that need to happen before XYZ to also be written using `setUp***` and `tearDown***` style. Basically, once test code hits such limitation, it forces half of the codebase away from `addCleanup`.

This is exactly what happened in Buildbot project. Right now there's a bad hack to avoid hundreds of additional `tearDown` methods. It would be great if the hack could be avoided and `addDelayedCleanup` be used instead.

**Comment by exarkun** [comment]
Don't you get the desired  behavior if you do all of your cleanup with `addCleanup` instead of doing some with `tearDown` and some with `addCleanup`?

**Comment by adiroiban** [comment]
> For example, one that will start a docker container at the start of all tests and will close it at the end of all tests.

There was an error there. I am using `setUpClass + tearDownClass` for docker containers... as in order to speed up the tests, all tests are sharing the same container


Most of my recent code only uses setUp together with `addCleanup()`

So it will look like this

```
setup xyz  + addCleanup(xyz)
setup docker + addCleanup(docker)
test_something()

```

**Comment by p12tic** [comment]
Ok, sounds good. Though I don't understand why there's so much aversion to adding such small helpers. It's 5 lines + tests + documentation change for Twisted to save a few hundreds lines of refactoring for the users.

**Comment by glyph** [comment]
> Though I don't understand why there's so much aversion to adding such small helpers. It's 5 lines + tests + documentation change for Twisted to save a few hundreds lines of refactoring for the users.

Multiply this out by one change like this a month for 20 years and you have a pile of absolutely incomprehensible massive API surface. Which we have experienced a subset of, and it's not fun :). In isolation, the pushback against individual features might seem excessive, but systemically it is necessary. See for example https://alexgaynor.net/2020/nov/30/why-software-ends-up-complex/

**Comment by p12tic** [comment]
Interestingly standard python library runs `addCleanup` callbacks after the `tearDown` method. So Twisted running them before without a way to run them after introduces an incompatibility that makes it impossible to directly rewrite `unittest.TestCase` tests to ones using trial `TestCase` in certain cases.

**Comment by adiroiban** [comment]
> Interestingly standard python library runs addCleanup callbacks after the tearDown method. 

Thanks for the info.

Yep... unfortunately.

Code is here.

https://github.com/python/cpython/blob/5ace71713b03cb37d829f50c849a8bb8a518738d/Lib/unittest/case.py#L655-L665

My hope was that `_callTearDown` will also call `doCleanups`

--------

I don't know what we can do here.

The Twisted TestCase should continue to work as it is.

We might want to introduce a CompatTestCase with the goal of matching the stdlib behaviour... but I don't know if people will start using it... it will be confusing to select between these 2.

Another option is to add a class member for Twisted TestCase that will trigger the stdlib behaviour and will call cleanups after teardown

**Comment by exarkun** [comment]
It has never been promised feature or a design goal of trial to have exact feature equivalence with the stdlib unittest.  There are loose _compatibility_ goals - it's nice if trial can _run_ stdlib TestSuites - but that doesn't mean a trial TestSuite must be identical to a stdlib TestSuite.

It doesn't really make sense to try to make them identical, either.  If someone wants to use stdlib features, they can write a stdlib TestSuite.  There also isn't just one version of stdlib TestSuite and it would be a significant maintenance burden for Twisted to try to provide identical behavior to every version of the stdlib that ships with a supported version of CPython, nor would this be very useful to application developers since it would create more variation for them to account for in their code, not less.
