### ISSUE TITLE
Functions added via addCleanup ignore the test timeout

### ISSUE THREAD

**Issue by p12tic** [twisted/twisted#12390]
**Describe the incorrect behavior you saw**
Functions added via addCleanup ignore the test timeout. This makes it possible for the test to hang even if reasonable timeout is configured and as a result test case timeouts are not completely reliable.

**Comment by glyph** [comment]
Thanks for all this attention to detail and maintenance! I am sure it was frustrating to get pushback on some of your implemented feature requests, so your continued diligence is much appreciated ;)
