### ISSUE TITLE
xpath.queryForString fails on unicode XML

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2490]
|<img alt="akrherz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| akrherz reported|
|-|-|
|Trac ID|trac#2490|
|Type|enhancement|
|Created|2007-02-26 20:00:15Z|

I'm getting this traceback:

```
File "./bot-twisted.py", line 133, in processMessage
    bstring = xpath.queryForString('/message/body', elem)
  File "/usr/lib/python2.3/site-packages/twisted/words/xish/xpath.py", line 275, in queryForString
    return internQuery(xpathstr).queryForString(elem)
  File "/usr/lib/python2.3/site-packages/twisted/words/xish/xpath.py", line 242, in queryForString
    self.baseLocation.queryForString(elem, result)
  File "/usr/lib/python2.3/site-packages/twisted/words/xish/xpath.py", line 115, in queryForString
    self.childLocation.queryForString(c, resultbuf)
  File "/usr/lib/python2.3/site-packages/twisted/words/xish/xpath.py", line 117, in queryForString
    resultbuf.write(str(elem))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 177: ordinal not in range(128)
```

I'm using Twisted 2.5.0 (TwistedWords-0.5.0).  thanks!

Attachments:

* [test_xpath_unicode.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f79/f7918d1eeff9bb2dc6ee29dbfe1945b155ebe075/03c3a0374da1a4bfff3930873257f98c50002040.py) (649 bytes) - added by j2a on 2007-02-28 17:04:46Z - unit-test, tests unicode in content and path
* [xpath.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f79/f7918d1eeff9bb2dc6ee29dbfe1945b155ebe075/efc5fdedf28579ecbb1e87dc1a4d58e7d24be135.diff) (1656 bytes) - added by j2a on 2007-02-28 17:05:36Z - quick&dirty patch for bug #2490

<details><summary>Searchable metadata</summary>

```
trac-id__2490 2490
type__enhancement enhancement
reporter__akrherz akrherz
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__words words
keywords__unicode_xpath unicode xpath
time__1172520015000000 1172520015000000
changetime__1464115725180759 1464115725180759
version__None None
owner__ 
cc__ralphm
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="j2a's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|j2a commented|
|-|-|

I'm getting this bug too.

**Comment by twisted-trac** [comment]
|<img alt="akrherz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|akrherz commented|
|-|-|

thanks j2a, this patch seems to be working for me :)

**Comment by twisted-trac** [comment]
|<img alt="akrherz's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|akrherz commented|
|-|-|

Any updates on fixing this bug for the next twisted release?  thanks!

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve commented|
|-|-|

xpathparser.py must not be modified, xpathparser.g should be instead. Also, the provided patch only fixes one of the tests for me.

I have no idea if the approach is correct or not.

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_8"></a>|@ralphm commented|
|-|-|

As therve said, this would require changing the `xpathparser.g` file from which `xpathparser.py` is generated. However, YAPPS 2 does not support unicode in its scanner, so we would need to find a way around that. A possibility might be patching the scanner class later on in the file.

Since PyXML also uses YAPPS for parsing XPath queries, we might learn from that. They couldn't use the generated Scanner as-is, either, by the way.

**Comment by twisted-trac** [comment]
|<img alt="powdahound's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|powdahound commented|
|-|-|

I noticed that another (ghetto) workaround for this is to call `xpath.queryForStringList('/message/body', stanza)[0]` since that flow never casts the data using str().

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_11"></a>|@ralphm commented|
|-|-|

In changeset 5980a7b2fea507582c6f46de920e7aa2177ceb0f
```
#!CommitTicketReference repository="" revision="5980a7b2fea507582c6f46de920e7aa2177ceb0f"
Resolve str/unicode ambiguities, add tests, exceptions on syntax errors.

This also addresses #2490 for the cases where non-ascii code points are
used in string literals with attribute or function matches. Matching
element names that are non-ascii still isn't supported.
```

**Comment by twisted-trac** [comment]
|[<img alt="ralphm's avatar" src="https://avatars.githubusercontent.com/u/116741?s=50" width="50" height="50">](https://github.com/ralphm)<a name="note_12"></a>|@ralphm commented|
|-|-|

In changeset 3c7ef0728e48d9bf638d8b49e886d72fb984ed8c
```
#!CommitTicketReference repository="" revision="3c7ef0728e48d9bf638d8b49e886d72fb984ed8c"
Resolve str/unicode ambiguities, add tests, exceptions on syntax errors.

This also addresses #2490 for the cases where non-ascii code points are
used in string literals with attribute or function matches. Matching
element names that are non-ascii still isn't supported.
```

**Comment by akrherz** [comment]
I believe this issue was fixed somewhere around Twisted 16

**Comment by adiroiban** [comment]
Thanks. 

I see https://github.com/twisted/twisted/commit/3c7ef0728e48d9bf638d8b49e886d72fb984ed8c as being part of 16.4.1

So yes. I think this is closed.
