### ISSUE TITLE
Trial's --until-failure feature is fragile and under-tested

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2786]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#2786|
|Type|enhancement|
|Created|2007-08-15 00:34:51Z|

More than once now, a change to Trial has broken the `--until-failure` option. Only vigilance is keeping it working. This is terrible.

I propose that either:
 1. We remove the feature, and replace it with a wrapper around `trial` that checks for application return code.
 1. We figure out an effective testing strategy for `--until-failure`
 1. We do both of these.

<details><summary>Searchable metadata</summary>

```
trac-id__2786 2786
type__enhancement enhancement
reporter__jml jml
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__reopened reopened
resolution__ 
component__trial trial
keywords__ 
time__1187138091000000 1187138091000000
changetime__1187242074000000 1187242074000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

I think that option 1 is a bad idea, unless you're talking about optionally.  The primary use-case I have for --until-failure is detecting invalid mutation of global state; destroying the whole process would make it impossible to detect this.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_2"></a>|@jml commented|
|-|-|

I meant "make a new wrapper script and get rid of until failure". You are right though, that is an important use case.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

This isn't really a ticket.  It's too bad trac doesn't have something which this could be one of.

Once this discussion is done, I hope either this ticket's details will be edited to make it clear what the specific problem which is being resolved is or it will be closed and some other ticket(s) created.

One such ticket could be "provide complete line coverage of code in support of the --until-failure command line option", for example.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_4"></a>|@jml set status to `closed`|
|-|-|

Whatever.

I'll just keep a list of the problems that I encounter while working on Trial in some personal, local tracker where I don't have to quibble over what is and isn't a ticket.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

I'm sorry the input I provided was not productive.  My goal was only to try to bring focus to whatever efforts are going to be put into improving Twisted.  I don't want to fight about this.  If you want, just look at my comment as friendly advice and disregard it if you like.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_6"></a>|@jml commented|
|-|-|

I'm sorry for going off in a huff with this ticket, and am glad of your kind response. 

I also don't want to fight about this. However, I think that there's an actual project management issue here that needs to be figured out.

I will try to collect my thoughts when I am more calm.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph set status to `reopened`|
|-|-|

Counterpoint: this _is_ really a ticket, but could perhaps use some additional metadata to indicate that it is still in the requirements gathering or discussion phase.  However, such additional metadata is really a fairly sophisticated nuance of issue tracking and is unlikely to be of much use until we have a much better tracker.

Things which are yet to be done are, in my mind, tickets, even if the idea about what needs to be done is vague, and the first task involved is to refine the idea to where it is useful.  It's fine if the refinement ends up being "Oh, I guess not, then."  (However, I reserve the right to close tickets which have been open for more than a month and are too vague to be actionable by anyone but their owner).

More to the point of the ticket itself, I don't see any reason why this should remain closed: the issue it describes is real, and we should continue to talk about and fix it.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_8"></a>|@jml commented|
|-|-|

Perhaps more important than what needs to be done is how we know when it's done.

Anyway.

What I'd like to see here is:
 * A set of tests that should pass for any runner.
 * A set of tests specifically for --until-failure.

Leaving the term 'runner' deliberately vague, at least for this post.

Actually, let's not.

I suspect that a large part of the problem is that there's no clear API / object / concept (I hate it when I sound like this!) for a test runner. There are other tickets that reflect this.

This ticket was triggered by [#2275](https://github.com/twisted/twisted/issues/2275).

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this can be closed.

I have used `--until-failure` and it was working fine.
It now works even with parallel jobs.

Feel free to reopen if you think that `--until-failure` is broken.

But I think this ticket should include more detail about what is broken for `--until-failure` and how to reproduce the error.

**Comment by adiroiban** [comment]
I now realized that GitHub will not trigger the notifications... so @jml and @glyph see my previous comment.

Thanks!

**Comment by glyph** [comment]
> Feel free to reopen if you think that `--until-failure` is broken.

I would add that if it's under-tested and someone just wants to fix the coverage gap, that would also be great. But we can open a more specific coverage ticket if someone has actual plans to move forward with that.  But we can always reopen, so I am just closing.
