### ISSUE TITLE
Link to howto's from API reference docs.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2801]
|<img alt="mellis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| mellis reported|
|-|-|
|Trac ID|trac#2801|
|Type|enhancement|
|Created|2007-08-24 13:51:38Z|

It would be nice to point people from the API docs for a module to the howto describing its usage.  One reason is that sometimes a Google search will turn up the former and not the latter.  Another is that because of ticket [#11367](https://github.com/twisted/twisted/issues/11367), sometimes fundamental parts of a module are not described in the API docs (e.g. twisted.python.log.msg) but do appear in the howto.  Finally, in some cases the howto documents behavior that is not described in the API docs.  

<details><summary>Searchable metadata</summary>

```
trac-id__2801 2801
type__enhancement enhancement
reporter__mellis mellis
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__lore lore
keywords__documentation documentation
time__1187963498000000 1187963498000000
changetime__1389979824000000 1389979824000000
version__None None
owner__ 
cc__thijs cc__exarkun cc__mwhudson cc__khorn
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_1"></a>|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `assigned`|
|-|-|

I agree. But where to start ;) twisted.web?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_2"></a>|@thijstriemstra removed owner<br>@thijstriemstra set status to `new`|
|-|-|

Putting it up for review to check with the other developers if this is actually a good idea.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun set owner to @thijstriemstra|
|-|-|

Yea, this is a good idea.  Links are great.

How do we actually implement this, though?  I hope we can do something better than stuffing entire URLs into lots of module docstring.  Should we have some epytext-ish markup for pointing to howtos?  And what about examples?  It'd be great to link to those as well.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

One day, one glorious day, we might actually distribute some documentation that users download, rather than just browse on the website.  The links from their local Lore documentation should refer to their local API documentation.  I think the main reason that stuffing entire URLs into module docstrings is bad is that it breaks this.

Having specific markup for "here's a link to some lore documentation" would be unfortunate, because it would be one more thing for documentors to learn aside from "we use epytext".  I don't think we need actually need new markup for this, though.  What we want are relative hyperlinks.

We should established the convention that the directory structure of the generated documentation on the website, the generated documentation in the download tarball, and the source documentation in SVN are all the same.  This precludes the possibility of distributing project-specific documentation, but given that we are probably going to want lots of cross-project links, maybe that's a good idea anyway.

When we generate the API documentation, we should put the result in the `api` subdirectory of the `doc` directory (or its generated equivalent).

Now, due to a happy accident of the way that pydoctor arranges its output, all we need is for it to honor a directive that looks like this, which is already part of the epydoc syntax:
```
#!py
"""
You should really read about U{../core/howto/defer.html<Deferreds>}.
"""
```
If the output arrangement of one of these tools were to change somehow, it could be modified to recognize relative links rather than rendering them literally.

Unfortunately epytext has two bugs which prevent us from doing this immediately.  I say "epytext" and not "pydoctor" because epydoc seems to do the same thing:

  1. It ignores the bit in angle-brackets, so you end up seeing the ugly, raw hyperlink.
  2. It decides all hyperlinks are, unless otherwise specified, `http` links, so it renders that link as `http://../core/howto/defer.html`.

I'm open to other suggestions.  Maybe there should be different markup for relative hyperlinks.  I mostly wanted to clarify the motivation.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

I think you got the angle bracket part backwards.  Did you mean `U{Deferreds<../core/howto/defer.html>}`?  That should render as [../core/howto/defer.html Deferreds].

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

Replying to [glyph](#note_4):
> Unfortunately epytext has two bugs which prevent us from doing this immediately.  I say "epytext" and not "pydoctor" because epydoc seems to do the same thing:
>
>   1. It ignores the bit in angle-brackets, so you end up seeing the ugly, raw hyperlink.
>   2. It decides all hyperlinks are, unless otherwise specified, `http` links, so it renders that link as `http://../core/howto/defer.html`.
>
> I'm open to other suggestions.  Maybe there should be different markup for relative hyperlinks.  I mostly wanted to clarify the motivation.

Yeah, ```U{Deferreds<../core/howto/defer.html>```} is the correct syntax. So do we want to go with that? I'd rather not start working on it before I'm absolutely sure you guys want this, otherwise I'll be creating a useless branch..

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

I would postpone any work on this until the website re-arrangement Glyph talked about is actually done.  Either that, or implement something that includes a way to map one URL hierarchy onto another.  Until that happens, any changes made to resolve this ticket in the "right" way will just result in broken links.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_8"></a>|@thijstriemstra commented|
|-|-|

Going to put this in the Lore category with an eye on the proposed plan to switch to sphinx.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_11"></a>|@khorn commented|
|-|-|

Lore is no longer being used for Twisted documentation, and is being deprecated, prior to eventual removal, per [#6907](https://github.com/twisted/twisted/issues/6907).

However, this is not really a Lore ticket, so I am leaving it open, as it still seems desirable to have this functionality (someday).

**Comment by adiroiban** [comment]
I think that this should be already solved via intershinx links 

pydoctor supports intersphinx links 

https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

----------

So if anything is missing, it should be fixed in pydoctor.

I have created a pydoctor issue here https://github.com/twisted/pydoctor/issues/609


Closing this.
