### ISSUE TITLE
Automate uploading release tarballs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2888]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#2888|
|Type|enhancement|
|Created|2007-11-12 20:02:52Z|

Do this please.

<details><summary>Searchable metadata</summary>

```
trac-id__2888 2888
type__enhancement enhancement
reporter__radix radix
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1194897772000000 1194897772000000
changetime__1448145196807076 1448145196807076
version__None None
owner__ 
cc__therve cc__michael@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_2"></a>|@therve commented|
|-|-|

Do you know how to make the upload? Is it ssh, sftp, ftp?

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_3"></a>|@radix commented|
|-|-|

Actually, we only have to get the files to cube. There's a cronjob that runs to rsync the files from cube to the mirrors. So we can sftp them to cube.

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_5"></a>|@radix commented|
|-|-|

I should mention that TMRC isn't really important here; the important thing is to automate the uploading of the tarballs to *somewhere* publicly accessible. This is an important distinction because there are [other file services with easy-to-use APIs](http://news.launchpad.net/api/recipe-for-uploading-files-via-the-api) which we could use for file hosting.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_6"></a>|@jml commented|
|-|-|

FWIW, automatically uploading the tarballs to cube right now involves uploading to `cube:/srv/www-data/twisted/Releases/<Project>/<First two parts of version number>/*`. The directories need to be created, and the permissions need to be set correctly.

New directories are 2775, and ought to be in the www-data group. New files are 664, and ought to be in the www-data group.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_7"></a>|@jml commented|
|-|-|

We might also want to automate signing the tarballs / msis and uploading the signatures.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_10"></a>|@tomprince commented|
|-|-|

There is some code in [braid](http://git.io/z2ZuvQ) to do this. I'm not sure how this should be integrated.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_11"></a>|@exarkun commented|
|-|-|

It seems like this should build on the work done for [#4353](https://github.com/twisted/twisted/issues/4353).  Using one tool to upload pre-release packages and another tool to upload release packages doesn't seem like a good goal to aim for.

**Comment by adiroiban** [comment]
We no longer have tarball on own site.

I think that this is now done via pypy via GitHub Action.

i think that this can be closed as it is now fixed
