### ISSUE TITLE
Automate updating the API docs on the twistedmatrix web site

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2891]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#2891|
|Type|enhancement|
|Created|2007-11-12 20:05:18Z|

This also involves unix commands. (Jp: "Not that hard")

<details><summary>Searchable metadata</summary>

```
trac-id__2891 2891
type__enhancement enhancement
reporter__radix radix
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__assigned assigned
resolution__None None
component__release_management release management
keywords__ 
time__1194897918000000 1194897918000000
changetime__1448145941065125 1448145941065125
version__None None
owner__ 
cc__thijs cc__michael@...
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix set owner to @radix<br>@radix set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

[#4354](https://github.com/twisted/twisted/issues/4354) was a duplicate of this.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
This is now done via Read The Docs.

pydoctor has a sphinx extension that will trigger the apidocs generation via standard sphinx build process.

Read the docs triggers the standard sphinx build process and publishes the HTML files.
