### ISSUE TITLE
Holistic release automation tool

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2892]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)| @radix reported|
|-|-|
|Trac ID|trac#2892|
|Type|enhancement|
|Created|2007-11-12 20:06:35Z|

We need a single button that can do the entire release from building to publishing to announcing.

<details><summary>Searchable metadata</summary>

```
trac-id__2892 2892
type__enhancement enhancement
reporter__radix radix
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1194897995000000 1194897995000000
changetime__1258563640000000 1258563640000000
version__None None
owner__ 
cc__thijs cc__khorn
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?s=50" width="50" height="50">](https://github.com/zooko)<a name="note_2"></a>|@zooko commented|
|-|-|

According to radix (on IRC), this ticket is waiting for the following tickets:

[#2886](https://github.com/twisted/twisted/issues/2886), [#2888](https://github.com/twisted/twisted/issues/2888), [#2889](https://github.com/twisted/twisted/issues/2889), [#2890](https://github.com/twisted/twisted/issues/2890), [#2891](https://github.com/twisted/twisted/issues/2891), [#2925](https://github.com/twisted/twisted/issues/2925)

**Comment by twisted-trac** [comment]
|[<img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?s=50" width="50" height="50">](https://github.com/zooko)<a name="note_3"></a>|@zooko commented|
|-|-|

According to radix (on IRC), the following are not actually part of the twisted-7.0 milestone as far as he is concerned, but he doesn't mind other people putting crap in there as wishful thinking: [#2854](https://github.com/twisted/twisted/issues/2854), [#2307](https://github.com/twisted/twisted/issues/2307)

**Comment by twisted-trac** [comment]
|[<img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?s=50" width="50" height="50">](https://github.com/zooko)<a name="note_4"></a>|@zooko commented|
|-|-|

I guess [#2353](https://github.com/twisted/twisted/issues/2353) -- "Change Twisted "main" release to a time-based version number" -- is relevant.  And how about [#2308](https://github.com/twisted/twisted/issues/2308) -- "Test Twisted's release automation" -- ?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra commented|
|-|-|

Replying to [radix](#2892):
> We need a single button that can do the entire release from building to publishing to announcing.

I'll start working on that button :)

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_7"></a>|@khorn commented|
|-|-|

Has anyone here considered using fabric?

[http://fabfile.org]

Its designed to do precisely this kind of thing.

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_9"></a>|@khorn commented|
|-|-|

Paver might also be a useful tool here:

http://www.blueskyonmars.com/projects/paver/

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun commented|
|-|-|

Implicit in this ticket is the requirement for the system to be covered by automated tests to ensure that it continues to work.  Do fabfile or paver offer anything in that area?

**Comment by twisted-trac** [comment]
|[<img alt="khorn's avatar" src="https://avatars.githubusercontent.com/u/815352?s=50" width="50" height="50">](https://github.com/khorn)<a name="note_11"></a>|@khorn commented|
|-|-|

I'm not aware of anything specific provided by these tools, but as both of them use regular python files to define their "tasks", I would presume you could use standard unit-testing techniques (unittest/trial) to test them.  I haven't done anything like this, but I don't see any obvious reason why you couldn't do it.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this is already done via GitHub Actions and Read The docs

https://github.com/twisted/twisted/blob/67612689e58fc33cf8db1664ea2bfeeff1a5117f/.github/workflows/test.yaml#L229-L233
