### ISSUE TITLE
"./setup.py install --prefix=relative/path" behaves surprisingly

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#2907]
|[<img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?s=50" width="50" height="50">](https://github.com/zooko)| @zooko reported|
|-|-|
|Trac ID|trac#2907|
|Type|enhancement|
|Created|2007-11-16 23:21:31Z|

I was explaining to a user how to install Twisted on a machine where he doesn't have root.  I wrote a note telling him to install with "--prefix", and then fortunately I tested that myself before sending the note.  After the somewhat surprising results of my test I added a comment in the instructions that he must use an absolute path:

http://allmydata.org/pipermail/tahoe-dev/2007-November/000248.html

<details><summary>Searchable metadata</summary>

```
trac-id__2907 2907
type__enhancement enhancement
reporter__zooko zooko
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1195255291000000 1195255291000000
changetime__1195255656000000 1195255656000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?s=50" width="50" height="50">](https://github.com/zooko)<a name="note_1"></a>|@zooko commented|
|-|-|

Maybe I should go ahead and explain what is surprising instead of assuming that everyone knows what it does and that everyone knows what I expected.

What it does is install into the relative path under each subproject, so for example if I run ```./setup.py install --prefix=instdir```, I get:

```
TwistedConch-0.8.0/instdir  TwistedMail-0.4.0/instdir   TwistedRunner-0.2.0/instdir
TwistedCore-2.5.0/instdir   TwistedNames-0.4.0/instdir  TwistedWeb-0.7.0/instdir
TwistedLore-0.3.0/instdir   TwistedNews-0.3.0/instdir   TwistedWords-0.5.0/instdir
```

What I expected was that it would install into the relative path from the current working directory, as in ```./instdir```.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this can be closed as we no longer use setup.py install
