### ISSUE TITLE
Set version information in new deprecations to the version number actually associated with a release

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3040]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3040|
|Type|enhancement|
|Created|2008-02-18 16:42:36Z|

Some APIs (eg `twisted.python.deprecate.deprecated`) accept version information.  This information can't be known for sure until a release is actually done (eg, a lot of deprecations, though they mostly don't use the API mentioned above, talk about Twisted 2.6, which presumably will not be the next version of Twisted).  We should represent "the next version of Twisted" symbolically and part of the release process should be to replace this with an actual value.

Here's one humble suggestion:

  * `twisted.something` is a `Version` instance set to a reasonable guess for the next Twisted release.  Any new deprecations import and use it.
  * When a release is about to happen, all imports of `twisted.something` are replaced with imports of `twisted.somethingElse`.  `twisted.somethingElse` is the Version number which is actually associated with the release.
  * `twisted.something` is updated to give a reasonable guess for the _next_ Twisted release.

This way, it's always the same to deprecate an API (and particularly, it doesn't require much thinking about releases and such).  It also gives deprecations a uniformity which should make the release update job straightforward.

<details><summary>Searchable metadata</summary>

```
trac-id__3040 3040
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1203352956000000 1203352956000000
changetime__1242411917000000 1242411917000000
version__None None
owner__ 
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

(In [22677]) Merge deprecated-enterprise-3022

Author: exarkun
Reviewer: therve, dreid
Fixes [#3022](https://github.com/twisted/twisted/issues/3022)
Refs [#3040](https://github.com/twisted/twisted/issues/3040)

Deprecate twisted.enterprise.util and everything in it.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

Also see [#3838](https://github.com/twisted/twisted/issues/3838) where a 8.2 vs 9.0 trunk issue is described.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this is now fixed via the "NEXT" placeholder implemented by `versioneer`
