### ISSUE TITLE
add support for twisted.python.deprecate's docstring manipulation to pydoctor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3048]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#3048|
|Type|enhancement|
|Created|2008-02-21 17:19:56Z|

`twisted.python.deprecate` rewrites docstrings to include deprecation information.

It would be excellent if pydoctor supported this in some way, either by reflecting the modified docstring in its output or by marking up the output to indicate the deprecation in some other way.

Since the decorator is in use already, it would be nice for this to be done for the next release, so the generated documentation reflects these new deprecations.

<details><summary>Searchable metadata</summary>

```
trac-id__3048 3048
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__ 
branch_author__ 
status__new new
resolution__None None
component__pydoctor pydoctor
keywords__ 
time__1203614396000000 1203614396000000
changetime__1249585116000000 1249585116000000
version__None None
owner__ 
cc__therve
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

I hacked some stuff in http://bazaar.launchpad.net/~therve/pydoctor/handle-deprecated. It's not very clean, but it did the job. I use the livecheck option, but instead of loading every module, it loads only the modules flagged by hand. I flagged the module where I detected a ```name = func(name)``` at module level (which is approximately what we do with deprecated decorator).

Michael, can you have a look? I can work on this more if you have some pointers.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Hm.

Pydoctor should really use launchpad for issue tracking.  I'm tempted to close this as invalid.  However, this code is all intimately Twisted specific, is it not?  Does it really belong in pydoctor?  Should it instead be in Twisted and loaded by pydoctor via some extension mechanism?

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this should be tracked in pydoctor.

There is already a PR that was merged https://github.com/twisted/pydoctor/pull/554

And this issue https://github.com/twisted/pydoctor/issues/319

---------

I don't think there is anything else we should do for twisted/twisted

Once the feature is ready we should upgrade to pydoctor.

I am closing this.
