### ISSUE TITLE
Move release related code outside of the twisted package

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3138]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)| @therve reported|
|-|-|
|Trac ID|trac#3138|
|Type|enhancement|
|Created|2008-03-29 18:51:50Z|

I don't think it should be in there. We can at least easily move _release.py and the related tests in a top package. We must add a buildbot that also runs these tests though.

<details><summary>Searchable metadata</summary>

```
trac-id__3138 3138
type__enhancement enhancement
reporter__therve therve
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1206816710000000 1206816710000000
changetime__1224447313000000 1224447313000000
version__None None
owner__ 
cc__glyph cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_1"></a>|@glyph commented|
|-|-|

In my opinion this does nothing but create an operational hassle (adjusting the buildbots, adjusting each developer's checkout to remember to run the 'release' tests as well, etc).

What problem is this ticket trying to solve?  If it's that _release is private and shouldn't be released, or that the code is not related to the rest of twisted.python, perhaps we can have a private twisted._release package - after all, we already have packages excluded from the release.

(If it's something else then please elaborate, but I still have a hunch this is going to create more problems than it solves.)

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_3"></a>|@therve commented|
|-|-|

My main concern with this code is the direct call to the latex command line. This makes it a functional test, and it appears it doesn't work everywhere: http://www.python.org/dev/buildbot/community/trunk/x86%20Red%20Hat%209%20trunk/builds/1933/step-Twisted.zope.dev/0

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph commented|
|-|-|

Wouldn't it be better to make this test optional, depending on the presence of an appropriate latex setup?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Good luck figuring out if a particular latex setup is appropriate or not. :)

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve commented|
|-|-|

I agree with exarkun. Also, I think we want to remove all the 'skip' in these tests, to be sure that the tests are always run. We want a stable slave with pydoctor (with correct version), latex, etc... that doesn't silently skip the tests.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

I wonder if the idea of "test resources" (is that what they're called?) from the stdlib test runner would help out here at all.

Splitting the release code into a separate package would help avoid failing tests in cases where no one cares about them, but the same problem applies to SSL and SSH.  If you don't have pyOpenSSL, tests should fail.  Unless you somehow say you really don't care about SSL.  Or maybe it's actually not a similar case.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_8"></a>|@therve commented|
|-|-|

I think that's a fairly similar case. I don't know if the skip solution is more elegant or not. The problem with it is that we don't monitor the numbers of skips, ie we don't have "unexpected skips".

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_9"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_7):
> I wonder if the idea of "test resources" (is that what they're called?) from the stdlib test runner would help out here at all.

I have no idea what these are.

> Splitting the release code into a separate package would help avoid failing tests in cases where no one cares about them, but the same problem applies to SSL and SSH.  If you don't have pyOpenSSL, tests should fail.  Unless you somehow say you really don't care about SSL.  Or maybe it's actually not a similar case.

I think this is definitely a similar (the same) case.  It's just more obvious here that the user has to make a decision because we can't simply look to see whether an import fails or not :).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

Also, the idea of making an explicit decision to avoid "unexpected skips" is a _great_ idea.  +1.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_11"></a>|@thijstriemstra commented|
|-|-|

The release related code was removed from trunk/admin not long ago, so this can be closed?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun commented|
|-|-|

The ticket is about removing `twisted.python._release` and related code, rather than the release code which was in the admin directory.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
The current `_release.py` has 3 parts:

* generate narrative docs - to be removed in https://github.com/twisted/twisted/pull/11576
* generate apidocs - to be removed https://github.com/twisted/twisted/pull/11578
* check for news fragment - to be removed in https://github.com/twisted/twisted/issues/11583

The plan is to replace these custom scripts with direct CLI calls.

I think that this can be closed as we now have separate tickets for removing each part of the release script
