### ISSUE TITLE
HTTPClientFactory should follow relative redirects

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3384]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| adevore reported|
|-|-|
|Trac ID|trac#3384|
|Type|enhancement|
|Created|2008-08-08 07:43:24Z|
|Branch|https://github.com/twisted/twisted/tree/follow-relative-redirects-3384|

Some web applications respond with a faulty Location header that gives only a relative path (spam.html) instead of the full URL (http://www.example.com/eggs/spam.html) that is required by HTTP. Twisted's HTTPClientFactory should follow these redirects.

Attachments:

* [testcase.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/dd8/dd824a3b8c2f738c359558544544bfcbbf88fa9f/e562c77e924a9fe16a4304509f441fd5c98e4341.diff) (2598 bytes) - added by adevore on 2008-08-08 23:01:07Z - 
* [mypatch.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/dd8/dd824a3b8c2f738c359558544544bfcbbf88fa9f/36803a8631e74c9110c89437a88646e3b981123e.diff) (3507 bytes) - added by adevore on 2008-08-09 19:52:21Z - Patch to web/client.py and a unit test case
* [mypatch2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/dd8/dd824a3b8c2f738c359558544544bfcbbf88fa9f/27db3d58ed00f4694b940f4431ce00d489cb59f7.diff) (3699 bytes) - added by adevore on 2008-08-12 18:57:45Z - Patch to web/client.py and a working unit test case
* [relative-redirect.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/dd8/dd824a3b8c2f738c359558544544bfcbbf88fa9f/886eef8407d807377664280e3c38addd4c104e82.diff) (1939 bytes) - added by adevore on 2009-04-20 01:12:30Z - 
* [relative-redirect-2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/dd8/dd824a3b8c2f738c359558544544bfcbbf88fa9f/e8e2cea5680a0ba240d674d88c4f19fd075ce2a3.diff) (2299 bytes) - added by adevore on 2009-04-24 03:34:01Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__3384 3384
type__enhancement enhancement
reporter__adevore adevore
priority__normal normal
milestone__ 
branch__branches_follow_relative_redirects_3384 branches/follow-relative-redirects-3384
branch_author__ 
status__assigned assigned
resolution__None None
component__web web
keywords__httpclient httpclient
time__1218181404000000 1218181404000000
changetime__1354921440000000 1354921440000000
version__None None
owner__rkrzr rkrzr
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set owner to adevore|
|-|-|

Thanks for the patch.  Can you include a unit test for this change as well?

**Comment by twisted-trac** [comment]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|adevore commented|
|-|-|

The current test case may need to be modified to apply to more real world situations.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

There's one significant problem with the `mypatch.diff`, there are four errors in the test suite when it is applied:

```
===============================================================================
[ERROR]: twisted.web.test.test_webclient.WebClientSSLTestCase.test_infiniteRedirection

Traceback (most recent call last):
Failure: twisted.web.error.Error: 404 Not Found
===============================================================================
[ERROR]: twisted.web.test.test_webclient.WebClientSSLTestCase.test_infiniteRedirection

Traceback (most recent call last):
Failure: twisted.web.error.Error: 500 Internal Server Error
===============================================================================
[ERROR]: twisted.web.test.test_webclient.WebClientTestCase.testServerError

Traceback (most recent call last):
Failure: twisted.web.error.Error: 404 Not Found
===============================================================================
[ERROR]: twisted.web.test.test_webclient.WebClientTestCase.testServerError

Traceback (most recent call last):
Failure: twisted.web.error.Error: 500 Internal Server Error
-------------------------------------------------------------------------------
```

A few other lesser problems:
  * `BrokenRedirect` should have at least a class docstring (including documentation for its instance attribute `path`)
  * `testRelativeRedirect` should be named `test_relativeRedirect`
  * `testRelativeRedirect` needs a docstring
  * `testRelativeRedirect` returns a `DeferredList`.  `DeferredList` always fires successfully, regardless of what the `Deferred`s it wraps do.  This means failures in the test will be reported as errors as a consequence of garbage collection instead of due to a failing returned `Deferred`.  You probably want to use `gatherResults` here instead, or split the test into two methods.
  * Instead of defining `_cbRelativeRedirectNoStartingSlash` and the other callback method, you can just add `self.assertEqual` (preferred over the spelling of `self.assertEquals`) as a callback to the `Deferred` you want to check the result of, with `"success"` as an extra callback argument.  This is a bit easier to read since it's shorter and the code is nearer the rest of the `Deferred` setup.

Thanks

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun set owner to adevore|
|-|-|

Thanks.

A couple more comments:

  * `BrokenRedirect` causes `request.finish` to be called twice.  It shouldn't call `request.finish()` itself, it can just return an empty string.
  * The check `if basePath[-1] != '':` isn't tested.  There should be another new test method like the two you already added, but for the case where the resource issuing the redirect is at an URL which ends with /.  This should exercise that check.
  * I think the new code that you added for changing `parsed[2]` is copying a bug which the existing code that changed that already had.  What happens if the resource issuing the redirect is at an URL like `http://foo/bar?baz=quux`?  Since this is a pre-existing and somewhat unrelated problem, it'd probably be best to open a new ticket for this problem (if it's real) and fix it separately from this change.  However, it might be nice to avoid duplicating the bug in this new code.  You could factor two assignments to `parsed[2]` into a single assignment that comes after the if/else suites.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

[#3157](https://github.com/twisted/twisted/issues/3157) was a (very confused) duplicate of this.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

[#3378](https://github.com/twisted/twisted/issues/3378) was a duplicate of this.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

[#3614](https://github.com/twisted/twisted/issues/3614) was a duplicate of this

**Comment by twisted-trac** [comment]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|adevore commented|
|-|-|

I found that the difference is with redirects that are of the form:

original: /subdir/
location: foo.html

instead of the form

/subdir/foo.html

**Comment by twisted-trac** [comment]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|adevore removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_12"></a>|@exarkun set owner to adevore|
|-|-|

Thanks for investigating this and contributing this patch. :)

A couple small comments on the change:

  1. The new test method should have a docstring describing the scenario it is testing and the behavior which it is defining as correct.
  1. I think `handleStatus_301` might be a better place for the new logic:
    1. If `getPage` is called with a relative URI with a relative path, `setURL` will also be called and the new logic invoked.  Apparently this will have no effect (I was surprised to just find out that `urljoin(None, "foo") == "foo"` :/) but I'm not sure whether this is intentional behavior on the part of `urljoin` and whether we can rely on it continuing to behave this way.
    1. Either way, this isn't really the intended effect of the change - it's only intended to handle the redirect case, so putting it into the redirect handling method directly makes more sense to me.

**Comment by twisted-trac** [comment]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|adevore removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_14"></a>|@exarkun commented|
|-|-|

(In [26753]) Branching to 'follow-relative-redirects-3384'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_15"></a>|@exarkun commented|
|-|-|

(In [26754]) Apply relative-redirect-2.diff

refs [#3384](https://github.com/twisted/twisted/issues/3384)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_16"></a>|@exarkun set owner to adevore|
|-|-|

Thanks.  Just one more question.  In the new patch, you added a check for `not host` protecting the join logic.  I can't think of any way for `not host` to be true but `path.startswith('/')` to be false.  If there's such a case, can you add a test for it?

I applied the patch to the branch mentioned above.  If you can provide any subsequent patches against that branch, that'd be great.

**Comment by twisted-trac** [comment]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_17"></a>|adevore commented|
|-|-|

path.startswith('/') is false when the server returns something like "Location: foo.html". In the case of "Location /subdir/foo.html" some logic in getURL already handled the translation.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_18"></a>|@exarkun commented|
|-|-|

Right, but what about the host part?

**Comment by twisted-trac** [comment]
|<img alt="alexis's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_19"></a>|alexis commented|
|-|-|

If host is not "", it means that we have a full URL in the location header (like http://foo.com/bar), so we don't need to modify the url variable.

I've made a similar ticket: [#4380](https://github.com/twisted/twisted/issues/4380)
I think the problem is fixed in the 3384 branch.

**Comment by twisted-trac** [comment]
|<img alt="rkrzr's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_20"></a>|rkrzr commented|
|-|-|

Hi, I just ran into this problem and noticed that this ticket is still open. Could the provided patch be included in the next twisted release? (Or is there anything preventing it from being included?)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_21"></a>|@exarkun commented|
|-|-|

Hi rkrzr.  Thanks for your interest in this ticket.  Please see ReviewProcess for details on how changes get included in a release.

**Comment by twisted-trac** [comment]
|<img alt="adevore's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_22"></a>|adevore commented|
|-|-|

alexis and rkrzr:

The application that I was writing when I ran into this problem is no longer in use. I'm releasing the ticket so that one of you can take it over. You'll be better able to work on it.

**Comment by twisted-trac** [comment]
|<img alt="rkrzr's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|rkrzr set owner to rkrzr<br>rkrzr set status to `assigned`|
|-|-|

**Comment by twm** [comment]
Closing as `HTTPClientFactory` was removed in #10295.
