### ISSUE TITLE
twisted\python\lockfile.py problem on portable Python install

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3868]
|<img alt="JamesB's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| JamesB reported|
|-|-|
|Trac ID|trac#3868|
|Type|defect|
|Created|2009-06-05 01:15:19Z|

I'm running Python from a USB key, and as a result Pywin32 has never been formally installed.

Regular Python doesn't seem to have a problem, but Pywin32 fails with
```
from win32api import OpenProcess
```
Now, why this pertains to Twisted -- I found a workaround [here](http://groups.google.com/group/movpy/browse_thread/thread/4186e56692014bed?pli=1).

```
    _windows = True
    from win32api import OpenProcess
    import pywintypes
```
becomes
```
    _windows = True
    import pywintypes
    from win32api import OpenProcess
```

Fixes it. Weird.

<details><summary>Searchable metadata</summary>

```
trac-id__3868 3868
type__defect defect
reporter__JamesB JamesB
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__win32 win32
time__1244164519000000 1244164519000000
changetime__1313178154000000 1313178154000000
version__None None
owner__JamesB JamesB
cc__exarkun cc__adiroiban cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set owner to JamesB|
|-|-|

Can you explain how it fails?  You only explained which import statement fails (and not even which file it's in).  What is the failure?  And how can we reproduce this?

**Comment by twisted-trac** [comment]
|<img alt="JamesB's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|JamesB commented|
|-|-|

Sure. Here is the complete failure:

```
Traceback (most recent call last):
  File "H:\Servers\Python\auth.py", line 1, in <module>
    from twisted.application import internet, service
  File "H:\Python26\lib\site-packages\twisted\application\internet.py", line 36, in <module>
    from twisted.application import service
  File "H:\Python26\lib\site-packages\twisted\application\service.py", line 21, in <module>
    from twisted.internet import defer
  File "H:\Python26\lib\site-packages\twisted\internet\defer.py", line 17, in <module>
    from twisted.python import log, failure, lockfile
  File "H:\Python26\lib\site-packages\twisted\python\lockfile.py", line 28, in <module>
    from win32api import OpenProcess
ImportError: DLL load failed: The specified module could not be found.
```

The import is in lockfile.py. It does not fail if you reverse the order of the imports (pywintypes before win32api works fine). The URL I linked to shows someone else with the exact same problem -- and also while using 'portable apps' -- presumably meaning this problem only occurs if Pywin has not been formally installed on the PC. Instead of an installation, I have python26.dll, pywintypes26.dll and pythoncom26.dll in my USB key's \Python26 directory. Key thing: Python is *not formally installed* -- none of these are in this system's \Windows\System32 directory. Pywin can handle this, but only if pywintypes is imported before win32api first.

It would be handy if this were fixed in the default Twisted, because it would guarantee operation for someone just zipping their Python installation and moving it from PC to PC. Definitely would be an easier way to package up a server, in addition to my USB key dev environment. :)

**Comment by twisted-trac** [comment]
|<img alt="JamesB's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|JamesB commented|
|-|-|

Also [here](http://dev.plone.org/archetypes/changeset/6690), as linked from my above link. Importing pywintypes before the other parts of Pywin fixes. :)

**Comment by twisted-trac** [comment]
|<img alt="seocam's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|seocam commented|
|-|-|

```
Traceback (most recent call last):
  File "scannerServer.py", line 6, in <module>
    from twisted.internet import reactor, protocol
  File "P:\PortablePython\twisted\internet\reactor.py", line 37, in <module>
    from twisted.internet import selectreactor
  File "P:\PortablePython\twisted\internet\selectreactor.py", line 21, in <module>
    from twisted.internet import posixbase
  File "P:\PortablePython\twisted\internet\posixbase.py", line 25, in <module>
    from twisted.internet import tcp, udp
  File "P:\PortablePython\twisted\internet\tcp.py", line 78, in <module>
    from twisted.internet import defer, base, address
  File "P:\PortablePython\twisted\internet\defer.py", line 17, in <module>
    from twisted.python import log, failure, lockfile
  File "P:\PortablePython\twisted\python\lockfile.py", line 28, in <module>
    import pywintypes
ImportError: No module named pywintypes
```

I'm having the same problem using (python portable) but unfortunately switch the lines didn't fix for me.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

This seems more like a bug (or lack of a feature) in pywin32.  Perhaps we should re-arrange the imports, but if that isn't going to fix the problem entirely (as it appears it does not), then also pursing a better fix (upstream) is probably also a good idea.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_6"></a>|@adiroiban commented|
|-|-|

JamesB change also solves my problem.

I am using latest stable Twisted release.

I am using a 'portable' Python distribution, no Python path is added to the global environment variables, and all .dlls are in the same folder as python.exe

The error only occurs when I call python.exe from another folder.
If I change the working directory to the folder hosting python.exe, and then I start python.exe, everything is ok.

I guess this is an error with win32 API, only loading pywintypes.dll from the current folder, and not the same folder as python.exe

----

Seocam is having another problem, since he/she does not have pywintypes installed. 

----

I am not sure if this is a pywin32 bug, or a general python bug.

I also found a strange error, when on RedHat 4 I had to import hashlib, prior to OpenSSL, otherwise the import process got messed up.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_8"></a>|@adiroiban commented|
|-|-|

I have reported this behavior upstream :
http://sourceforge.net/tracker/?func=detail&aid=3390456&group_id=78018&atid=551954

I am still not sure who is to blame for this behavior.

**Comment by Avasam** [comment]
The upstream issue has been moved to https://github.com/mhammond/pywin32/issues/562

@adiroiban Is this issue still relevant?

```py
from win32api import OpenProcess
import pywintypes

print(OpenProcess)
print(pywintypes)

<built-in function OpenProcess>
<module 'pywintypes' (C:\Program Files\Python39\lib\site-packages\pywin32_system32\pywintypes39.dll)>
```
(installed pywin32==306 using pip, removed all python paths from `PATH`, executed the test file from a different location than where my python.exe is located)

**Comment by adiroiban** [comment]
Thanks for the update.

It looks like by now, this was fixed.

I am closing this, as this is not a Twisted issue.
