### ISSUE TITLE
Twisted version scheme differs whether setuptools is installed or not

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3912]
|<img alt="tarek's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| tarek reported|
|-|-|
|Trac ID|trac#3912|
|Type|enhancement|
|Created|2009-07-12 19:53:53Z|

If setuptools is not installed, and if I build a trunk version using twisted setup script, I'll get a : "8.2.0+r27123" for the version number (cooked by twisted.python.versions.Version.short)

If setuptools is installed, it'll cook the version number and the output will differ
and will be "8.2.0-r27123".

The behavior should be the same,

<details><summary>Searchable metadata</summary>

```
trac-id__3912 3912
type__enhancement enhancement
reporter__tarek tarek
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1247428433000000 1247428433000000
changetime__1287501826000000 1287501826000000
version__None None
owner__ 
cc__exarkun cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Arg I hate setuptools.

fwiw, Nevow had exactly the same problem.  http://divmod.org/trac/ticket/2880

**Comment by twisted-trac** [comment]
|[<img alt="zooko's avatar" src="https://avatars.githubusercontent.com/u/467900?s=50" width="50" height="50">](https://github.com/zooko)<a name="note_2"></a>|@zooko commented|
|-|-|

By the way there is another difference between the SVN revision number appended by setuptools and the one appended by twisted's internal version-number-cooking code.  That is that if you commit a new patch to SVN on a different branch then the twisted revision number increments but the setuptools one doesn't.  The setuptools one shows the most recent revision on *this* branch.

I would personally prefer it if (a) the Twisted way to cook version numbers happened to result in the same thing as the setuptools way to cook version numbers, for obvious (?) reasons of uniformity among other Python packages, and (b) Twisted didn't have a way to cook version numbers, but instead relied on some external tool whose sole job in life has to do with versioning and packaging and so on.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Hey, radix, please consider this issue and make a determination as to whether it needs to be resolved for Twisted 9.0.

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_4"></a>|@radix set owner to @exarkun|
|-|-|

Was the nevow fix easy? Is the same fix applicable to Twisted? If so, then we can probably get it in really quickly. If someone does that, I'll review it.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

The new fix was to disable the setuptools behavior even when setuptools was installed.  The patch for Twisted would probably look something like this:

```
#!diff
Index: twisted/python/dist.py
===================================================================
--- twisted/python/dist.py      (revision 27306)
+++ twisted/python/dist.py      (working copy)
@@ -80,6 +80,14 @@
         if sys.version_info[:3] < (2, 3, 0):
             kw['cmdclass']['build_py'] = build_py_twisted
 
+        try:
+            import setuptools
+        except ImportError,:
+            pass
+        else:
+            from distutils.command.sdist import sdist
+            setup_args['cmdclass'] = {'sdist': sdist}
+
     if "conditionalExtensions" in kw:
         extensions = kw["conditionalExtensions"]
         del kw["conditionalExtensions"]
```

(but would probably also include unit tests).

**Comment by twisted-trac** [comment]
|<img alt="TimAllen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_7"></a>|TimAllen commented|
|-|-|

Ticket [#4138](https://github.com/twisted/twisted/issues/4138) involves customizing the `sdist` command for other reasons, so it might wind up accidentally fixing this ticket too.

I had a look at [setuptools' customized sdist](http://svn.python.org/projects/sandbox/trunk/setuptools/setuptools/command/sdist.py) and I can't see any evidence of it messing with version strings at all, so I'm not sure how replacing setuptools' `sdist` with distutils' `sdist` would help at all. Even if it did, it'd be a pretty difficult thing to write a test for, I think, unless the test was "shell out to 'python setup.py sdist'; look in `dist/` and check what shows up", and even then you'd need a buildbot guaranteed to have setuptools installed, and one guaranteed not to.

A better solution might be to update `t.p.versions` to construct [PEP0386](http://www.python.org/dev/peps/pep-0386/)-compatible version strings, which presumably would be acceptable input to distutils or setuptools or distribute.

**Comment by twisted-trac** [comment]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)<a name="note_8"></a>|@jml commented|
|-|-|

This issue wasn't necessary for the 9.0 release, and the 10.0 release is already frozen.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I think that this is fixed.
Twisted now used versionner to version management.
