### ISSUE TITLE
HTTPPageGetter does not support 307 redirects

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3959]
|<img alt="JegnuX's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| JegnuX reported|
|-|-|
|Trac ID|trac#3959|
|Type|defect|
|Created|2009-08-09 08:14:04Z|

in twisted / web / client.py, HTTPPageGetter doesn't support 307 errors. Need to add something like this :

```
def handleStatus_307(self):
    self.factory.method = 'GET'
    self.handleStatus_301()
```

<details><summary>Searchable metadata</summary>

```
trac-id__3959 3959
type__defect defect
reporter__JegnuX JegnuX
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1249805644000000 1249805644000000
changetime__1249806324000000 1249806324000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|ivank commented|
|-|-|

Even though twisted.web.client is an HTTP/1.0 client, it should probably handle 307 redirects from any server. The proposed fix (a copy of handleStatus_303) in the description is incorrect, though.

"303 See Other

The response to the request can be found under a different URI and SHOULD be retrieved using a GET method on that resource. This method exists primarily to allow the output of a POST-activated script to redirect the user agent to a selected resource."

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

So, don't implement 307 like a 303.

**Comment by twisted-trac** [comment]
|<img alt="JegnuX's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|JegnuX commented|
|-|-|

Okay,
It's just this is working for my code, and I really don't know how fix this issue. So now, I'm waiting for a correct fix.

**Comment by twisted-trac** [comment]
|<img alt="ivank's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|ivank set owner to @jyknight|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in https://github.com/twisted/twisted/pull/1683
