### ISSUE TITLE
OSCAR chatReceiveMessage being passed bad data in the message field

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#3963]
|<img alt="Garnett's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| Garnett reported|
|-|-|
|Trac ID|trac#3963|
|Type|defect|
|Created|2009-08-13 10:13:51Z|

I've been working on a chatbot for AOL Instant Messenger. However, I've run into a problem while trying to get Twisted to work as the backend library for this. I've set up a handler for `chatReceiveMessage` so that when the bot connects to a chat room it can respond to the messages that occur there. When it gets called, though, it just gets five garbage characters which seem to be affected only by the length of the incoming chat message. Further examination reveals that `oscar_0E_06` (the function that calls chatReceiveMessage), after unpacking the TLVs of the message, ends up with this dictionary:

```
{1: '\x00D\x00\x02\x00', 2165: 'ascii\x00\x03\x00\x02en\x00\x01\x00.<HTML>The handler never sees this text.</HTML>'}
```

It then sends entry 1 (our aforementioned five incomprehensible characters), leaving the actual message text inside a garbled block of data at entry 2165.

I am on a Gentoo virtual machine running version 8.2 of twisted and twisted-words. My script is based heavily on the example script "oscardemo.py", which exhibits the same failure on this machine. Contact me at ecomono@... if you need any more info to reproduce and/or track down this bug.

Thanks for your time. :)

<details><summary>Searchable metadata</summary>

```
trac-id__3963 3963
type__defect defect
reporter__Garnett Garnett
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__words words
keywords__ 
time__1250158431000000 1250158431000000
changetime__1385158251000000 1385158251000000
version__None None
owner__Snorge Snorge

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Garnett's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_1"></a>|Garnett commented|
|-|-|

For reference, the internal function in question:
```
    def oscar_0E_06(self,snac):
        data = snac[3]
        user,rest=self.bos.parseUser(snac[3][14:],1)
        tlvs = readTLVs(rest[8:])
        message=tlvs[1]
        print user, repr(rest), tlvs
        self.bos.chatReceiveMessage(self,user,message)
```
For the example message "oijwfiofewjoefwj" (yes, nonsensical, but it's not a big deal), repr(rest) looks like:
```
'\x00\x01\x00\x00\x00\x0c\x00\x02\x00\x01\x00\x05\x003\x00\x02\x00\x08us-ascii\x00\x03\x00\x02en\x00\x01\x00\x1d<HTML>oijwfiofewjoefwj</HTML>'
```
From what I can tell, the actual TLV data begins at rest[14:], *not* rest[8:] as called for in the code.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="Snorge's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|Snorge commented|
|-|-|

I experienced this exact same issue, and the suggestion to change 


```
tlvs = readTLVs(rest[8:])
```

to 


```
tlvs = readTLVs(rest[14:])
```

appears to be working for me as well.

System: Mac OS X 10.7.2, included installation of Twisted (appears to be 11.0.0), Python 2.7.

Seems like this should be updated in a future release.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun set owner to Snorge|
|-|-|

Hi Snorge.  Thanks for your suggestion.  If you can add a unit test for this change, it would be greatly helpful!  Please see [the guidelines for Twisted contribution](https://twistedmatrix.com/trac/wiki/ReviewProcess) for more details.  Thanks again!

**Comment by twisted-trac** [comment]
|<img alt="Snorge's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|Snorge commented|
|-|-|

Decided to dig into this a bit deeper finally.  I probably don't have the will to turn this into a patch with the required level of polish, but if someone wants to assist me I would be interested in working more on the issue.

Here are some details on this portion of the protocol that I found online. It seems to be a fairly old reference:

http://iserverd.khstu.ru/oscar/snac_0e_06.html


Here is an example of the data parameter for a call to oscar_0E_06 as of today:
```
'\x05\xef\xf7\x00\xe9\xa1:\xe5\x00\x03\x00\x03\x003\x10isthatagoodlinux\x00\x00\x00\x04\x00\x01\x00\x02\x00\x90\x00\x05\x00\x04L\xd0=\xa7\x00\x0f\x00\x04\x00\x00\x02\xe5\x00\x03\x00\x04R\x8f\xce!\x00\x01\x00\x00\x00\x0c\x00\x02\x00\x01\x00\x05\x00;\x00\x02\x00\x08us-ascii\x00\x03\x00\x02en\x00\x01\x00%<HTML>please read this message</HTML>'
```

Breaking that down like the reference page:
```
\x05\xef\xf7\x00\xe9\xa1:\xe5 (msg-id cookie)
\x00\x03 (message channel)
```
```
\x00\x03 (TLV.Type(0x03) - sender information)
\x003 (TLV.Length = 51)
```
```
\x10 (screenname strlen)
sixteenletternam (screenname string)
\x00\x00 (warning level)
\x00\x04 (number of info TLVs (user info block) - CHANGED FROM 3)
```
```
\x00\x01 (TLV.Type (0x01) - user class)
\x00\x02 (TLV.Length)
\x00\x90 (user class)
```
```
\x00\x05 (UNKNOWN)
\x00\x04 (UNKNOWN)
L\xd0=\xa7 (UNKNOWN)
```
```
\x00\x0f (TLV.Type (0x0f) - user idle time)
\x00\x04 (TLV.Length)
\x00\x00\x02\xe5 (user idle time)
```
```
\x00\x03 (TLV.Type (0x03) - signon time)
\x00\x04 (TLV.Length = 4)
R\x8f\xce! (signon time)
```
```
\x00\x01 (TLV.Type (0x01) - public/whisper flag)
\x00\x00 (TLV.Length)
```
```
\x00\x0c (UNKNOWN)
\x00\x02 (UNKNOWN)
\x00\x01 (UNKNOWN)
```
```
\x00\x05 (TLV.Type(0x05) - message information)
\x00; (TLV.Length = 59)
```
```
\x00\x02 (TLV.Type (0x02) - message encoding)
\x00\x08 (TLV.Length = 8)
us-ascii (message encoding string)
```
```
\x00\x03 (TLV.Type(0x03) - message language)
\x00\x02 (TLV.Length = 2)
en (message language abbr)
```
```
\x00\x01 (TLV.Type(0x01) - message text)
\x00% (TLV.Length = 37)
<HTML>please read this message</HTML> (message text)
```

Notice that there are two sections in this which don't seem to correspond to the TLVs listed on the reference page. I'm guessing something changed in the OSCAR protocol to introduce this bug a few years ago.  There is one extra TLV inside the user TLV (\x00\x05 code), and one extra TLV between the public/whisper flag and the message information TLVs (\x00\x0c code).

That extra TLV has length 6, which is why we things worked when using rest[14:] instead of rest[8:] now.

**Comment by adiroiban** [comment]
I think that this can be closed as for now we only support IRC and Jabber
