### ISSUE TITLE
Twisted Install Error with Odd Python/Win32 Setup

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4068]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)| @teratorn reported|
|-|-|
|Trac ID|trac#4068|
|Type|defect|
|Created|2009-11-05 03:01:47Z|

I have Python2.6 installed system-wide in D:\Python26. It works fine. The reg key
```
    HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\2.6\InstallPath
```
points to the right place (NOT the C: drive).

Regardlessly, the Twisted Installer creates the non-existant directory C:\Python26 (and subdirs) and copies the library files over, then it tries to execute a command using C:\Python26\pythonw.exe (which fails with a MessageBox because the executable doesn't exist).

Obviously we should be getting the right path to Python out of the registry, or it should LoadLibrary() on the Python DLL and introspect the right paths.

I may investigate further as time and opportunity permit. Anyone that tackles this let me know if you need help with anything. Cheers -E

PS. Assigning to Timothy Fitz because you are the other person that claims, however hesitantly, to know a thing about windows (:

<details><summary>Searchable metadata</summary>

```
trac-id__4068 4068
type__defect defect
reporter__teratorn teratorn
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__regression__win32__release__installer regression, win32, release, installer
time__1257390107000000 1257390107000000
changetime__1257424893000000 1257424893000000
version__None None
owner__TimothyFitz TimothyFitz
cc__TimothyFitz cc__moonfallen cc__teratorn cc__exarkun cc__radix cc__PenguinOfDoom
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)<a name="note_1"></a>|@teratorn commented|
|-|-|

This seems to be a regression... see http://twistedmatrix.com/trac/ticket/3556 which is currently closed.

**Comment by twisted-trac** [comment]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)<a name="note_2"></a>|@teratorn commented|
|-|-|

[Adding CC's from previous bug...]

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_3"></a>|@therve commented|
|-|-|

Which version are you using?

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

[#3556](https://github.com/twisted/twisted/issues/3556) is _closed_, certainly, but it wasn't _fixed_.  The reporter said that he could no longer reproduce it.  As described on that ticket, the installer does _try_ to figure out the right place to install things.  Can you provide detailed instructions on how to reproduce this?

**Comment by adiroiban** [comment]
I think that this can be closed.
I don't think that this is an issue anymore.
