### ISSUE TITLE
twisted.web.client.HTTPClient should expose the HTTP status as an integer

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4185]
|<img alt="nejucomo's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| nejucomo reported|
|-|-|
|Trac ID|trac#4185|
|Type|enhancement|
|Created|2009-12-23 17:05:13Z|

The twisted.web.http.Request.setResponseCode() method requires an int argument to represent the HTTP status code to send to a client.

On the other hand, the twisted.web.client.HTTPClientFactory.deferred errback fires with a Failure whose .value.status contains a string representing the HTTP status code in the response from a server.  (The errback fires when this status is an error status, such as a 404.)

I assumed I could pass the contents of a Failure to a Request (server-side response) but this raised a type error.  A simplified example of the code would look like this:

```
def errback(reason):
    assert the_reason_represents_a_404_error_response(reason)
    myRequest.setResponseCode(reason.value.status)


cfac = HTTPClientFactory('http://www.google.com/nonexistent_path_wombat')
cfac.deferred.addCallbacks(normalHandler, errback)
reactor.connectTCP(cfac.host, cfac.port, cfac)
```

<details><summary>Searchable metadata</summary>

```
trac-id__4185 4185
type__enhancement enhancement
reporter__nejucomo nejucomo
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1261587913000000 1261587913000000
changetime__1294924617000000 1294924617000000
version__None None
owner__ 
cc__exarkun
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

Aiming for this kind of symmetry is a great idea.  For one thing, if a particular type makes sense on one side of the connection, it almost certainly makes sense on the other side.  In this case, it certainly makes sense to represent the HTTP status as an integer; the server gets it right, the client gets it wrong.  Fortunately, the new HTTP client gets it right and represents it as an integer.

I don't think this is something to fix in the older HTTP client though.  Simply changing `status` to an integer is an incompatible change, so we should avoid that.  We can add a new attribute and make that an integer... But that's a bit confusing and redundant, and considering all that's necessary to get the status as an integer is to use `int` on the existing attribute, may not be worthwhile.

If someone wants to implement this, or has another idea about how this might be improved, go for it.  However, since it's so easy to "work around", and since there's a replacement for this API anyway, I don't think it's a big deal.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Actually, even in the new client, integer status codes are problematic; [IIS apparently has some status codes with dots in them](http://support.microsoft.com/kb/943891/), although that's not spec-compliant.

We should probably have some kind of [ticket:4671 specific type] used for HTTP status codes.

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)<a name="note_3"></a>|@jyknight commented|
|-|-|

I don't believe you. I think they only put those extended statuses in freetext parts of the response.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in https://github.com/twisted/twisted/pull/1683
