### ISSUE TITLE
Automate uploading pre-release tarballs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4353]
|[<img alt="jml's avatar" src="https://avatars.githubusercontent.com/u/125674?s=50" width="50" height="50">](https://github.com/jml)| @jml reported|
|-|-|
|Trac ID|trac#4353|
|Type|enhancement|
|Created|2010-03-07 14:36:43Z|
|Branch|https://github.com/twisted/twisted/tree/upload-prerelease-4353|

Related to [[#2888](https://github.com/twisted/twisted/issues/2888)](https://github.com/twisted/twisted/issues/2888) but possibly easier solved separately.

As part of the ReleaseProcess, we need to upload pre-release tarballs somewhere so that people can test them. Normally, we don't upload them to twistedmatrix.com, instead we upload them to someone's personal web space.

It would be nice to have the process for this automated. A fix to #2888 might conceivably fix this.

<details><summary>Searchable metadata</summary>

```
trac-id__4353 4353
type__enhancement enhancement
reporter__jml jml
priority__normal normal
milestone__totally_automated_release_infrastructure totally automated release infrastructure
branch__branches_upload_prerelease_4353 branches/upload-prerelease-4353
branch_author__therve therve
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1267972603000000 1267972603000000
changetime__1448145254476955 1448145254476955
version__None None
owner__therve therve
cc__thijs cc__michael@...
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)|@therve set owner to @therve|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_3"></a>|@therve commented|
|-|-|

(In [38889]) Branching to 'upload-prerelease-4353'

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_4"></a>|@therve removed owner|
|-|-|

The attached branch makes a tiny step into automating pre-release upload. It uses our own cftp and uploads a list of files in a directory.

I think we should also standardize where we upload the pre-releases. Possibly creating a custom user for that on the server? Or we could find a specific place in www-data, but the branch would need to change a bit.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_5"></a>|@tomprince set owner to @therve|
|-|-|

1.I would suggest putting them under `/srv/t-web`. Do they want to be under `https://twistedmatrix.com/Releases/` or some other directory. If the former, then they want to be uploaded under `data/releases` and the later `data/prereleases`. (Both as user `t-web`).
 2. I'd be inclined to use twisted as a library, rather than spawning a process that reads a batch file.
   - I guess this might be involved. If that is the case, we should at least file tickets for the pieces needed to make this easier.
 3. `twisted.python.usage`! I know nothing else here uses it yet. But ... `twisted.python.usage`!
 4. `SystemExit` can be raised by a succesful exit, as well, so doesn't make a good test (at least without another assertion).

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_6"></a>|@therve removed owner|
|-|-|

Replying to [tom.prince](#note_5):
>  1. I would suggest putting them under `/srv/t-web`. Do they want to be under `https://twistedmatrix.com/Releases/` or some other directory. If the former, then they want to be uploaded under `data/releases` and the later `data/prereleases`. (Both as user `t-web`).

I don't think we want it to be under t-web. At any rate, the path is a parameter, so we can decide later on.

>  2. I'd be inclined to use twisted as a library, rather than spawning a process that reads a batch file.
>    - I guess this might be involved. If that is the case, we should at least file tickets for the pieces needed to make this easier.

Yeah I tried but it's pretty much impossible for now. I'm not sure I have great tickets in mind, except "make conch filetransfer better".

>  3. `twisted.python.usage`! I know nothing else here uses it yet. But ... `twisted.python.usage`!

It's really overkill in this case.

>  4. `SystemExit` can be raised by a succesful exit, as well, so doesn't make a good test (at least without another assertion).

Fixed.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_7"></a>|@thijstriemstra commented|
|-|-|

If you pass a non-existing directory as the first parameter you get:

```
Traceback (most recent call last):
  File "bin/admin/upload-tarballs", line 20, in <module>
    UploadTarballsScript().main(sys.argv[1:], __file__)
  File "/twisted/python/_release.py", line 1457, in main
    self.uploadTarballs(FilePath(args[0]), args[1], args[2], cftp.path)
  File "/twisted/python/_release.py", line 1419, in uploadTarballs
    first = path.children()[0]
  File "/twisted/python/filepath.py", line 363, in children
    raise UnlistableError(ose)
twisted.python.filepath.UnlistableError
```

Passing an empty directory results in:
```
Traceback (most recent call last):
  File "bin/admin/upload-tarballs", line 20, in <module>
    UploadTarballsScript().main(sys.argv[1:], __file__)
  File "/twisted/python/_release.py", line 1457, in main
    self.uploadTarballs(FilePath(args[0]), args[1], args[2], cftp.path)
  File "/twisted/python/_release.py", line 1419, in uploadTarballs
    first = path.children()[0]
IndexError: list index out of range
```

Would be nice to raise a meaningful exception in those cases or do you think that's overkill? If I'll ever use this command I'd want to be absolutely sure it's working or gives me a proper error since the file's going to a remote server where I might not have access to delete an erroneous file? And what about overwriting existing files, what does the tool do in that case?

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)<a name="note_8"></a>|@radix commented|
|-|-|

I don't get the point of this branch. It's +170 LoC for "scp -r", and it doesn't even encode any useful policy. I think either this ticket shouldn't exist, or it should be interpreted as solving the problem holistically (whatever that means).

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_9"></a>|@therve commented|
|-|-|

The branch does one interesting thing, which is to find the version from the tarballs, and use that as the target directory. I think it's a useful small first step, which is nice considering that nothing has happened in [#2888](https://github.com/twisted/twisted/issues/2888) for 6 years.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_10"></a>|@exarkun set owner to @therve|
|-|-|

I agree with therve - this seems like a good way to make a step forward on our otherwise largely stalled release automation project.

I also agree with radix - this should at least encode some policy otherwise it seems like far too much code for minimal benefit.  Can I suggest that it at least do something like always upload to "~/public_html/prereleases"?

  1. twisted/python/_release.py
    1. `printProgress` seems to nearly split the functionality of `runCommand` in two.  It seems like a better API would be to accept a file-like object to copy the output to.  If this functionality were put into a new API and `runCommand` were changed to use that API with a throw-away `BytesIO` instance (or, say, /dev/null) then there'd be less code and no "change this function entirely"-style flags (also, no use of print - making the code more testable).
    1. Does `runCommand` really have no direct unit tests? :(  Sad.  I guess that makes it harder to ask where the unit tests for the new `runCommand`-related functionality is without looking like a jerk.
    1. The API docs for `UploadTarballsScript` use `C{}` for builtin types.  Please use `L{}`.
    1. The API docs use `str`.  They also use native string literal syntax.  I don't really know what the best course forward is but I have stopped using both of these things in new code I write, preferring the unambiguous `bytes` and `b""`.  I'm not saying you have to do this.  I'm just pointing out a difficulty that may lie ahead.
    1. Please add a link to the conch improved-filetransfer-api ticket above the use of runCommand to launch cftp in a child process in `UploadTarballsScript.uploadTarballs`.
    1. Please use the oxford comma in the `sys.exit` string in `UploadTarballsScript.main` :)
  1. twisted/python/test/test_release.py
    1. nice catch on `ScriptTests`
    1. `test_main` docstring talks about `C{sftp}`.  I'm not sure what `C{}` indicates here.  I probably would have written `I{}` to give it some emphasis.  I think `C{}` only makes sense for a snippet of Python code (or perhaps some other language).  Also it actually tests for cftp usage, not sftp usage.
    1. I think `test_main` is testing two different things and should be split into two tests.  Perhaps this also suggests the implementation should be split up so that the generation of the batch file can be exercised independently of the function to run the upload.
    1. `test_missingArgument` docstring says the function requires 2 arguments but it actually requires 3.  But!  Maybe the path argument will go away and this will end up correct. :)
  1. Please address thijs's comments above or file tickets for adding error handling for those mis-uses (and link to the tickets from the implementation please).
  1. I agree that we should be using `twisted.python.usage` in these scripts (if for no other reason than that supporting `--help` is pretty nice) - but I don't mind if someone works on that later.

That's it from me.  These aren't major points.  Please address and then merge.  Thanks a lot!

**Comment by adiroiban** [comment]
This is done via github actions and the github release process.

I think it can be closed.
