### ISSUE TITLE
test_trial fails on windows

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4689]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#757|
|Type|defect|
|Created|2004-10-25 01:24:06Z|

Attachments:

* [test.log](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/d64/d64ce8d6017f0d3ab6d528cf5dfd616ae05c32b4/324a41b34d2dfa32c804ef7b2ac23fc24200c596.log) (10450 bytes) - added by moonfallen on 2004-10-25 03:04:42Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__757 757
type__defect defect
reporter__itamarst itamarst
priority__highest highest
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__core core
keywords__ 
time__1098667446000000 1098667446000000
changetime__1102703463000000 1102703463000000
version__ 
owner__slyphon slyphon
cc__moonfallen cc__slyphon
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)|@itamarst commented|
|-|-|

```
#!html
<pre>
Cory may be able to help with this.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Just had time to run trial and attach a log.  Here it is.

Note the "please tell slyphon you saw this message!" message at the top. :-)
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="slyphon's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|slyphon commented|
|-|-|

```
#!html
<pre>
the "please tell slyphon you saw this message!" is related to the
twisted.python.plugin system not working in several mysterious (to me)
circumstances.

as to the failures, they're partly the fault of procutils.which() not finding
'trial' and wprocess being horribly broken
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
wprocess is no longer horribly broken.  Try again. :-)
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
But wprocess is now missing, so they fail worse.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
Is this relevant any more? I think slyphon made the trial tests stop using
processes. 

btw, trial is failing on cfreactor too with a "can't crash stopped reactor".
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph commented|
|-|-|

```
#!html
<pre>
Unit tests still failing on windows, but not test_trial
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="jyknight's avatar" src="https://avatars.githubusercontent.com/u/873903?s=50" width="50" height="50">](https://github.com/jyknight)|@jyknight commented|
|-|-|

```
#!html
<pre>
What's that got to do with this bug then?
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
*blink*  *blink*   Did you mean to post that comment to another bug?  This bug
is about test_trial failing, and it's not failing.
</pre>
```

**Comment by twisted-trac** [comment]
|<img alt="moonfallen's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|moonfallen commented|
|-|-|

```
#!html
<pre>
Hrm, he's not even nosy here.  Closing again.
</pre>
```

**Comment by twisted-trac** [comment]
|[<img alt="radix's avatar" src="https://avatars.githubusercontent.com/u/227068?s=50" width="50" height="50">](https://github.com/radix)|@radix commented|
|-|-|

```
#!html
<pre>
nobody specified what "could be better", so resolving.
</pre>
```

**Comment by stback2024-pixel** [comment]
I noticed that your project is seeking reviews. I can provide a detailed, constructive feedback on your codebase and offer to do more for a payment. Let me know if you are interested.
