### ISSUE TITLE
pydoctor generated documentation on the website should use common stylesheet

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4693]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#4693|
|Type|enhancement|
|Created|2010-10-18 23:10:04Z|
|Branch|https://github.com/twisted/twisted/tree/howto-styling-4693|

When I was setting up [tm.tl](http://tm.tl/), I realized that it's pretty easy to add the Twisted Matrix Labs template frosting to a web page.  The pydoctor template that we use on the website should include that.

Attachments:

* [screen1.png](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/e80/e8097443ce629e44b745ff723b628d3740f03141/2dbb726c073c8fbebda37819d507b352f8503c0f.png) (84552 bytes) - added by thijs on 2011-11-06 15:51:03Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__4693 4693
type__enhancement enhancement
reporter__glyph glyph
priority__normal normal
milestone__ 
branch__branches_howto_styling_4693 branches/howto-styling-4693
branch_author__thijs thijs
status__assigned assigned
resolution__None None
component__website website
keywords__documentation documentation
time__1287443404000000 1287443404000000
changetime__1321115322000000 1321115322000000
version__None None
owner__thijs thijs
cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @thijstriemstra|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

(In [33085]) Branching to 'howto-styling-4693'

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_4"></a>|@thijstriemstra commented|
|-|-|

(In [33086]) Use css style from website in template for howto documents. refs [#4693](https://github.com/twisted/twisted/issues/4693)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra removed owner|
|-|-|

Below's a screenshot of a howto with the website css style applied. As you can see there are some images missing (that have a relative reference in the css file) and I wonder how to handle this with lore. It basically needs to make relative links in every html page for static images..

We could also simply decide to get rid of the top banner where all the images are and only use the text styling.


![screen1.png,nolink](/uploads/migrated/screen1.png,nolink)

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

Huh.  The release document looks wrong, since it does direct the release manager to use `doc/core/howto/template.tpl` to generate the website documentation.  Instead, it should be directing the release manager to use `doc/core/howto/website-template.tpl`.

In turn, it seems `template.tpl` has gotten somewhat out of date for a few reasons:

  1. It is missing the version footer.
  1. It is missing at sitemeter and google analytics (adding this would remove a couple gross manual steps from the release process).
  1. It should have a link to the latest version of the docs, as was just recently added to the api docs pages.

These are all separate issues, but implementing the website style in the website template still makes more sense than implementing it in the default template.

I haven't really read the diff closely apart from this, and I'm not going to comment on the particulars of the css.

**Comment by twisted-trac** [comment]
|[<img alt="jonathanj's avatar" src="https://avatars.githubusercontent.com/u/112166?s=50" width="50" height="50">](https://github.com/jonathanj)<a name="note_7"></a>|@jonathanj commented|
|-|-|

I'm a little confused, the ticket talks about "pydoctor generated documentation" but the howtos are Lore docs.

I assume that moving to the Sphinx documentation is still not really close to being on the cards if we're updating the styling of Lore documentation.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun set owner to @thijstriemstra|
|-|-|

>I'm a little confused, the ticket talks about "pydoctor generated documentation" but the howtos are Lore docs.

Good point.  The branch seems to implement the wrong thing entirely.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_9"></a>|@thijstriemstra set status to `assigned`|
|-|-|

Replying to [exarkun](#note_6):
> Huh.  The release document looks wrong, since it does direct the release manager to use `doc/core/howto/template.tpl` to generate the website documentation.

I opened [#5380](https://github.com/twisted/twisted/issues/5380) for this.

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_10"></a>|@thijstriemstra commented|
|-|-|

Replying to [exarkun](#note_8):
> >I'm a little confused, the ticket talks about "pydoctor generated documentation" but the howtos are Lore docs.
> 
> Good point.  The branch seems to implement the wrong thing entirely.
> 

Fair enough. I started with trying to add the header to the API documentation but couldn't find a way to specify a custom html/css template to pydoctor and then implemented it for the howtos instead.

**Comment by adiroiban** [comment]
I think that this can be closed.

Since we no longer have the Trac website and custom theme, pydoctor should be standalone

At the same time, the docs are using the Read The Docs theme.

And pydoctor now has support for RTD theme https://github.com/twisted/pydoctor/pull/457

I am going to close this.

This should be fixed by just upgrading to latest pydoctor.
