### ISSUE TITLE
"setup.py install" installs topfiles directories

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4743]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#4743|
|Type|defect|
|Created|2010-11-23 00:43:21Z|

There's no reason to have these directories added to site-packages.  They aren't part of the Twisted package, they're data about a particular release for human consumption.

<details><summary>Searchable metadata</summary>

```
trac-id__4743 4743
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1290473001000000 1290473001000000
changetime__1309133866000000 1309133866000000
version__None None
owner__ 
cc__therve cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_1"></a>|@therve commented|
|-|-|

Note that it's only true for the top setup.py which is used in the global Twisted tarball. The subproject setup.py are correct.

The trivial fix is to change the data_files directive: `data_files=getDataFiles('twisted', ignore=['topfiles'])`.

**Comment by twisted-trac** [comment]
|<img alt="Automation's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|Automation removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

Also see [#5042](https://github.com/twisted/twisted/issues/5042)

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)|@thijstriemstra set owner to @thijstriemstra<br>@thijstriemstra set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra removed owner<br>@thijstriemstra set status to `new`|
|-|-|

Replying to [therve](#note_1):
> Note that it's only true for the top setup.py which is used in the global Twisted tarball. The subproject setup.py are correct.
> 
> The trivial fix is to change the data_files directive: `data_files=getDataFiles('twisted', ignore=['topfiles'])`.

When using 'ignore' it does exclude the `topfiles` folder for `packages` and `data_files` but the resulting egg still contains the folders..

When you remove the top-level 'twisted' package in the `packages` list it excludes the `topfiles` folder though.

```
#!diff
Index: setup.py
===================================================================
--- setup.py    (revision 32185)
+++ setup.py    (working copy)
@@ -52,6 +52,10 @@
                        and x in twisted_subprojects]
 
     scripts = []
+    packages = getPackages('twisted', ignore=['topfiles'])
+    data_files = getDataFiles('twisted', ignore=['topfiles'])
+    packages.remove('twisted')
     for i in projects:
         scripts.extend(getScripts(i))
 
@@ -71,11 +75,11 @@
 An extensible framework for Python programming, with special focus
 on event-based network programming and multiprotocol integration.
 """,
-            packages = getPackages('twisted'),
+            packages = packages,
             conditionalExtensions = getExtensions(),
             scripts = scripts,
-            data_files=getDataFiles('twisted'),
-            classifiers=[
+            data_files = data_files,
+            classifiers = [
                 "Programming Language :: Python :: 2.4",
                 "Programming Language :: Python :: 2.5",
                 "Programming Language :: Python :: 2.6",
```


But then this change below doesn't remove/ignore the folder in a sub-project though..

```
#!diff
Index: twisted/python/dist.py
===================================================================
--- twisted/python/dist.py      (revision 32185)
+++ twisted/python/dist.py      (working copy)
@@ -1,3 +1,6 @@
+# Copyright (c) Twisted Matrix Laboratories.
+# See LICENSE for details.
+
 """
 Distutils convenience functionality.
 
@@ -54,7 +57,9 @@
         projname = kw['twisted_subproject']
         projdir = os.path.join('twisted', projname)
 
-        kw['packages'] = getPackages(projdir, parent='twisted')
+        kw['packages'] = getPackages(projdir, ignore=['topfiles'], parent='twisted')
         kw['version'] = getVersion(projname)
 
         plugin = "twisted/plugins/twisted_" + projname + ".py"
@@ -62,7 +67,7 @@
             kw.setdefault('py_modules', []).append(
                 plugin.replace("/", ".")[:-3])
 
-        kw['data_files'] = getDataFiles(projdir, parent='twisted')
+        kw['data_files'] = getDataFiles(projdir, ignore=['topfiles'], parent='twisted')
 
         del kw['twisted_subproject']
     else:
``` 

Perhaps `package_data` should be used to specify a [*.py pattern](http://docs.python.org/distutils/setupscript.html#installing-package-data) for packages?

**Comment by adiroiban** [comment]
I think that this can be closed as it should no longer be an issue.

We no longer have sub-project packages.
