### ISSUE TITLE
web.client.HTTPPageGetter.handle_301 does not re-use SSL context

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#4890]
|<img alt="wetherbeei's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| wetherbeei reported|
|-|-|
|Trac ID|trac#4890|
|Type|enhancement|
|Created|2011-02-17 17:32:13Z|

When following redirects, the HTTPPageGetter class creates it's own SSL context using the default ssl.ClientContextFactory(), when it should use the same context passed to it in getPage. I have a buggy remote SSL implementation that needs a few special options set on each SSL context, as I get forwarded to the buggy server mid-way through a series of redirects.

<details><summary>Searchable metadata</summary>

```
trac-id__4890 4890
type__enhancement enhancement
reporter__wetherbeei wetherbeei
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1297963933000000 1297963933000000
changetime__1297963933000000 1297963933000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in https://github.com/twisted/twisted/pull/1683
