### ISSUE TITLE
ReactorBuilder test infrastructure breaks code that uses the global reactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5206]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)| @itamarst reported|
|-|-|
|Trac ID|trac#5206|
|Type|defect|
|Created|2011-07-27 11:52:15Z|

Code that uses the global reactor, e.g. `twisted.internet.task.cooperate`, will not work correctly with tests that use the ReactorBuilder infrastructure. While such code should be updated to have an explicit reactor passed in, doing so can be non-trivial (e.g. `cooperate` needs a registry, or it's a 3rd party library that cannot be modified).

Providing some workaround to this would both be helpful for testing, but also (depending on the implementation) could later be expanded to help catch code that relies on the global reactor instance.

<details><summary>Searchable metadata</summary>

```
trac-id__5206 5206
type__defect defect
reporter__itamar itamar
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__closed closed
resolution__wontfix wontfix
component__core core
keywords__ 
time__1311767535000000 1311767535000000
changetime__1321499609000000 1321499609000000
version__None None
owner__itamar itamar

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun set owner to @itamarst|
|-|-|

The `ReactorBuilder` tests are intended for unit testing reactor implementations.  I think this eliminates un-updateable 3rd party code as a problem.  `cooperate` doesn't need a registry, either - code under test can just parameterize the cooperate callable, like `twisted.web.client.FileBodyProducer` does.

So maybe this isn't a problem after all.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_2"></a>|@itamarst commented|
|-|-|

I had the problem testing the reactor, kinda sorta: abortConnection tests running the new TLS code.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_3"></a>|@exarkun commented|
|-|-|

Right, kinda sorta: the new TLS code isn't third-party.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_4"></a>|@itamarst set status to `closed`|
|-|-|

Meh. We can just use workarounds when necessary.

**Comment by itamarst** [comment]
Ono.

**Comment by itamarst** [comment]
The brilliant individual who opened this issue originally had a point: I'm hitting this again, testing TLS code in Twisted. And yes, I can patch things but it's really brittle to do so, e.g. every new person who tweaks any relevant code is liable to hit this issue due to things not keeping references to reactor.
