### ISSUE TITLE
Many `_listOpenFDs` tests fail on OpenBSD

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5226]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#5226|
|Type|defect|
|Created|2011-08-08 23:50:45Z|

A handful of tests fail on OpenBSD, relating to how we detect open file descriptors which need to be closed after forking to launch a child process.

Here is a representative sample:
    twisted.internet.test.test_posixprocess.FileDescriptorTests.test_expctedFDs
    twisted.internet.test.test_process.PTYProcessTestsBuilder_PollReactor.test_openFileDescriptors

These mainly fail because OpenBSD _is not_ reporting the correct open file descriptors list.  This is a shortcoming of our open file descriptors detection code, but unless anyone has a brilliant idea for improving it, we should do something to make these tests not fail.  The fallback is mostly good enough for correctness, it's just perhaps a little bit slow.

One option is to unconditionally skip them on OpenBSD.

Another option would be to weaken the assertion, to only cover what we really need.  It's most important for `_listOpenFDs` to always tell us all open file descriptors.  It's not as important for it to not tell us closed file descriptors (though it's better when it doesn't do this).

<details><summary>Searchable metadata</summary>

```
trac-id__5226 5226
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1312847445000000 1312847445000000
changetime__1312847445000000 1312847445000000
version__None None
owner__ 

```
</details>

**Comment by adiroiban** [comment]
For now, we don't have the energy to support OpenBSD .
Also, with the current GitHub only infrastructure, I don't know how we can run OpenBSD tests

I think that this can be closed.

It can be opened once someone volunteer to mantain OpenBSD support for Twisted.

**Comment by glyph** [comment]
Agreed. We support the platforms that we have in CI, and if anyone wants OpenBSD support they should contribute some kind of build support.
