### ISSUE TITLE
Update twisted.web.client.getPage to use Agent and friends.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5405]
|<img alt="amberite's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| amberite reported|
|-|-|
|Trac ID|trac#5405|
|Type|enhancement|
|Created|2011-11-22 17:43:36Z|

Now that twisted.web.client.Agent supports redirection and cookies, porting the getPage functionality to run atop Agent would seem to be a win in terms of reducing the amount of code to be maintained.

Attachments:

* [agentGetPageSketch.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/aea/aeab2a27fe4d5b98eee7f174a7301f98b85a68e9/1435bcba8c8f0380c1a0071963b6e248d4f70eb8.py) (2867 bytes) - added by amberite on 2011-11-22 17:44:47Z - A crappy sketch of how to implement getPage in terms of Agent
* [agentGetPageSketch.2.py](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/aea/aeab2a27fe4d5b98eee7f174a7301f98b85a68e9/9b698d555dd76051dccc839ba694f6ac8e49173d.py) (2462 bytes) - added by amberite on 2011-12-11 01:59:07Z - Updated sketch using FileBodyProducer
* [compatAgentGetPage_v1.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/aea/aeab2a27fe4d5b98eee7f174a7301f98b85a68e9/358ec0d5e4c229939967f23fc9b242151665c3b5.patch) (3958 bytes) - added by dbornside on 2013-05-23 23:31:52Z - get page implementation based on Agent

<details><summary>Searchable metadata</summary>

```
trac-id__5405 5405
type__enhancement enhancement
reporter__amberite amberite
priority__low low
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1321983816000000 1321983816000000
changetime__1369352726000000 1369352726000000
version__None None
owner__ 
cc__jknight cc__amberite cc__dbornside
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

We have `FileBodyProducer` now.  `FileBodyProducer(StringIO(formdata))` can replace `RequestBodyProducer(formdata)`.

**Comment by twisted-trac** [comment]
|<img alt="amberite's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_3"></a>|amberite commented|
|-|-|

Still crappy, but a little closer.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_5"></a>|@exarkun commented|
|-|-|

Awesome, amberite. :)  Thanks for pushing this on.  Have you tried dropping this `getPage` into `twisted.web.client` and discovering what the unit tests think of it?

**Comment by twisted-trac** [comment]
|<img alt="amberite's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|amberite commented|
|-|-|

I've progressed this to the point where it passes the tests up until WebClientSSLTestCase, where it starts to throw some errors, and then hangs outright on test_getPageBrokenDownload.

I'll attach another stab at this once I've got some more tests passing, or if I can't figure out why the tests fail.

**Comment by twisted-trac** [comment]
|[<img alt="cyli's avatar" src="https://avatars.githubusercontent.com/u/223200?s=50" width="50" height="50">](https://github.com/cyli)<a name="note_7"></a>|@cyli commented|
|-|-|

I'm not sure if this is would comply with the twisted coding standards, but it'd be nice if the new getPage could take an IBodyProducer as well as just postdata.

I know that the current docstring says to look at the arguments from HTTPClientFactory, and I guess compatibility needs to be maintained, so a postdata argument needs to be there, but it'd be convenient if, for instance, I wanted to upload a file for me to just provide the FileBodyProducer for that file, rather than read the whole thing into memory and then pass it as postdata, which then creates a file like object to pass to FileBodyProducer anyway.

Sorry to be a pain.  :)  Just seems like it might be a convenience.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun commented|
|-|-|

The `getPage` API has a lot of problems.  `Agent` is the future.  We should definitely have an API that makes it easy to post forms and easy to upload files, though - but I'd lean away from pushing that into `getPage` and think more about something new.

**Comment by twisted-trac** [comment]
|<img alt="amberite's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_9"></a>|amberite commented|
|-|-|

Yeah, I believe there was some talk on IRC a while back about designing a better API atop Agent, and doing the minimum necessary to move getPage/downloadPage atop Agent.  That said, if there is some powerful desire to add backwards-compatible improvements to getPage/downloadPage, I'm willing to work on them after I actually get the basics working.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_10"></a>|@glyph commented|
|-|-|

See also: [ticket:5462 Agent should probably process relative URI references] when it deals with a redirect.

**Comment by twisted-trac** [comment]
|<img alt="dbornside's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_11"></a>|dbornside commented|
|-|-|

This patch is a pretty rough cut of a t.w.c.getPage implemntation; it still fails on some tests; the ones relating to redirects and timeouts.  Also missing is a related change for downloadPage;

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in #1683
