### ISSUE TITLE
Update http://wiki.python.org/moin/TwistedMatrix in ReleaseProcess

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5706]
|<img alt="techtonik's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| techtonik reported|
|-|-|
|Trac ID|trac#5706|
|Type|enhancement|
|Created|2012-06-10 10:29:51Z|

Mention http://wiki.python.org/moin/TwistedMatrix in ReleaseProcess.

## Why bother?
 * page subscribers could be notified about new release automatically
   * subscription and login on Python wiki is easier
     * because it uses OAuth
 * updated info on the central Python community wiki (not as popular as Wikipedia, but still useful)

<details><summary>Searchable metadata</summary>

```
trac-id__5706 5706
type__enhancement enhancement
reporter__techtonik techtonik
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1339324191000000 1339324191000000
changetime__1339324192000000 1339324192000000
version__None None
owner__ 
cc__radix
```
</details>

**Comment by adiroiban** [comment]
I think that this can be closed.
This is now part of the docs https://docs.twisted.org/en/stable/core/development/policy/release-process.html
