### ISSUE TITLE
twisted.test.test_strcred fails on Python without pycrypto

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#5805]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)| @thijstriemstra reported|
|-|-|
|Trac ID|trac#5805|
|Type|defect|
|Created|2012-07-25 17:33:14Z|

When you run the tests without having pycrypto installed the following tests fail:

```
[ERROR]
Traceback (most recent call last):
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/plugin.py", line 213, in getPlugins
    adapted = interface(plugin, None)
  File "/usr/local/lib/python2.6/dist-packages/zope.interface-4.0.1-py2.6-linux-x86_64.egg/zope/interface/interface.py", line 131, in __call__
    adapter = self._call_conform(conform)
  File "/usr/local/lib/python2.6/dist-packages/zope.interface-4.0.1-py2.6-linux-x86_64.egg/zope/interface/interface.py", line 494, in _call_conform
    return conform(self)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/plugin.py", line 68, in __conform__
    return self.load()
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/plugin.py", line 63, in load
    return namedAny(self.dropin.moduleName + '.' + self.name)
  File "/home/thijs/workspaces/opensource/software/twisted/svn/Twisted/trunk/twisted/python/reflect.py", line 517, in namedAny
    obj = getattr(obj, n)
exceptions.AttributeError: 'module' object has no attribute 'theSSHKeyCheckerFactory'

twisted.test.test_strcred.TestAnonymousChecker.testAnonymousAccessSucceeds
twisted.test.test_strcred.TestAnonymousChecker.test_isChecker
twisted.test.test_strcred.TestCheckerOptions.test_createsDictionary
twisted.test.test_strcred.TestCheckerOptions.test_credInterfacesProvidesLists
twisted.test.test_strcred.TestCheckerOptions.test_displaysListCorrectly
twisted.test.test_strcred.TestCheckerOptions.test_displaysListCorrectly
twisted.test.test_strcred.TestCheckerOptions.test_displaysListCorrectly
twisted.test.test_strcred.TestCheckerOptions.test_invalidAuthError
twisted.test.test_strcred.TestCheckerOptions.test_invalidAuthError
twisted.test.test_strcred.TestCheckerOptions.test_invalidAuthError
twisted.test.test_strcred.TestCheckerOptions.test_listDoesNotDisplayDuplicates
twisted.test.test_strcred.TestLimitingInterfaces.test_helpAuthLimitsOutput
twisted.test.test_strcred.TestLimitingInterfaces.test_helpAuthTypeLimitsOutput
twisted.test.test_strcred.TestLimitingInterfaces.test_helpAuthTypeLimitsOutput
twisted.test.test_strcred.TestLimitingInterfaces.test_unsupportedInterfaceError
twisted.test.test_strcred.TestPublicAPI.test_emptyDescription
twisted.test.test_strcred.TestPublicAPI.test_emptyDescription
twisted.test.test_strcred.TestPublicAPI.test_emptyDescription
twisted.test.test_strcred.TestPublicAPI.test_invalidAuthType
twisted.test.test_strcred.TestPublicAPI.test_invalidAuthType
twisted.test.test_strcred.TestPublicAPI.test_invalidAuthType
twisted.test.test_strcred.TestStrcredFunctions.test_findCheckerFactories
twisted.test.test_strcred.TestStrcredFunctions.test_findCheckerFactories
twisted.test.test_strcred.TestUnixChecker.test_isChecker
twisted.test.test_strcred.TestUnixChecker.test_unixCheckerFailsPassword
twisted.test.test_strcred.TestUnixChecker.test_unixCheckerFailsUsername
twisted.test.test_strcred.TestUnixChecker.test_unixCheckerSucceeds
-------------------------------------------------------------------------------
Ran 7980 tests in 55.199s

FAILED (skips=1566, expectedFailures=11, errors=27, successes=6386)
```

<details><summary>Searchable metadata</summary>

```
trac-id__5805 5805
type__defect defect
reporter__thijs thijs
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1343237594000000 1343237594000000
changetime__1373121404000000 1373121404000000
version__None None
owner__ 
cc__thijs cc__jamesbroadhead
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun set owner to @thijstriemstra|
|-|-|

This is at odds with [buildbot's results](http://buildbot.twistedmatrix.com/builders/py-without-modules/builds/104/steps/trial/logs/stdio).  What's different about your environment?

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_3"></a>|@thijstriemstra commented|
|-|-|

```
Python 2.6.7 (r267:88850, Aug 11 2011, 12:18:09) 
[GCC 4.6.1] on linux2
```

That's the system installed version on ubuntu 12.4 without pycrypto, pyasn1. The buildbot has [pycrypto installed](http://buildbot.twistedmatrix.com/builders/py-without-modules/builds/104/steps/shell_2/logs/versions) and is using python 2.6.1.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

Notice that the build I linked to runs trial with `--without-module Crypto`.  That means that it _effectively_ does not have pycrypto installed, for the purposes of the build.

**Comment by twisted-trac** [comment]
|[<img alt="therve's avatar" src="https://avatars.githubusercontent.com/u/159137?s=50" width="50" height="50">](https://github.com/therve)<a name="note_5"></a>|@therve commented|
|-|-|

This is because of the plugin cache. The following sequence of events reproduce it, on a system with pycrypto:

```
$ rm twisted/plugins/dropin.cache
$ trial twisted.test.test_strcred
$ trial --without-module Crypto twisted.test.test_strcred
```

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_6"></a>|@thijstriemstra removed owner|
|-|-|

Replying to [therve](#note_5):
> This is because of the plugin cache. The following sequence of events reproduce it, on a system with pycrypto:
> 
> ```
> $ rm twisted/plugins/dropin.cache
> $ trial twisted.test.test_strcred
> $ trial --without-module Crypto twisted.test.test_strcred
> ```

In that case I think something that needs to be added to the buildslave. Unassigning myself.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_7"></a>|@exarkun commented|
|-|-|

[#6376](https://github.com/twisted/twisted/issues/6376) was a duplicate of this.  Note that it describes the same problem when a different Conch dependency is missing, pyasn1.

**Comment by alex** [comment]
pycrypto hasn't been a dependency for a while, this can be closed
