### ISSUE TITLE
Make it possible to cancel getPage and downloadPage

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6104]
|<img alt="luks's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| luks reported|
|-|-|
|Trac ID|trac#6104|
|Type|enhancement|
|Created|2012-10-12 16:54:09Z|
|Branch|https://github.com/twisted/twisted/tree/get-page-cancel-6104|

Currently there is no way to cancel the deferreds returned by `getPage` or `downloadPage`. The attached patch adds a canceller to these deferreds, so calling `d.cancel()` will actually close the connection and fail with `CancelledError`. The implementation is similar to `twisted.web.xmlrpc.Proxy.callRemote`, with a different way of calling the errback.

I had to change `HTTPClientFactory.clientConnectionFailed`, because even though the docstring suggests it should be possible to send a result to the deferred before this method is called, it wouldn't fire `_disconnectedDeferred` in that case and the user-specified callback/errback would never be actually called.

Attachments:

* [get-page-cancel.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/fd1/fd1c8d6f01bf3b4ebb2bf1482e9bf899a07a99db/ead5819c1b4a198790e8c1f10e023cfa166531cc.diff) (6150 bytes) - added by luks on 2012-10-12 16:54:34Z - 
* [get-page-cancel-2.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/fd1/fd1c8d6f01bf3b4ebb2bf1482e9bf899a07a99db/dc513ccb7e3fba8754642a79ce5d2ed72fe46cb2.diff) (553 bytes) - added by luks on 2013-01-07 08:57:27Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__6104 6104
type__enhancement enhancement
reporter__luks luks
priority__normal normal
milestone__ 
branch__branches_get_page_cancel_6104 branches/get-page-cancel-6104
branch_author__glyph glyph
status__new new
resolution__None None
component__web web
keywords__ 
time__1350060849000000 1350060849000000
changetime__1359229926000000 1359229926000000
version__None None
owner__luks luks
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

(In [36747]) Branching to 'get-page-cancel-6104'

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

I checked it into a branch and [forced some builds](http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/get-page-cancel-6104).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set owner to luks|
|-|-|

Hi luks, thanks for your contribution.

This branch looks pretty good; coding-standard compliant, starting with unit tests.  However, it has one significant flaw in its test cases.  They use the real reactor and wait for real time.  To be fair, they took from a bad example sitting right next to them, but the 10 second delay is noticeably slow when running the tests.  Tests should always run quickly; it's important to be able to get through the whole suite as fast as is reasonable, so development doesn't bog down in endless waiting.

Rather than just shorten the delay though, I suggest you follow the example [set forth in the trial tutorial](http://twistedmatrix.com/documents/current/core/howto/trial.html) of how to test code that relies on time passing, with `twisted.internet.task.Clock`.

Please re-submit for review when you have tuned up the unit tests, and submit a patch against the branch I created rather than trunk.

-glyph

**Comment by twisted-trac** [comment]
|<img alt="luks's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_5"></a>|luks commented|
|-|-|

Thank you for the review.

I'm not 100% sure now, but I think it did not wait the full 10 seconds when I tested it. I wouldn't have submitted the patch with that. It does slow the tests now, so I'll fix it and add the new patch.

**Comment by twisted-trac** [comment]
|<img alt="luks's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_6"></a>|luks set owner to @glyph|
|-|-|

Ok, it turns out the patch wasn't correctly merged and the web-specific canceller wasn't called at all. However, the default canceller from `Deferred` was used, so it still raised the `CancelledError` exception. See the new patch with the missing change.

This means that the code it not in fact properly tested, but I'm afraid I do not know how to test it. The end result, with or without the specific canceller implementation, is the same -- the deferred raises `CancelledError`. The only thing that comes to my mind is a time-based test, e.g. if the client timeout is 10 seconds (can be lowered) and it took 10 or more seconds to raise the `CancelledError` exception, consider it a failure.

Do you have any ideas how to fix the tests?


Another problem is the `test_getPageCancelLater` which calls `callLater`. The `getPage` API doesn't have any kind of hook, where I could detect that I'm in the middle of a request, but it's not finished yet. I used 1ms as an estimate, but it's not an explicit test.

I think the `Clock` example will not help me, because when using `getPage`, I do not have access to the low level protocol and I'm not really testing timeouts. I'm testing if I can disconnect from the server in various stages of the connection and I want the disconnection to happen almost immediately after I call `d.cancel()`.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph removed owner|
|-|-|

I still might review this, but no reason somebody else shouldn't do it if I can't get to it soon.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_8"></a>|@itamarst set owner to luks|
|-|-|

The way to test this is to use a fake reactor (probably subclassing `twisted.test.proto_helpers.InMemoryReactor` and `Clock`). That way you can manually push the system through various stages and make sure cancellation happens correctly in each particular phase. For example, to test cancellation after connection was made, you would call buildProtocol on the factory in the reactor, and attach a `proto_helpers.StringTransport` to the protocol, then call `.cancel()`. Then you can write a deterministic, fast test for each possible place where cancellation may happen.

As you say, there's no way to get to the reactor right now. Therefore what you'll need to do is add an extra parameter to `twisted.web.client.getPage`, namely `reactor`, which defaults to current reactor and used by both `getPage` and the various classes (factory and protocol) it is integrated with.

**Comment by twisted-trac** [comment]
|[<img alt="itamarst's avatar" src="https://avatars.githubusercontent.com/u/3266662?s=50" width="50" height="50">](https://github.com/itamarst)<a name="note_9"></a>|@itamarst commented|
|-|-|

Oh, and of course some of the test may work by creating a protocol instance directly, rather than going via `getPage`.

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in #1683
