### ISSUE TITLE
twisted.web.http.Request.addCookie is untested

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6125]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#6125|
|Type|defect|
|Created|2012-10-16 13:24:19Z|

It should be tested (found while porting http.py to Python 3).

Attachments:

* [twisted6125.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/0c9/0c9bc17fff9b24104038a0b93419944f4dd0d7ee/3c9071d5052f0bf3f8cac1bbdf5d4248783c567b.patch) (1240 bytes) - added by canibanoglu on 2013-07-03 22:17:03Z - t.web.Request.addCookie now has complete test coverage.

<details><summary>Searchable metadata</summary>

```
trac-id__6125 6125
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__ 
branch__ 
branch_author__glyph glyph
status__new new
resolution__None None
component__web web
keywords__ 
time__1350393859000000 1350393859000000
changetime__1396676452000000 1396676452000000
version__None None
owner__canibanoglu canibanoglu
cc__jknight cc__thijs
```
</details>

**Comment by twisted-trac** [comment]
|<img alt="canibanoglu's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|canibanoglu set owner to canibanoglu|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="canibanoglu's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|canibanoglu set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|<img alt="canibanoglu's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">|canibanoglu removed owner<br>canibanoglu set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="thijstriemstra's avatar" src="https://avatars.githubusercontent.com/u/305679?s=50" width="50" height="50">](https://github.com/thijstriemstra)<a name="note_5"></a>|@thijstriemstra set owner to canibanoglu|
|-|-|

Thanks for this patch canibanoglu. Could you also

 1. Make the docstring for `twisted.web.http.Request.addCookie`:
   1. conform to the coding standard? So 1 line should be <= 80 chars
   1. Document the parameters using `@param` and `@type`
   1. ensure the actual code has proper spacing etc, for example:
```
cookie = cookie +"; Expires=%s" % expires
```
should be
```
cookie = cookie + "; Expires=%s" % expires
```

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph commented|
|-|-|

(In [42064]) Branching to service-identity-6125.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Sorry, that's the RFC number, not the ticket number.

**Comment by adiroiban** [comment]
We now have some tests first test was added here

https://github.com/twisted/twisted/commit/24caa9a597077a238e58c2b6fd43c0fefe9e4b3f#diff-8d107eb53fa9bbe99f33f0a15b37c9321e9883dd42b8e4a5ba6f69c9fd9d48c3

--------

and we now have more tests

https://github.com/twisted/twisted/blob/c465c460c68bec3cf481c2815d1039da6796eb03/src/twisted/web/test/test_http.py#L3066-L3122


I think that this can be closed.
