### ISSUE TITLE
prefer sha256 over md5 for tarball/installer signature file

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6187]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)| @teratorn reported|
|-|-|
|Trac ID|trac#6187|
|Type|defect|
|Created|2012-11-15 23:05:26Z|

The release process describes creating a signed manifest of md5 checksums for the various Twisted tarballs and installers produced during the release process. 

Here proposing to use sha256 sums instead.

AFAICT, this involves:

Updating http://twistedmatrix.com/trac/wiki/ReleaseProcess and replace the line
```
e.g. md5sum Tw* | gpg -a --clearsign > twisted-$RELEASE-md5sums.txt
```
with
```
e.g. sha256sum Tw* | gpg -a --clearsign > twisted-$RELEASE-sha256sums.txt
```

And upon the next release, update the wording near the bottom of this page, http://twistedmatrix.com/trac/wiki/Downloads to not refer explicitly to md5.

But really this step should be automated, so I'll file a new ticket for that feature. Marking this as a defect, since md5 is known to be defective.

<details><summary>Searchable metadata</summary>

```
trac-id__6187 6187
type__defect defect
reporter__teratorn teratorn
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1353020726000000 1353020726000000
changetime__1353020726000000 1353020726000000
version__None None
owner__ 
cc__radix
```
</details>

**Comment by adiroiban** [comment]
I think that this can be closed.

We no longer have custom tarballs.

We just use pypi.
