### ISSUE TITLE
Automate generation of md5 signature file during release process

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6188]
|[<img alt="teratorn's avatar" src="https://avatars.githubusercontent.com/u/154069?s=50" width="50" height="50">](https://github.com/teratorn)| @teratorn reported|
|-|-|
|Trac ID|trac#6188|
|Type|enhancement|
|Created|2012-11-15 23:10:23Z|

It would be really nice to automate the creation of the md5 sums signature file, e.g. twisted-12.2.0-md5sums.txt

Note also a proposal to use sha256 instead: [#6187](https://github.com/twisted/twisted/issues/6187)

See the manual process documented here: http://twistedmatrix.com/trac/wiki/ReleaseProcess

I haven't studied the release process enough to know where would be the right place to put this new script, or what tool should be modified to include this functionality (?)

<details><summary>Searchable metadata</summary>

```
trac-id__6188 6188
type__enhancement enhancement
reporter__teratorn teratorn
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1353021023000000 1353021023000000
changetime__1353021023000000 1353021023000000
version__None None
owner__ 
cc__radix
```
</details>

**Comment by adiroiban** [comment]
I think that this can be closed.

The files are released via PyPI.
