### ISSUE TITLE
trial -j should support tests which emit Unicode

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6865]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| lewq reported|
|-|-|
|Trac ID|trac#6865|
|Type|enhancement|
|Created|2013-12-07 16:29:21Z|
|Branch|https://github.com/twisted/twisted/tree/text-from-event-dict-safe-bytes-6865-2|

When trial -j is used to run tests which emit Unicode, an exception such as the following is often raised:

```
    test_sendingWaitingTimeout ... Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/python/log.py", line 191, in msg
    self.observers[i](actualEventDict)
  File "/Library/Python/2.7/site-packages/twisted/trial/_dist/workertrial.py", line 59, in emit
    self.protocol.callRemote(managercommands.TestWrite, out=text)
  File "/Library/Python/2.7/site-packages/twisted/protocols/amp.py", line 821, in callRemote
    return co._doCommand(self)
  File "/Library/Python/2.7/site-packages/twisted/protocols/amp.py", line 1778, in _doCommand
    self.requiresAnswer)
  File "/Library/Python/2.7/site-packages/twisted/protocols/amp.py", line 752, in _sendBoxCommand
    box._sendTo(self.boxSender)
  File "/Library/Python/2.7/site-packages/twisted/protocols/amp.py", line 577, in _sendTo
    proto.sendBox(self)
  File "/Library/Python/2.7/site-packages/twisted/protocols/amp.py", line 2153, in sendBox
    self.transport.write(box.serialize())
  File "/Library/Python/2.7/site-packages/twisted/protocols/amp.py", line 551, in serialize
    "Unicode value for key %r not allowed: %r" % (k, v))
exceptions.TypeError: Unicode value for key 'out' not allowed: u'Sending site-example.com to beta failed for reason timeout elapsed after being scheduled for reason asynchronouslyRunCheck'
[ERROR]
```

This is related to the fact that trial uses a log observer which writes the output of the logging system directly into AMP, which doesn't support Unicode in the codepath used here.

Attachments:

* [text-from-event-dict-safe-bytes-6865.patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f11/f111f376352dc911db43324cb1010603a820b93c/8fd3e29234800f4c4ef8ff3116e670b13535787f.patch) (4800 bytes) - added by lewq on 2013-12-07 16:35:07Z - Initial proposed patch against twisted trunk
* [text-from-event-dict-safe-bytes-6865.patch.2](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/f11/f111f376352dc911db43324cb1010603a820b93c/8bda35d9dddf0401403216090356a05566332cb6.2) (9061 bytes) - added by lewq on 2013-12-07 21:22:22Z - This patch is a completely new approach, which fixes the actual bugs in textFromEventDict which cause this issue

<details><summary>Searchable metadata</summary>

```
trac-id__6865 6865
type__enhancement enhancement
reporter__lewq lewq
priority__normal normal
milestone__ 
branch__branches_text_from_event_dict_safe_bytes_6865_2 branches/text-from-event-dict-safe-bytes-6865-2
branch_author__exarkun__rwall exarkun, rwall
status__new new
resolution__None None
component__core core
keywords__amp__unicode__workertrial amp, unicode, workertrial
time__1386433761000000 1386433761000000
changetime__1560774750394058 1560774750394058
version__None None
owner__lewq lewq

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_4"></a>|lewq commented|
|-|-|

Please review, particularly with respect to Python 3, since I'm not sure the implementation of safe_bytes is correct.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

(In [40941]) Branching to 'text-from-event-dict-safe-bytes-6865'

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @exarkun<br>@exarkun set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_8"></a>|@exarkun set owner to lewq<br>@exarkun set status to `new`|
|-|-|

Thanks!

  1. twisted/python/_reflectpy3.py
    1. `safe_bytes` does need to be a bit more sophisticated on Python 3 :/  For example, the result of `bytes(3)` on Python 3 is `b"\x00\x00\x00"`.  I'm not sure if other types are handled in a similarly insane way.  `str(o).encode("ascii")` might be simpler.
    1. On the other hand, now I'm confused about what behavior we should actually aim for on Python 3.  I think maybe https://twistedmatrix.com/documents/current/core/howto/python3.html#auto3 is saying we should actually produce unicode in log events - which perhaps implies `str(o)` is right on both Python 2 and Python 3 and we can forget about `bytes(o)`.
    1. But matters aren't helped at all by the apparent lack of testing of the various corner cases.  Some tests are failing on the Python 3.3 builder, <https://buildbot.twistedmatrix.com/builders/python-3.3-tests/builds/1708/steps/shell/logs/stdio>, but none of the failures seem related to the subtleties in `safe_bytes`...  So perhaps `textFromEventDict` needs another test or two.
    1. Oops no disregard that.  Th...

Oops.  There are some more complicated issues relating to how disttrial really always wants bytes by the normal single-process logging case wants native strings.  Also Luke just tested the branch and the original problem still seems to happen so for some reason the bug isn't actually fixed.  Re-assigning to Luke for further work.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_9"></a>|@exarkun commented|
|-|-|

Here are some interesting observations (note that `L[-1]` is "the last log event"):

```
>>> msg(format="hello %(n)s", n=u"world \N{SNOWMAN}")
>>> textFromEventDict(L[-1])
u'hello world \u2603'
>>> msg(format=u"hello %(n)s", n="world \N{SNOWMAN}")
>>> textFromEventDict(L[-1])
u'hello world \\N{SNOWMAN}'
>>> err(Failure(Exception("world")), u"hello")
hello
Traceback (most recent call last):
Failure: exceptions.Exception: world
>>> textFromEventDict(L[-1])
u'hello\nTraceback (most recent call last):\nFailure: exceptions.Exception: world\n'
```

**Comment by twisted-trac** [comment]
|<img alt="lewq's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_10"></a>|lewq commented|
|-|-|

Please review the patch in text-from-event-dict-safe-bytes-6865.patch.2

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_11"></a>|@wallrj commented|
|-|-|

(In [40956]) Branching to 'text-from-event-dict-safe-bytes-6865-2'

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_12"></a>|@wallrj commented|
|-|-|

(In [40959]) Apply text-from-event-dict-safe-bytes-6865.patch.2 from lewq. Refs [#6865](https://github.com/twisted/twisted/issues/6865)

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_13"></a>|@wallrj commented|
|-|-|

Thanks Luke,

I'm not too familiar with this code, so treat this as a cosmetic code review.

Jp and Tom both seem happy with the latest approach though.

Notes:
 * Patch applies cleanly
 * Applied to clean branch log:branches/text-from-event-dict-safe-bytes-6865-2
 * Tests all pass locally
 * Build results
   * http://buildbot.twistedmatrix.com/boxes-supported?branch=/branches/text-from-event-dict-safe-bytes-6865-2

Points:
 1. Python3 build errors - as you suspected
    1. https://buildbot.twistedmatrix.com/builders/python-3.3-tests/builds/1715/steps/shell/logs/stdio
 2. Some long lines reported by twistedchecker
    1. https://buildbot.twistedmatrix.com/builders/twistedchecker/builds/1576/steps/run-twistedchecker/logs/new%20twistedchecker%20errors
 3. [twisted/python/log.py](twisted/python/log.py)
    1. `% fmtDict` - the variables need to be in a tuple (https://twistedmatrix.com/documents/current/core/development/policy/coding-standard.html#auto8)
    2. `text = str(fmtString % fmtDict)` - wasn't sure about the use of str
       here? I'd have thought twisted.python.compat.nativeString. But I see Jp
       recommended str, so perhaps just add a comment about that choice.
    3. `@return` - Use L{} instead of C{} for builtin types (str, bytes, unicode)
 4. [branches/text-from-event-dict-safe-bytes-6865-2/twisted/test/test_log.py](branches/text-from-event-dict-safe-bytes-6865-2/twisted/test/test_log.py)
    1. MeltingSnowmanException
       1. No need for the pass statement since the function has a docstring.
    2. setUp
       1. needs a short docstring.
    3. TextFromEventDictTests
       1. `# Workaround brain-deadness` - maybe add an little more explanation of this hack
       2. Looks like the hack may not work  / may not be needed in Python3.
       3. jp mentioned that gtkreactor doesn't work on python3 anyway.
       4. Also remove the print statment
       5. Anyway to reverse the changes - maybe an addCleanup function to return
          the default encoding to its original value.
    4. test_simpleMessageBytes
       1. docstring needs expanding.
       2. Combine the assertions by comparing type and value as a tuple
       3. Or implement a custom assertion called assertTypeEqual

Please resubmit for review after addressing or answering the numbered points
above. Also just commit changes directly to the new branch, force a buildbot run
and link to some clean build results.

Thanks again.

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)|@wallrj set owner to @wallrj|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="wallrj's avatar" src="https://avatars.githubusercontent.com/u/978965?s=50" width="50" height="50">](https://github.com/wallrj)<a name="note_15"></a>|@wallrj set owner to lewq|
|-|-|

Just claiming my review points :) Sorry for the noise.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_17"></a>|@exarkun commented|
|-|-|

I wonder if [#9378](https://github.com/twisted/twisted/issues/9378) was a duplicate of this.

**Comment by glyph** [comment]
Pretty sure that this got addressed somewhere on the way to Python 3.
