### ISSUE TITLE
Use CFRunLoopRemoveSourceInvalidate instead of CFRunLoopRemoveSource in CFReactor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#6960]
|<img alt="BobNovas's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| BobNovas reported|
|-|-|
|Trac ID|trac#6960|
|Type|defect|
|Created|2014-02-10 18:28:12Z|

If you are using CFReactor, and doing your own IO (in particular, using 
pybonjour and adding your file descriptor to the reactor's reader list
(e.g., reactor.addReader), then, if you close the file descriptor before
you call removeReader, on some platforms (Lion) you will likely wind up
in CFRunLoopRemoveSource in a spinlock waiting on the FD.  The solution is 
either to ensure that you call removeReader before closing the FD, or
CFReactor could solve the problem by using CFRunLoopRemoveSourceInvalidate
instead of CFRunLoopRemoveSource at line 300.

See http://icodeanswer1.appspot.com/post/709526 and attached crash
report.txt file.

Attachments:

* [crashreport.txt](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/708/70875fe7aa9f60b30f01f4a2c8562bc257eed414/0305b3aa7c246fc0949d1996ea3af993ef1af85c.txt) (64261 bytes) - added by BobNovas on 2014-02-10 18:29:26Z - Typical hang showing spinlock in CFRunLoopRemoveSource

<details><summary>Searchable metadata</summary>

```
trac-id__6960 6960
type__defect defect
reporter__BobNovas BobNovas
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__cfreactor__spin_lock__CFRunLoopRemoveSource cfreactor, spin lock, CFRunLoopRemoveSource
time__1392056892000000 1392056892000000
changetime__1392056892000000 1392056892000000
version__None None
owner__ 

```
</details>

**Comment by glyph** [comment]
Perhaps this is a clue to #11771 's cause

**Comment by glyph** [comment]
I *think* this is referring to `CFRunLoopSourceInvalidate` since there doesn't seem to be a `CFRunLoopRemoveSourceInvalidate` in the API

**Comment by glyph** [comment]
Given that this specifically mentions Lion, and we have tests for this sort of FD shenanigans for other platforms, I don't think that this report is necessarily valid any more.  If this is still an issue I really hope someone will re-report it, but given how much I use CFReactor these days, I think I will eventually bump into it if so.  (Although really, `removeReader` before closing the FD is really the application's responsibility, dealing with closed FDs like this can only be done heuristically.)
