### ISSUE TITLE
Allow building apidocs for a sub-project or a single file

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7010]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#7010|
|Type|enhancement|
|Created|2014-02-28 16:27:10Z|

When I change some epydoc documentation I would like to see the result.

Right now, this means building whole documentation.

It would be nice to be able to call apidocs generation for a single file or at least a folder.

I have attached a patch which does a quick prototype

```
# Should produce the same result as previous version.
./bin/admin/build-apidocs . apidocs

# Will only generate apidoc for twisted/web/proxy.py file
./bin/admin/build-apidocs twisted/web/proxy.py apidocs

# Will only generate apidoc for twisted/web sub-project
./bin/admin/build-apidocs twisted/web apidocs
```

As a final result, I would like to be able to call the command as:

```
./bin/admin/build-apidocs --output-dir=apidocs twisted/sub/file.py twisted/file2.py
```

In this way I can use the VC system to get a list of files changes since origin/trunk and run apidocs only on those files.

What do you think?

Does it make sense?

Do you find it useful?

Is there a better way to get the same result?

Maybe this should not be an admin command.

Thanks!

Attachments:

* [7010-1.diff](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/4e6/4e65779f12f2a55487db9f94a8c088a611d9c628/b05d5fa9759ab31eb6296459a21b53b180d0cc63.diff) (1731 bytes) - added by adiroiban on 2014-02-28 16:29:33Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__7010 7010
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__ 
time__1393604830000000 1393604830000000
changetime__1393667367000000 1393667367000000
version__None None
owner__adiroiban adiroiban
cc__radix
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban commented|
|-|-|

I have attached a quick hack, but based on feedback from initial review I would like to do a full implementation.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

What does this do when the included files contain links to APIs defined by excluded files?

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_5"></a>|@adiroiban set owner to @adiroiban|
|-|-|

In current version it receives an 'invalid ref to' error.

... will think at a way to fix these kind of errors... maybe this would require a patch in pydoctor.


One reason why I want to run pydoctor on specific files/folders to that I could start  fixing all errors in twisted projects and have a clean build.

But like you said, maybe running full build is faster in this case.

Another reason why I want this is to have a very fast pydoctor which can run only on files changed during development of a branch. 

Thanks for the feedback!

**Comment by adiroiban** [comment]
This should be closed as wont-fix

with pydoctor is hard to do this...as you will end up with invalid/missing links
