### ISSUE TITLE
Twisted should provide the `--output-pickle` pydoctor generates.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7018]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)| @tomprince reported|
|-|-|
|Trac ID|trac#7018|
|Type|enhancement|
|Created|2014-03-04 00:57:34Z|
|Branch|https://github.com/twisted/twisted/tree/pydoctor-system-pickle-7018|

Pydoctor supports cross-project links, by using the generated `System` object. To make it easier for other projects to link to our documentation, we should generate and publish that pickle.

<details><summary>Searchable metadata</summary>

```
trac-id__7018 7018
type__enhancement enhancement
reporter__tom_prince tom.prince
priority__normal normal
milestone__ 
branch__branches_pydoctor_system_pickle_7018 branches/pydoctor-system-pickle-7018
branch_author__tomprince tomprince
status__new new
resolution__None None
component__core core
keywords__documentation documentation
time__1393894654000000 1393894654000000
changetime__1393895957000000 1393895957000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_1"></a>|@tomprince commented|
|-|-|

(In [41804]) Branching to pydoctor-system-pickle-7018.

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_2"></a>|@tomprince commented|
|-|-|

This would be ready for review, if pydoctor could actually load the generate file (https://bugs.launchpad.net/pydoctor/+bug/1287458)

**Comment by adiroiban** [comment]
I think that this should be closed.

pydoctor now uses intersphinx object inventory.
