### ISSUE TITLE
pydoctor reports invalid ref to OpenSSL.SSL.Context

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7034]
|[<img alt="lvh's avatar" src="https://avatars.githubusercontent.com/u/97816?s=50" width="50" height="50">](https://github.com/lvh)| @lvh reported|
|-|-|
|Trac ID|trac#7034|
|Type|enhancement|
|Created|2014-03-14 16:20:25Z|

The pydoctor reports are rife with these, for example:

```
twisted.internet._sslverify._OpenSSLECCurve.addECKeyToContext: invalid ref to OpenSSL.SSL.Context 
```

I think pydoctor is supposed to support this, perhaps this is just because the buildbot has no access to PyOpenSSL; perhaps we should install PyOpenSSL on the builder?

I'm tentatively filing this under pydoctor, but I'm not sure if it's actually a pydoctor bug, or perhaps there should be a bug on one of the Github repos.

<details><summary>Searchable metadata</summary>

```
trac-id__7034 7034
type__enhancement enhancement
reporter__lvh lvh
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__pydoctor pydoctor
keywords__ 
time__1394814025000000 1394814025000000
changetime__1394814025000000 1394814025000000
version__None None
owner__ 
cc__mwh
```
</details>

**Comment by adiroiban** [comment]
I think that this is now fixed via  docs/conf.py

```
    "--intersphinx=https://pyopenssl.readthedocs.io/en/stable/objects.inv",
```
