### ISSUE TITLE
It isn't clear how to deprecate a class.

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7147]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)| @tomprince reported|
|-|-|
|Trac ID|trac#7147|
|Type|enhancement|
|Created|2014-04-15 04:38:09Z|

[#6044](https://github.com/twisted/twisted/issues/6044) used warnings.warn by hand to deprecate `twisted.internet.defer.waitForDefered` by reporting a warning in `__init__`. `twisted.python.deprecate.deprecated` doesn't work, since that would include `__init__` in the name being deprecated.

<details><summary>Searchable metadata</summary>

```
trac-id__7147 7147
type__enhancement enhancement
reporter__tom_prince tom.prince
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__documentation documentation
time__1397536689000000 1397536689000000
changetime__1397954741000000 1397954741000000
version__None None
owner__ 

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

I think the words in the ticket summary are wrong and the ticket description doesn't *quite* make it clear what the issue is here.

My guess is that this is about deprecating a whole class and that the issue is that:

```python
class Foo:
    @deprecated(...)
    def __init__(self):
        pass
```

does not produce wholly desirable results.

If this is the case, then I suggest the answer is:

```python
class Foo:
    ...

deprecatedModuleAttribute(version, "replacement recommendation", __name__, "Foo")
```

Very likely `deprecatedModuleAttribute` is preferable to `deprecated` in most other cases as well since it will trigger a deprecation warning if the name is even accessed rather than requiring it actually be called.  This is likely to produce the warning more reliably (though still not 100%) in a code base with less than perfect test coverage.

So presumably some documentation about the deprecation process should be updated to include this information.

Editing the ticket summary to reflect this interpretation, if it is incorrect please make some further edits.

**Comment by twm** [comment]
I think that the current [entry in the compatibility policy on deprecating classes](https://docs.twisted.org/en/stable/development/compatibility-policy.html#classes) covers this and is in line with @exarkun's suggestions, so closing this as completed.
