### ISSUE TITLE
getPage still isn't going to verify HTTPS URLs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7243]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#7243|
|Type|defect|
|Created|2014-04-23 22:07:53Z|

[#4888](https://github.com/twisted/twisted/issues/4888) doesn't fix older APIs.  They should probably also verify stuff, because there's no high-level API on top of the new thing yet, so they're not deprecated, and lots of examples use them.

<details><summary>Searchable metadata</summary>

```
trac-id__7243 7243
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__ 
time__1398290873000000 1398290873000000
changetime__1398380145000000 1398380145000000
version__None None
owner__ 
cc__jknight
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Replying to [rwall](#note_52):
> Glyph, here's a quick and dirty review while I wait for a flight. I'll try and make some more thorough notes later (unless someone gets there first)
> 
> Points:
>  1. [branches/redux-4888/twisted/web/client.py](branches/redux-4888/twisted/web/client.py)
>     1. Missing epydocs: https://buildbot.twistedmatrix.com/builders/twistedchecker/builds/2047/steps/run-twistedchecker/logs/new%20twistedchecker%20errors

Aside from these, there are spurious twistedchecker errors yet again.

I filed https://github.com/twisted/twistedchecker/issues/76 for `set_connect_state` (which is the only unfixable one) and https://github.com/twisted/twistedchecker/issues/75 for the inner-class stuff which I've worked around.

>     2. The CreatorCreator suffix seems very confusing (as noted earlier) your suggested name seems better.

Right-o.  Name changed.

>  2. [branches/redux-4888/twisted/web/test/test_agent.py](branches/redux-4888/twisted/web/test/test_agent.py)
>     1. Build Failures due to OpenSSL import errors - please fix
>        1. https://buildbot.twistedmatrix.com/builders/debian-easy-no-zope-py2.6-epoll/builds/1862/steps/epoll/logs/problems
>        2. https://buildbot.twistedmatrix.com/builders/debian-easy-old-zope-py2.6-epoll/builds/1857/steps/epoll/logs/problems
>        3. https://buildbot.twistedmatrix.com/builders/py-without-modules/builds/2456/steps/trial/logs/problems
>        4. https://buildbot.twistedmatrix.com/builders/windows7-64-py2.7/builds/3872/steps/iocp/logs/problems

These all seem to be the same failure.  Perhaps more of our build farm should have pyOpenSSL installed?  There's really just supposed to be the one builder without optional dependencies, I thought.

>     2. Missing epydocs - please fix the important ones: https://buildbot.twistedmatrix.com/builders/twistedchecker/builds/2047/steps/run-twistedchecker/logs/new%20twistedchecker%20errors

I think these should all be fixed now, important or not :).

>     3. Add a test for the deprecation of t.w.c.WebClientContextFactory

Hmm.  While I'm at it, I think this should probably be using deprecatedModuleAttribute, actually; at least until the tickets referenced by ticket:4804#comment:15 are addressed.

And then when I tried to do the right thing here I discovered [#7242](https://github.com/twisted/twisted/issues/7242) as well, and filed it; you can see the comment in the test code.

>  3. Missing news file

Added.

I also added a formal interface because all these silly half-finished
looks-kinda-like-this-one-weird-class types are a bad idea and I should stop
putting them into public interfaces.

Last time when I put it up for review I knew it was in kinda bad shape and I
wanted feedback before putting more effort in; this time I think it's probably
ready to go.

I also filed [#7243](https://github.com/twisted/twisted/issues/7243) for other APIs.  Hopefully that's a duplicate of something?

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph commented|
|-|-|

Blah, wrong ticket :(

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_4"></a>|@exarkun commented|
|-|-|

I wonder what remaining issues prevent `getPage` from being reimplemented on top of `Agent`.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_4):
> I wonder what remaining issues prevent `getPage` from being reimplemented on top of `Agent`.

That would certainly be an _awesome_ way to fix this.

I thought there were parts of the `getPage`/`downloadPage` interface - particularly the who-knows-what "`**kwargs`" piece - that made it impossible to replicate completely?

We could just deprecate the use of that, if it's not important...

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_6"></a>|@exarkun commented|
|-|-|

I think we were just waiting for the `IAgent` implementations to reach feature parity with `HTTPClientFactory` and `HTTPDownloader`.  That might have happened when we weren't looking.

Let's see.  The features of `getPage` are:

  1. Specify the URL (`Agent.request`, check)
  1. Specify the method (`Agent.request`, check)
  1. Specify some data to upload (`Agent.request`, `FileBodyProducer`, check)
  1. Specify the header (`Agent.request`, check)
  1. Specify the User-Agent (`Agent.request`, check)
  1. Specify a request timeout (distinct from the connect timeout) (`reactor.callLater`, `Deferred.cancel`, check)
  1. Specify some cookies (`CookieAgent`, check)
  1. Control redirect following behavior (`RedirectAgent` or maybe `BrowserLikeRedirectAgent`, check)
  1. Impose a limit on how many redirects to follow (`RedirectAgent`, etc, check)
  1. `afterFoundGet` - this is more redirect control behavior, I think the choice of which redirect `IAgent` implementation you use lets you implement the feature this flag represents (check)
  1. Additionally, `downloadPage` has features for writing the result to the filesystem and resuming interrupted downloads.  These can be implemented in terms of existing `IAgent` APIs but aren't directly supported by them.  Still, there should be a net reduction in code if we reimplemented `downloadPage` on top of `IAgent`.

So... yea, actually, it looks like the `IAgent` universe has reached parity.

We *could* simply deprecate `getPage` and `downloadPage` but it might be gentler on users to leave the old interface.  I don't feel strongly either way but it does seem feasible to just swap out the implementation.  It might also be a nice way to get everyone onto `IAgent` sooner rather than later (less work for application developers is kind of yay).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_7"></a>|@glyph commented|
|-|-|

Thanks a ton for enumerating this.  I'm honestly not familiar with all the ins and outs of either the old _or_ the new HTTP client APIs so this list was tremendously informative to me.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_8"></a>|@glyph commented|
|-|-|

Replying to [exarkun](#note_6):

> We *could* simply deprecate `getPage` and `downloadPage` but it might be gentler on users to leave the old interface.  I don't feel strongly either way but it does seem feasible to just swap out the implementation.  It might also be a nice way to get everyone onto `IAgent` sooner rather than later (less work for application developers is kind of yay).

So, I still frequently use `getPage` in examples, because using `Agent` is considerably wordier.  I think we could probably have a version that took a `reactor` without making it too tedious, but more than that would start to be burdensome.  (Particularly I want to have a tool for examples that doesn't involve typing a string like `"GET"` which you might get wrong.  `something.get`, treq-style, might be an OK way to work around that.)

I'm not sure if you were referencing what I was proposing or not, but what I was saying was that we could deprecate use of `**kwargs`, not `getPage` itself.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_9"></a>|@glyph commented|
|-|-|

Based on your list though, it sounds like we don't _need_ to deprecate ``**kwargs``, we could just literally implement all of the features exposed thereby.

**Comment by adiroiban** [comment]
I am closing this as the getPage API was removed in #1683
