### ISSUE TITLE
str() of delayedcall instances failed when call is a method-of-a-builtin

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#7891]
|[<img alt="moshez's avatar" src="https://avatars.githubusercontent.com/u/422703?s=50" width="50" height="50">](https://github.com/moshez)| @moshez reported|
|-|-|
|Trac ID|trac#7891|
|Type|defect|
|Created|2015-05-11 03:02:51Z|

See attachment. When running it, I get (edited whitespace for wiki reasons, no other editing):

  15.1.0 sys.version_info(major=2, minor=7, micro=8, releaselevel='final', serial=0)
  Traceback (most recent call last):
    File "froop", line 9, in <module>
      str(t)
    File "/home/moshez/src/ncolony/build/.tox/py27-unit/local/lib/python2.7/site-packages/twisted/internet/base.py", line 182, in __str__
      func = self.func.func_name
  AttributeError: 'builtin_function_or_method' object has no attribute 'func_name'

Attachments:

* [froop](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/7a3/7a3748d4f3ad1fcf6f5efb81db9ed3c465b581f1/258bca98e2e0b564f31c6bee6827f3db644a5469) (161 bytes) - added by moshez on 2015-05-11 03:03:20Z - Bug reproduction

<details><summary>Searchable metadata</summary>

```
trac-id__7891 7891
type__defect defect
reporter__moshez moshez
priority__normal normal
milestone__ 
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__ 
time__1431313371584526 1431313371584526
changetime__1431313371584526 1431313371584526
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
#9061 was a duplicate of this and the issue was fixed in #10155.
