### ISSUE TITLE
No windows wheels for win32

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8314]
|<img alt="techtonik's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| techtonik reported|
|-|-|
|Trac ID|trac#8314|
|Type|release blocker: release process bug|
|Created|2016-05-02 13:08:20Z|

https://pypi.python.org/pypi/Twisted misses win32 binaries, because Windows XP build bot was decommissioned. Need to get them back again.

As an alternative to automating Windows, it might be possible to try https://mingwpy.github.io/ in cross-compiler mode on Linux.

<details><summary>Searchable metadata</summary>

```
trac-id__8314 8314
type__release_blocker__release_process_bug release blocker: release process bug
reporter__techtonik techtonik
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__None None
time__1462194500857338 1462194500857338
changetime__1501244446916504 1501244446916504
version__None None
owner__None None
cc__radix
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="altendky's avatar" src="https://avatars.githubusercontent.com/u/543719?s=50" width="50" height="50">](https://github.com/altendky)<a name="note_2"></a>|@altendky commented|
|-|-|

Possible duplicate of:

http://twistedmatrix.com/trac/ticket/9217
Distribute 32-bit windows wheels

**Comment by adiroiban** [comment]
duplicate of #9217 which is closed.

Also, we have separate packages for C extensions for Windows.
