### ISSUE TITLE
serverFromString parsing should support unicode on python2

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8422]
|[<img alt="Laharah's avatar" src="https://avatars.githubusercontent.com/u/539998?s=50" width="50" height="50">](https://github.com/Laharah)| @Laharah reported|
|-|-|
|Trac ID|trac#8422|
|Type|defect|
|Created|2016-06-04 18:06:01Z|

Currently, twisted.internet.endpoints.serverFromString only accepts bytes on python2 and only accept unicode on python3. This makes it hard to specify a server string in a cross version app trying to support unicode internally.

I've written a failing test and a patch/PR that fixes the issue: https://github.com/twisted/twisted/pull/141

<details><summary>Searchable metadata</summary>

```
trac-id__8422 8422
type__defect defect
reporter__Laharah Laharah
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1465063561313231 1465063561313231
changetime__1469404233795090 1469404233795090
version__None None
owner__Laharah Laharah

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban set owner to @Laharah|
|-|-|

Hi and many thanks for your contribution.

1. The new test does not uses any non-ascii input value.

I don't understand what part of the Twisted API is hard to be used in a cross version app.

You can always encode the string in utf-8 (or other encoding) before passing them to the endpoint.

--------

2. Can you please also update the test to make sure that the SSL and unix server endpoints will still work after this changes.

I am aware that some pyOpenSSL arguments only work if they are passed as bytes.

Also, on Unix when the LANG env variable has different values at least on Python2, python will perform on-the-fly encoding which will not always produce the right results.

-------

3. This looks like an important new capability/feature. I think that the topfile news fragment should be a .feature and not a .misc


Please review my comments and resubmit.

I think that the coverage needs to be extended.

Many thanks again for your contribution!

**Comment by twisted-trac** [comment]
|[<img alt="Laharah's avatar" src="https://avatars.githubusercontent.com/u/539998?s=50" width="50" height="50">](https://github.com/Laharah)<a name="note_3"></a>|@Laharah commented|
|-|-|

Replying to [adiroiban](#note_1): 
> 1. The new test does not uses any non-ascii input value.
> 
> I don't understand what part of the Twisted API is hard to be used in a cross version app.


I've updated the tests to check for explicit unicode characters and ssl

I think I may have phrased the ticket poorly and have changed the title. This change doesn't actually add any new functionality to serverFromString, as unicode is already implicitly supported when using serverFromString on python3. Rather this patch extends that support to python2 as well. 

The usecase that brought this up is that the same representation of a server string could not be used for both py2 and py3 if you are trying to be internally consistent (for example a `from __future__ import unicode_literals`).

At current you either have to allow py2 and py3 to use their own str literals or maintain two server strings as such:

```python
from __future__ import unicode_literals
import sys
from twisted.internet.endpoints import serverFromString

if sys.version_info.major < 3:
    server = serverFromString(reactor, b"tcp:%d" % port)
else:
    server = serverFromString(reactor, "tcp:%d" % port)
```

I'm leaving the top file marked as misc since the patch only brings py2 into parity with py3. If you still think it should be changed let me know and I'll fix it.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_5"></a>|@adiroiban commented|
|-|-|

Thanks for the update!

Thanks for clarifying the ticket.

I would say that we should update Python3 to support bytes in serverFromString :)

Picking an encoding is complicated as for a domain you might have idna, while for a path you might have UTF-8 on Windows/OSX ... or on Unix/Linux any imaginable encoding.  

I saw that in trunk description is of type `str` but until 15.3.0 it was bytes

https://twistedmatrix.com/documents/15.3.0/api/twisted.internet.endpoints.html#serverFromString

the change was made here [#7982](https://github.com/twisted/twisted/issues/7982) and I was the one reviewing it.

I would say that serverFromString should support both bytes and Unicode ... but will need to check with Amber

Meanwhile, I think that is ok to add Unicode support for Python2 :)

------------

Here are my comments for the current patch.

1. While it is not a change for python3, it is a change for python2 as we now have Unicode support in python2. I think that this is newsworthy :)

2. Please split the current test into 3 separate tests.

If later we add a new endpoint, that endpoint should come with a dedicated test for unicode and should not update the existing test.

3. Can we use isinstance instead of type(x) == y ? this looks close to what we are actually testing there

4. escapedPEMPathName has no non-ascii characters in its name

5. tcp endpoint test has no non-ascii characters

6. the unix domain tests (and maybe also the other tests) should be executed when the LANG env is C or any non Unicode locale.


Please check my comments and resubmit for review.

Thanks!

**Comment by twisted-trac** [comment]
|[<img alt="Laharah's avatar" src="https://avatars.githubusercontent.com/u/539998?s=50" width="50" height="50">](https://github.com/Laharah)<a name="note_6"></a>|@Laharah commented|
|-|-|

Replying to [adiroiban](#note_5):
> Please check my comments and resubmit for review.
> 
> Thanks!

I've split the tests up and added unicode characters to the interface declarations of the SSL and TCP strings. I also added a test that re-tries each of my tests with the environment var $LANG set to "C". 

I also switched the code to use isInstance and changed the top file to .feature

\\
>I would say that serverFromString should support both bytes and Unicode ... but will need to check with Amber

I originally tried to add bytes support to serverFromString on python3 but the python3 bytes type doesn't support the string manipulation functions that the parser requires, it would have to convert the bytes back into unicode to parse them, which seemed like a waste of time. Besides, implicit string conversion almost always seems to get messy.

Let me know if anything else needs to be changed!

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_7"></a>|@adiroiban commented|
|-|-|

1. the .feature file needs a content which will be part of the release notes. 

see a few examples here http://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

2. from the test, I can see that those values are just parsed, but not really used.
I think that the tests should do a endpoint.listen() call to make sure that those values are correctly translated into something that can be used by the OS.

for example, for the DNS names, I want to make sure that unicode is successfully translated into idna, even on Python 2.7 

Is ok to keep these for severFromString as they are, as long as we have separate tests using unicode on python 2.7 for each endpoint ... ex for TCP4ServerEndpoint
 

In ServerEndpointTestCaseMixin I don't see any tests using unicode values https://github.com/twisted/twisted/blob/trunk/twisted/internet/test/test_endpoints.py#L560

It might be nice to update the current documentation for serverFromString to include  few examples. Then I could use those examples for a few manual test to check that all is ok

The current server-side endpoint documentation is brief 
https://github.com/twisted/twisted/blob/trunk/docs/core/howto/endpoints.rst


I also see that test_unixUnicode uses a fake reactor so that unicode value is actually never passed to the OS.

-------

Have you tested this code on Python 2.7 with unicode - non-ascii values? Does it work?

Please consider adding a few examples which can be used for manual testing.

I have created a simple example on gist here https://gist.github.com/adiroiban/609065fc492925b575f218cd6d47d9f5

on your branch, it fails on Python2.7 when LANG=C. As expected.

To understand why it fails you can consider reading http://lucumr.pocoo.org/2014/5/12/everything-about-unicode/ 
or other blog post explaining the unicode implicit encoding in py 2.7 :(

**Comment by twisted-trac** [comment]
|[<img alt="Laharah's avatar" src="https://avatars.githubusercontent.com/u/539998?s=50" width="50" height="50">](https://github.com/Laharah)<a name="note_8"></a>|@Laharah commented|
|-|-|

Sorry it took so long to get back to this. I didn't have a linux machine to test this on, only my OSX laptop, where the LANG=C env variable has no effect. Indeed the gist you linked fails when LANG=C on linux, however it fails on both python2 and python3. 

As I said, the point of this patch was to simply to make python2 and python3 accept and parse the same unicode string in the same consistent way. I would consider the LANG=C issue a separate, unrelated, bug. I'm willing to try and work on it, but I don't have easy access to a linux dev environment to properly test my changes.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_9"></a>|@adiroiban commented|
|-|-|

You don't need access to a Linux system.
We now have Travis-CI which runs on Linux.
You can write tests and have them executed on Linux.

If you think that Unicode error is a different bug, please create a ticket for it.

I still think that the tests should be written in such a way that they hit the OS... as just parsing it will not reveal any bugs and will not prove that the parse value actually works.

I still think that you should add a simple example which can be use to manually demonstrate how this fails on trunk and how it pass on your branch.

---------

If you want to have this PR merged as it is now, please put it for review.

**Comment by twisted-trac** [comment]
|[<img alt="Laharah's avatar" src="https://avatars.githubusercontent.com/u/539998?s=50" width="50" height="50">](https://github.com/Laharah)<a name="note_10"></a>|@Laharah commented|
|-|-|

Replying to [adiroiban](#note_9):
> I still think that the tests should be written in such a way that they hit the OS... as just parsing it will not reveal any bugs and will not prove that the parse value actually works.
>

Well, all the serverFromString tests function as unit tests for the parser, it seems that putting what amounts to an integration test there would be out of place. But I could add unicode to the UNIXEndpointsTests to ensure that they run correctly even when they hit the OS. I'm not sure how I would add unicode to the TCP and SSL endpoints tests though. The OS would have to have an interface with unicode characters in its name, and I'm not sure how exactly that would work.

**Comment by twisted-trac** [comment]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)<a name="note_11"></a>|@Julian commented|
|-|-|

IMHO, typically this issue is a reason to avoid `from __future__ import unicode_literals` rather than extending the API.

**Comment by twm** [comment]
Closing this as we no longer support Python 2, and `serverFromString` operates on Python 3's `str`.
