### ISSUE TITLE
Cleanup after coverage publish changes

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8599]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#8599|
|Type|enhancement|
|Created|2016-07-13 19:16:14Z|

So we have [#8598](https://github.com/twisted/twisted/issues/8598) which add support for sending coverage from tox.

... but the old code for sending coverage from a custom buildbot step is still kept.

Then we have https://github.com/twisted-infra/braid/issues/209 to update build to use tox.

after buildbot is deployed, we can update trunk to clean the code which is no longer used

<details><summary>Searchable metadata</summary>

```
trac-id__8599 8599
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1468437374245335 1468437374245335
changetime__1468437374245335 1468437374245335
version__None None
owner__adiroiban adiroiban

```
</details>

**Comment by twm** [comment]
We are currently sending coverage on failures, so closing this.
