### ISSUE TITLE
Run a single tox environment per Travis job

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8737]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)| @adiroiban reported|
|-|-|
|Trac ID|trac#8737|
|Type|enhancement|
|Created|2016-08-09 10:55:46Z|

Right now we are almost there with a few exceptions.

* coverage-publish is a separate env so that we can publish coverage even if the test failed in tox

* static-checkers are aggregated into a single job as a legacy of tox-travis and as a way to speed up the container startup time + cache init + other setup things

Glyph wants to have a Travis-CI build matrix like rackspace/mimic https://github.com/rackerlabs/mimic/blob/master/.travis.yml#L12

<details><summary>Searchable metadata</summary>

```
trac-id__8737 8737
type__enhancement enhancement
reporter__adiroiban adiroiban
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1470740146304779 1470740146304779
changetime__1470830290587957 1470830290587957
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

For coverage-publish we can create an admin/ci_coverage_run.py script which will run trial and will also call coverage

so maybe we should use tox just for virtualenv creation and have external scripts for doing the actual command run

-------

for the static checkers, we can do something similar, by having admin/ci_static_checker.py script which will run each check and will present the general results in an easy to read way

but meanwhile we can break the static-checker into separate jobs

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

Thanks for writing this ticket up, Adi.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban commented|
|-|-|

Having a container started / cache download and tox installed using the Travis-CI step takes between 30 to 40 seconds.... OSX takes 60 seconds

Right now we have 5 tox environments in the static checkers job.

So we we split them as individual jobs we will have an overhead between 120 and 160 seconds... this looks like a lot of time 

Also, the output from all those 5 environments is pretty brief and if we somehow we can make tox less verbose, the log will be cleaner

https://travis-ci.org/twisted/twisted/jobs/150803035

42 second after install - https://travis-ci.org/twisted/twisted/jobs/150803031

At this point I think that keeping the current job structure is ok...

also, maybe in the future we will start using flake8 or pylama or the defunct pocket-lint used by the Launchpad project and by me :) ... so then we will end up with a single tox env anyway

**Comment by adiroiban** [comment]
I think this can be closed as we no longer use Travis.
