### ISSUE TITLE
The twisted.test.test_main.MainTests.test_twisted test method is flaky

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8923]
|[<img alt="freeekanayaka's avatar" src="https://avatars.githubusercontent.com/u/598445?s=50" width="50" height="50">](https://github.com/freeekanayaka)| @freeekanayaka reported|
|-|-|
|Trac ID|trac#8923|
|Type|enhancement|
|Created|2016-11-26 11:09:31Z|

The assertion that makes sure that the help output is the same both when invoking the code with "python3 -m twisted --help" and when using TwistedOptions directly is flaky, because there's effectively no guarantee that the call to reflect.addMethodNamesToDict(self.__class__, dct, "opt_") in twisted.python.usage.Options._gather_handlers() will end up with a stable ordering of dct.keys() (which the above assertion indirectly relies on).

I'm not sure why it passes fine in buildbot, but I could reproduce this pretty consistently with Python 3 on Debian/sid (maybe some subtle differences were introduced in CPython or just planets aligning in my case).

Just running:

python3 -m twisted.trial twisted.test.test_main

on Debian/sid should hopefully be enough to reproduce (although I think the evidence of flakiness is pretty clear).

I'm attaching a stop-the-gap patch, you might want to curate it.

Attachments:

* [patch](https://raw.githubusercontent.com/twisted/twistedmatrix.com-trac-attachments/trunk/ticket/a15/a153e22675856f949b7a811b298daeb9bb8947b7/d75b3b528276d7a9f30a04b8bccaf74e1d61f67a) (477 bytes) - added by freeekanayaka on 2016-11-26 11:09:59Z - 

<details><summary>Searchable metadata</summary>

```
trac-id__8923 8923
type__enhancement enhancement
reporter__freeekanayaka freeekanayaka
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1480158571150380 1480158571150380
changetime__1480158571150380 1480158571150380
version__None None
owner__None None

```
</details>

**Comment by glyph** [comment]
I think that [Python's change to determinism on dict ordering](https://softwaremaniacs.org/blog/2020/02/05/dicts-ordered/en/) would have obviated this flake, but please feel free to reopen if I am wrong about this.
