### ISSUE TITLE
Release manylinux1 wheels

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8927]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#8927|
|Type|enhancement|
|Created|2016-11-30 19:15:17Z|

It would be awesome if Twisted published manylinux1 wheels as described in [PEP 513](https://www.python.org/dev/peps/pep-0513/) so that install doesn't require a C compiler (and is faster!).

<details><summary>Searchable metadata</summary>

```
trac-id__8927 8927
type__enhancement enhancement
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__reopened reopened
resolution__None None
component__release_management release management
keywords__None None
time__1480533317272835 1480533317272835
changetime__1554250482529660 1554250482529660
version__None None
owner__None None
cc__radix
```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="tomprince's avatar" src="https://avatars.githubusercontent.com/u/283816?s=50" width="50" height="50">](https://github.com/tomprince)<a name="note_2"></a>|@tomprince set status to `closed`|
|-|-|

This is a duplicate of [#3586](https://github.com/twisted/twisted/issues/3586)

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set status to `reopened`|
|-|-|

This isn't a duplicate; it's a specific mechanism we could use to partially implement the functionality requested in [[#3586](https://github.com/twisted/twisted/issues/3586)](https://github.com/twisted/twisted/issues/3586).  In order to do #3586, we'd have to have Mac wheels, Windows wheels, manylinux1 wheels, and some mechanism for fallbacks on other supported platforms (like freebsd).

**Comment by twisted-trac** [comment]
|[<img alt="wiml's avatar" src="https://avatars.githubusercontent.com/u/156891?s=50" width="50" height="50">](https://github.com/wiml)<a name="note_4"></a>|@wiml commented|
|-|-|

The only thing in Twisted that prevents its wheels from being architecture-neutral is `twisted/test/raiser.pyx`, which is used in Twisted's own tests. It seems suboptimal that this one file, which is likely not used in deployment, prevents people from being able to install Twisted directly from a `none-any` wheel without a C compiler.

**Comment by adiroiban** [comment]
I think that this can be closed.

twisted no longer has C extensions.
