### ISSUE TITLE
Split IOCPReactor out into its own package

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8951]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#8951|
|Type|enhancement|
|Created|2016-12-19 05:32:45Z|
|Branch|https://github.com/twisted/twisted/tree/8951-iocpreactor-sep|

        Instead of bundling it with the rest, moving IOCPReactor into its own package, with its own external API, that does not operate in lockstep. IOCPReactor would have nightly builds against Twisted current, and Twisted trunk. Twisted's Windows builders would test against IOCPReactor current, and IOCPReactor trunk. 

The goal here is to have all the existing Windows test infra test some of the most Windows-sensitive components of Twisted, and to make it sensible to make updates to one project without having to span two codebases. By moving IOCPReactor out of Twisted rather than just the support modules, it will be easier to write updates to IOCPReactor itself as they may span between the support modules and the Python implementation code.

Also worth noting: iocpsupport et. al. - basically everything except the reactor itself - will be deprecated in Twisted and private in its new location. The only public API for the new IOCPReactor package will be the public reactor APIs (and perhaps some semi-public stuff that leaks through like addActiveHandle). 

<details><summary>Searchable metadata</summary>

```
trac-id__8951 8951
type__enhancement enhancement
reporter__hawkowl hawkowl
priority__normal normal
milestone__None None
branch__8951_iocpreactor_sep 8951-iocpreactor-sep
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1482125565698828 1482125565698828
changetime__1486196047028109 1486196047028109
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

iocpreactor uses private APIs from other parts of Twisted.  How will this be dealt with?

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)|@hawkowl set owner to @hawkowl|
|-|-|

**Comment by glyph** [comment]
I think we have done the most salient part of this with the iocpsupport split.
