### ISSUE TITLE
pydoctor templates should set a canonical URL

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#8996]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#8996|
|Type|enhancement|
|Created|2017-01-15 21:18:17Z|

Our pydoctor templates should set a canonical URL via a ```link``` tag, so that A Certain Search Engine will send people to the latest version of our documentation.

See https://docs.readthedocs.io/en/latest/canonical.html for more information.

<details><summary>Searchable metadata</summary>

```
trac-id__8996 8996
type__enhancement enhancement
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1484515097061297 1484515097061297
changetime__1484515097061297 1484515097061297
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
I have moved this here as it should be fixed in pydoctor 
https://github.com/twisted/pydoctor/issues/608
