### ISSUE TITLE
Add treq to Twisted CI

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9042]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9042|
|Type|enhancement|
|Created|2017-02-16 13:19:41Z|
|Branch|https://github.com/twisted/twisted/tree/9042-ci-for-treq|

See [mailing list discussion](http://twistedmatrix.com/pipermail/twisted-python/2017-February/031174.html).

<details><summary>Searchable metadata</summary>

```
trac-id__9042 9042
type__enhancement enhancement
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__9042_ci_for_treq 9042-ci-for-treq
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__None None
time__1487251181816127 1487251181816127
changetime__1492323056342274 1492323056342274
version__None None
owner__exarkun exarkun

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

https://github.com/twisted/twisted/pull/710

**Comment by twisted-trac** [comment]
|[<img alt="wsanchez's avatar" src="https://avatars.githubusercontent.com/u/50002?s=50" width="50" height="50">](https://github.com/wsanchez)<a name="note_3"></a>|@wsanchez commented|
|-|-|

Twisted CI is already pretty bloated.  Does Twisted really need to be testing downstream projects in its own CI?

This seems like the wrong model here.  As are going to add every subproject?  Like why not also test klein?

Klein has it's own CI which does test Twisted trunk, though not on every Twisted commit on trunk.  So that's not as complete, but this feels like overkill.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_4"></a>|@hawkowl set owner to @exarkun|
|-|-|

Thanks, JP. See the review on the PR.

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_5"></a>|@hawkowl commented|
|-|-|

(which, to deduplicate here, was 'please make the builds not fail until we have a patch, then merge' :) )

**Comment by adiroiban** [comment]
I think that this can be closed.

If there any specific use case of Twisted in treq, instead of running the full treq tests, we should make sure that we extract the specific use case and have it as part of the core twisted tests and API backward compatiblity checks.

we have ldaptor and I think other project in which we run the tests the other way around.

We run ldaptor CI tests with latest released twisted and latest trunk twisted.

I think that this is more scalable.

I am going to close this.

Feel free to reopen if you think that is critical to have treq tests.

My issue is that if we run twisted trunk tests against treq trunk tests, if treq trunk breaks for any reason, the Twisted CI will also break.

**Comment by exarkun** [comment]
Does treq actually work against recent versions of Twisted right now?  Apparently I filed this ticket 5 years ago but latest releases of treq/Twisted were broken against each other as recently as a couple months ago.

**Comment by exarkun** [comment]
To be explicit about the implication of my above comment: If treq and Twisted continue to have incompatible releases then shouldn't we do _something_ about it?

**Comment by adiroiban** [comment]
Hm... I have just briefly checked treq CI 

I see all tests are green.
Treq CI runs 3 environments:

* Oldest public Twisted release
* Latest public Twisted release
* Latest trunk Twisted code

https://github.com/twisted/treq/runs/5121404025?check_suite_focus=true

So I think this is now fixed.

----------

I don't see any hacks or workaround in treq CI code

https://github.com/twisted/treq/blob/trunk/.github/workflows/ci.yaml

https://github.com/twisted/treq/blob/trunk/tox.ini
