### ISSUE TITLE
Provide .tar.gz version of package

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9046]
|<img alt="kmike's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50">| kmike reported|
|-|-|
|Trac ID|trac#9046|
|Type|enhancement|
|Created|2017-02-22 10:47:59Z|

Hey,

Currently Twisted provides only wheels and .tar.bz2 packages on pypi: https://pypi.python.org/pypi/Twisted. This is a problem because there are systems where Python is built without bz2 support, and there are also older systems where pip doesn't support wheels. In this case `pip install twisted` fails with an error. It caused installation issues for Scrapy, e.g. see https://github.com/scrapy/scrapy/issues/2563 and https://github.com/scrapy/scrapy/issues/2580.

Update: wheels are irrelevant because there is only a Py27+Windows wheel uploaded for Twisted, so even new pip versions are affected by this issue.

<details><summary>Searchable metadata</summary>

```
trac-id__9046 9046
type__enhancement enhancement
reporter__kmike kmike
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__None None
time__1487760479272202 1487760479272202
changetime__1499067356800445 1499067356800445
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|<img alt="kmike's avatar" src="https://avatars.githubusercontent.com/u/0?s=50" width="50" height="50"><a name="note_2"></a>|kmike commented|
|-|-|

More examples of users having this problem: https://github.com/scrapy/scrapy/issues/2810, [#8177](https://github.com/twisted/twisted/issues/8177).

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_3"></a>|@glyph set owner to @hawkowl|
|-|-|

I think we should probably just stop providing `.tar.bz2` if `.tar.gz` is the lowest common denominator for sdists.

However, splitting out our C extensions into a separate package - [#7945](https://github.com/twisted/twisted/issues/7945) - and finishing our Python 3 porting might allow us to ship a pure-python, universal wheel, which would simplify this somewhat.

Given that our release process isn't fully automated, there might not be any code to change here, so it needs to go to our current release manager, who is hopefully _as we speak_ finding an apprentice.  (Hey kmike do you want to be the release manager for twisted.)

**Comment by adiroiban** [comment]
PyPi has tar.gz  https://pypi.org/project/Twisted/#files

i think that this can be closed.
