### ISSUE TITLE
DelayedCall.__str__ assumes that things with __name__s always have func_names

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9061]
|[<img alt="Julian's avatar" src="https://avatars.githubusercontent.com/u/329822?s=50" width="50" height="50">](https://github.com/Julian)| @Julian reported|
|-|-|
|Trac ID|trac#9061|
|Type|defect|
|Created|2017-02-27 16:06:26Z|

(They do not, they can be classes or other fun things).

See e.g.:

```
from twisted.internet import reactor
from twisted.trial.unittest import TestCase
class TestTest(TestCase):
    def test_it_blows_up(self):
        reactor.callLater(10, int)
```

https://github.com/twisted/twisted/blob/b276c7f6929dfba91528423a6bde7288fc7644cb/src/twisted/internet/base.py#L192-L193

The comment there possibly means that this should just be done "properly" via [#6066](https://github.com/twisted/twisted/issues/6066) rather than fixing this specific issue.

<details><summary>Searchable metadata</summary>

```
trac-id__9061 9061
type__defect defect
reporter__Julian Julian
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1488211586271757 1488211586271757
changetime__1488211586271757 1488211586271757
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
It looks like this was introduced in 09c9169e3e988bcb92c054d28fe964d34919af93 for #6065.  Then it was fixed (maybe not "properly") in fadb582d49da33455c1623a07b4b200a58aa048c as part of #1570 for #10155.

#6066 remains valid because the logic is just inline in `DelayedCall.__repr__`.
