### ISSUE TITLE
Replace twisted.python.deprecate with eventually

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9111]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#9111|
|Type|enhancement|
|Created|2017-04-10 03:30:19Z|
|Branch|https://github.com/twisted/twisted/tree/9111-eventually|

https://pypi.python.org/pypi/eventually

https://github.com/twisted/eventually

Part of the FilePath splitout (as FilePath depends on t.p.deprecate, as do many other modules we want to split out).

<details><summary>Searchable metadata</summary>

```
trac-id__9111 9111
type__enhancement enhancement
reporter__hawkowl hawkowl
priority__normal normal
milestone__None None
branch__9111_eventually 9111-eventually
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1491795019380664 1491795019380664
changetime__1495659906769547 1495659906769547
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_1"></a>|@hawkowl commented|
|-|-|

Okay, this is in a good looking place. Please review.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_2"></a>|@glyph commented|
|-|-|

It doesn't look like I have PyPI permission to upload to `eventually`.

Things on the Twisted org should probably have ~similar upload permissions.  (I don't mean me specifically, I mean, the general set of committers, and not just one person.)

Not necessarily a blocker for this since we don't have a super disciplined approach to managing this kind of thing yet, but it's something to think about, especially as we make more and more of these; we need to be able to delegate release management.

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban commented|
|-|-|

PR at https://github.com/twisted/twisted/pull/764

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_4"></a>|@adiroiban commented|
|-|-|

Is there any real value in having many small python packages doing only a few things.

I feel like we are going to the node.js path where you have a package for the strip function.

Can we pack the deprecation code together with the versioning code... for example to only have 'incremental'  ?

I feel that having multiple separate project just adds a lot of extra admin works... set up repo permissions/ set up pypi access / set up CI integration / set up documentation ..

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)<a name="note_5"></a>|@hawkowl commented|
|-|-|

This should go into incremental, yeah.

**Comment by adiroiban** [comment]
Is this something that we still want to pursue ?

**Comment by glyph** [comment]
I think that having our deprecation functionality in Incremental would make more sense, since they're of a piece. (I think the `eventually` package is a dead end.)

**Comment by adiroiban** [comment]
I am closing this.

There is also https://github.com/Julian/regret
