### ISSUE TITLE
twistedmatrix.com should send an HSTS header to ensure browsers always get an HTTPS connection

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9233]
|[<img alt="alex's avatar" src="https://avatars.githubusercontent.com/u/772?s=50" width="50" height="50">](https://github.com/alex)| @alex reported|
|-|-|
|Trac ID|trac#9233|
|Type|enhancement|
|Created|2017-07-23 21:43:41Z|

```
~ ❯❯❯ http head 'https://twistedmatrix.com/trac'
HTTP/1.1 200 Ok
Cache-Control: must-revalidate
Content-Length: 26452
Content-Type: text/html;charset=utf-8
Date: Sun, 23 Jul 2017 21:43:17 GMT
Expires: Fri, 01 Jan 1999 00:00:00 GMT
Server: TwistedWeb/17.1.0
Set-Cookie: trac_form_token=c5d88a0e2ef5c8d977957adb; httponly; Path=/trac
Set-Cookie: trac_session=a903ba3af3821800cfff0a30; expires=Sat, 21 Oct 2017 21:43:17 GMT; httponly; Path=/trac
```

<details><summary>Searchable metadata</summary>

```
trac-id__9233 9233
type__enhancement enhancement
reporter__alex alex
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__website website
keywords__None None
time__1500846221663004 1500846221663004
changetime__1501436810417381 1501436810417381
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_1"></a>|@exarkun commented|
|-|-|

This should be filed against the infra project on github, probably <https://github.com/twisted-infra/braid>.

**Comment by adiroiban** [comment]
Thanks for the report

Not sure what we can do here.

We now use GitHub pages for our site.

I am closing this as I don't think we can do much here.

Feel free to reopen if you think that this is a big issue that needs to be fix.

One option is to move the hosting to something like Cloudflare, but I don't think that we have the energy to do that.



The Github page is already configured to enforce HTTPS ... but there is no explicit option to set the HTTP header

![image](https://github.com/twisted/twisted/assets/204609/8e499a6b-59de-4de0-9586-c34606dd851d)


I see that this is a known issue with GitHub Pages 

* https://github.com/orgs/community/discussions/4444
* https://github.com/isaacs/github/issues/1249
