### ISSUE TITLE
twistedmatrix.com should mark session cookies as "secure" to ensure they are never leaked in any unencrypted connections

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9234]
|[<img alt="alex's avatar" src="https://avatars.githubusercontent.com/u/772?s=50" width="50" height="50">](https://github.com/alex)| @alex reported|
|-|-|
|Trac ID|trac#9234|
|Type|defect|
|Created|2017-07-23 21:45:21Z|

```
~ ❯❯❯ http head 'https://twistedmatrix.com/trac'
HTTP/1.1 200 Ok
Cache-Control: must-revalidate
Content-Length: 26452
Content-Type: text/html;charset=utf-8
Date: Sun, 23 Jul 2017 21:43:17 GMT
Expires: Fri, 01 Jan 1999 00:00:00 GMT
Server: TwistedWeb/17.1.0
Set-Cookie: trac_form_token=c5d88a0e2ef5c8d977957adb; httponly; Path=/trac
Set-Cookie: trac_session=a903ba3af3821800cfff0a30; expires=Sat, 21 Oct 2017 21:43:17 GMT; httponly; Path=/trac
```

<details><summary>Searchable metadata</summary>

```
trac-id__9234 9234
type__defect defect
reporter__alex alex
priority__high high
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__website website
keywords__None None
time__1500846321155883 1500846321155883
changetime__1501436725935960 1501436725935960
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)<a name="note_2"></a>|@exarkun commented|
|-|-|

This should be filed against the infra project on github, probably <https://github.com/twisted-infra/braid>.

**Comment by adiroiban** [comment]
We no longer have a separate infa project.


The site is now hosted by GitHub pages and has no cookies.

So any fix should be done via https://github.com/twisted/twisted.github.io

It would be nice to setup some automated / scheduled scripts that are executed by GitHub Action and check whether the cookies are secure... but I don't think that we have the "energy" for that.

I am going to close this.

I would be happy to review a PR that add a test for this.

**Comment by glyph** [comment]
Should we be archiving Braid?

**Comment by adiroiban** [comment]
Done https://github.com/twisted-infra/braid
