### ISSUE TITLE
CI should cache intersphinx blobs

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9277]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9277|
|Type|enhancement|
|Created|2017-09-01 20:28:37Z|

[Documentation](http://twistedmatrix.com/trac/ticket/8823) [[#9276](https://github.com/twisted/twisted/issues/9276) builds] fail because various `objects.inv` files are inaccessible.

The CI jobs that build documentation should cache these `objects.inv`s to reduce the chances of spurious failures.

<details><summary>Searchable metadata</summary>

```
trac-id__9277 9277
type__enhancement enhancement
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1504297717855435 1504297717855435
changetime__1504428064214853 1504428064214853
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/pydoctor/issues/120 needs to be closed first.

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

I've opened a PR pydoctor that allows it to cache `objects.inv` files:

https://github.com/twisted/pydoctor/pull/143

This or something else that closes [pydoctor issue 120](https://github.com/twisted/pydoctor/issues/120) has to be merged before this ticket can be closed.

**Comment by adiroiban** [comment]
I think that this can be closed as we now have cache in pydoctor
