### ISSUE TITLE
twisted.python.url.URL documentation links to twisted.protocols.sip.URL

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9317]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9317|
|Type|enhancement|
|Created|2017-11-07 22:28:45Z|

[twisted.python.url](https://twistedmatrix.com/documents/17.9.0/api/twisted.python.url.html)'s docstring links to ```L{URL```} and pydoctor resolves it to ```twisted.protocols.sip.URL```.  That is clearly wrong.

<details><summary>Searchable metadata</summary>

```
trac-id__9317 9317
type__enhancement enhancement
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1510093725033539 1510093725033539
changetime__1510093725033539 1510093725033539
version__None None
owner__None None

```
</details>

**Comment by tristanlatr** [comment]
This has been fixed for a while.
