### ISSUE TITLE
Move twisted.python._log.actually to twisted.python._pydoctor

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9319]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9319|
|Type|enhancement|
|Created|2017-11-07 22:48:27Z|

`_actually` allows creating redirecting stubs for code that's been moved out of Twisted.  See [#9318](https://github.com/twisted/twisted/issues/9318).

<details><summary>Searchable metadata</summary>

```
trac-id__9319 9319
type__enhancement enhancement
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1510094907637109 1510094907637109
changetime__1510094907637109 1510094907637109
version__None None
owner__None None

```
</details>

**Comment by tristanlatr** [comment]
I think this issue can be closed.

**Comment by adiroiban** [comment]
Thanks for the feedback.
I am closing this.

Just asking: Is this functionality somehow supported by PyDoctor?
