### ISSUE TITLE
Cygwin: processEnded never called for spawned process

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9323]
|[<img alt="embray's avatar" src="https://avatars.githubusercontent.com/u/676149?s=50" width="50" height="50">](https://github.com/embray)| @embray reported|
|-|-|
|Trac ID|trac#9323|
|Type|defect|
|Created|2017-11-08 11:21:40Z|

This issue can be reproduced with a simple test case like:
```python
import os
from twisted.internet import reactor
from twisted.internet import utils

def printResults(*args):
    print(args)
    reactor.stop()


d = utils.getProcessOutputAndValue('echo', ['hello'], env=os.environ)
d.addCallback(printResults)
reactor.run()
```

The `printResults` callback is never run and the reactor (specifically `PollReactor` which is the default on Cygwin) blocks at `poll()`.

This can also be seen with the tests:
```
python -m twisted.trial twisted.internet.test.test_process.ProcessTestsBuilder_PollReactorTests.test_processEnded
python -m twisted.trial twisted.internet.test.test_process.ProcessTestsBuilder_PollReactorTests.test_processExited
```

and possibly others, which hang due to this issue.

The problem, as I understand it, has to do with the `forceReadHack` flag of [https://github.com/twisted/twisted/blob/bb371b3b602b1547c6e603d3b234bb18ded6d67c/src/twisted/internet/process.py#L132 `ProcessWriter`], which `Process` always passes `True`.

Cygwin has a bug(?) that I documented [here](https://cygwin.com/ml/cygwin/2017-11/msg00147.html).  The technical details in Cygwin are unimportant but in short `poll()`-ing for readability on the write end of a pipe does not set any useful bits (much less `POLLERR`).  So we get stuck polling for the write end of the `stdin` pipe to be ready which never happens on Cygwin.

It would be better to explicitly disable the "read hack" on Cygwin, and manually call `Process.closeStdin` when the child process is already known to have exited.

**PR:** https://github.com/twisted/twisted/pull/925

<details><summary>Searchable metadata</summary>

```
trac-id__9323 9323
type__defect defect
reporter__embray embray
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1510140100630732 1510140100630732
changetime__1511877854524949 1511877854524949
version__None None
owner__embray embray

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban set owner to @embray|
|-|-|

Thanks for working on this. The ticket description is great and it was very easy to review the PR. Great work!

See my review comments https://github.com/twisted/twisted/pull/925#pullrequestreview-79033710

I started a conversation on the mailing list to see what can be done for patches sent for unsupported platforms. See https://twistedmatrix.com/pipermail/twisted-python/2017-November/031746.html

**Comment by twisted-trac** [comment]
|[<img alt="embray's avatar" src="https://avatars.githubusercontent.com/u/676149?s=50" width="50" height="50">](https://github.com/embray)<a name="note_3"></a>|@embray commented|
|-|-|

Thanks for the review.  I'm also having a look at the (interesting) discussion on the mailing list.  Should I follow up more here or on GitHub?

**Comment by glyph** [comment]
We don't support cygwin and it has been declining in popularity pretty significantly since this issue was written.  We really appreciate you taking the time to make the contribution but unless we get an updated PR with a full GHA setup for testing cygwin comprehensively, I don't think there's much appetite for this.
