### ISSUE TITLE
twisted.web.http._newclient.Request vulnerable to header injection

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9421]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9421|
|Type|defect|
|Created|2018-04-13 23:29:06Z|

```twisted.web._newclient.Request._writeHeaders``` allows line breaks in header values, so it's possible that a malicious input could inject a new header by including a value with ```\n``` or ```\r\n```.

```writeHeaders``` should not write ```\n``` or ```\r\n``` in response header values.

```twisted.web.http.HTTPClient``` is also vulnerable.

<details><summary>Searchable metadata</summary>

```
trac-id__9421 9421
type__defect defect
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__closed closed
resolution__fixed fixed
component__web web
keywords__None None
time__1523662146636659 1523662146636659
changetime__1552934544220241 1552934544220241
version__None None
owner__markrwilliams markrwilliams

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_2"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/999

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)|@glyph set owner to @markrwilliams|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_4"></a>|@glyph set status to `closed`|
|-|-|

This was also fixed by PR 999.

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_5"></a>|@glyph commented|
|-|-|

(which is merged)

**Comment by itamarst** [comment]
I just discovered this recently, due to the performance overhead this introduced, and in actual normal twisted.web usage the headers are _already_ (mostly) sanitized, so this only really applies to code that uses HTTPChannel directly.
