### ISSUE TITLE
Describe release blockers in release policy

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9426]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)| @markrwilliams reported|
|-|-|
|Trac ID|trac#9426|
|Type|enhancement|
|Created|2018-04-18 18:03:26Z|

We can be more specific than "code that the RM decides can block a release."

<details><summary>Searchable metadata</summary>

```
trac-id__9426 9426
type__enhancement enhancement
reporter__markrwilliams markrwilliams
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1524074606707002 1524074606707002
changetime__1526222776155782 1526222776155782
version__None None
owner__markrwilliams markrwilliams

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="markrwilliams's avatar" src="https://avatars.githubusercontent.com/u/704247?s=50" width="50" height="50">](https://github.com/markrwilliams)<a name="note_1"></a>|@markrwilliams commented|
|-|-|

https://github.com/twisted/twisted/pull/1003

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_2"></a>|@adiroiban set owner to @markrwilliams|
|-|-|

See https://github.com/twisted/twisted/pull/1003#pullrequestreview-119656819

**Comment by glyph** [comment]
Looks like this terminology did not really hit :)
