### ISSUE TITLE
NEWS file should use https:// URL

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9437]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9437|
|Type|enhancement|
|Created|2018-05-03 20:37:05Z|

[NEWS.rst begins](https://github.com/twisted/twisted/blob/twisted-18.4.0/NEWS.rst):

> Ticket numbers in this file can be looked up by visiting http://twistedmatrix.com/trac/ticket/<number>

That should be `https://twistedmatrix.com/`

<details><summary>Searchable metadata</summary>

```
trac-id__9437 9437
type__enhancement enhancement
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__None None
time__1525379825396427 1525379825396427
changetime__1525379825396427 1525379825396427
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
I will look into this... and while at this, also update the link to tickets
