### ISSUE TITLE
Document that the version merged into trunk is X.Y.Z+1dev0, not X.Y.Zdev0

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9542]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)| @hawkowl reported|
|-|-|
|Trac ID|trac#9542|
|Type|enhancement|
|Created|2018-09-27 15:22:17Z|

I decided to do this at the end of https://github.com/twisted/twisted/pull/745 , but forgot to write it down.

<details><summary>Searchable metadata</summary>

```
trac-id__9542 9542
type__enhancement enhancement
reporter__hawkowl hawkowl
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__None None
time__1538061737205985 1538061737205985
changetime__1614652529577430 1614652529577430
version__None None
owner__hawkowl hawkowl

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="hawkowl's avatar" src="https://avatars.githubusercontent.com/u/3307100?s=50" width="50" height="50">](https://github.com/hawkowl)|@hawkowl set owner to @hawkowl|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="rodrigc's avatar" src="https://avatars.githubusercontent.com/u/1895943?s=50" width="50" height="50">](https://github.com/rodrigc)<a name="note_2"></a>|@rodrigc commented|
|-|-|

@hawkowl I changed the Twisted release process to do:

$RELEASE.rc1
$RELEASE
$RELEASE.post0

based on my reading of PEP-440, and the latest Twisted incremental 21.3.0 which
better supports PEP-440.
Hope that is OK with you.

**Comment by adiroiban** [comment]
I think  that this is documented at https://docs.twisted.org/en/stable/core/development/policy/release-process.html#post-release

We now have `post0`
