### ISSUE TITLE
'lint' tox environment contains UNIX shell scripts

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9616]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)| @glyph reported|
|-|-|
|Trac ID|trac#9616|
|Type|defect|
|Created|2019-04-08 03:40:15Z|

Among other things, this means you can't lint twisted on Windows, which is yet another spurious barrier to entry for any heroic contributors who want to help us out on that platform.

I hear good things about a shell-script replacement language called uh... adder?  rattle?  anyway it's named after some kind of snake, we should check it out

<details><summary>Searchable metadata</summary>

```
trac-id__9616 9616
type__defect defect
reporter__glyph glyph
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__None None
time__1554694815165816 1554694815165816
changetime__1554694815165816 1554694815165816
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
I think that this can be closed.

`tox -e lint` is now just an alias for pre-commit and I think that pre-commit works on Windows


```
    lint: pre-commit {posargs:run --all-files --show-diff-on-failure}
```

I have not tested... but I think that if there are any issues on Windows, it should be fixed in pre-commit :)
