### ISSUE TITLE
Binary wheel for Python 3.7 on Windows

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9631]
|[<img alt="ofek's avatar" src="https://avatars.githubusercontent.com/u/9677399?s=50" width="50" height="50">](https://github.com/ofek)| @ofek reported|
|-|-|
|Trac ID|trac#9631|
|Type|enhancement|
|Created|2019-04-24 17:52:22Z|

Twisted's release process should include building binary wheels that function on Windows.

<details><summary>Searchable metadata</summary>

```
trac-id__9631 9631
type__enhancement enhancement
reporter__ofek ofek
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__release_management release management
keywords__windows windows
time__1556128342582767 1556128342582767
changetime__1561831109527750 1561831109527750
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
I think that this can be closed. We no longer have binary wheels.
