### ISSUE TITLE
pydoctor ignores @deprecated's docstring augmentations

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9745]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9745|
|Type|defect|
|Created|2019-12-15 23:20:56Z|

`twisted.web.client.getPage` and `twisted.web.client.downloadPage` were deprecated in Twisted 16.7.0 but the rendered API documentation doesn't mention this.

The deprecation message _is_ inserted by the `@deprecated` decorator applied to both of them:

```
>>> from twisted.web.client import getPage
>>> getPage.__doc__
'\n    Download a web page as a string.\n\n    Download a page. Return a deferred, which will callback with a\n    page (as a string) or errback with a description of the error.\n\n    See L{HTTPClientFactory} to see what extra arguments can be passed.\n\n    Deprecated in Twisted 16.7.0; please use https://pypi.org/project/treq/ or twisted.web.client.Agent instead.\n    '
>>> print(getPage.__doc__)

    Download a web page as a string.

    Download a page. Return a deferred, which will callback with a
    page (as a string) or errback with a description of the error.

    See L{HTTPClientFactory} to see what extra arguments can be passed.

    Deprecated in Twisted 16.7.0; please use https://pypi.org/project/treq/ or twisted.web.client.Agent instead.
    
```

<details><summary>Searchable metadata</summary>

```
trac-id__9745 9745
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__pydoctor pydoctor
keywords__None None
time__1576452056994472 1576452056994472
changetime__1583456878085636 1583456878085636
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm set owner to @twm<br>@twm set status to `assigned`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)<a name="note_3"></a>|@twm commented|
|-|-|

See also https://github.com/twisted/pydoctor/issues/102

**Comment by twisted-trac** [comment]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)|@twm removed owner<br>@twm set status to `new`|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="mthuurne's avatar" src="https://avatars.githubusercontent.com/u/246676?s=50" width="50" height="50">](https://github.com/mthuurne)<a name="note_5"></a>|@mthuurne commented|
|-|-|

I have an implementation that addresses GitHub issue 102, but that only supports simple assignments to `__doc__`. The static code analysis of pydoctor is nowhere near advanced enough to figure out the inner workings of a decorator.

The right approach would be to have explicit support for Twisted's deprecation mechanism. And in fact there is code in pydoctor's `twistedmodel.py` that should process `@deprecated` decorations, but indeed this is not visible in the output, so I guess something is broken there.

**Comment by adiroiban** [comment]
I think that this can be closed.

As mentions above, the fix should be done in pydoctor

I think that pydoctor already supports the deprecation decorators.
