### ISSUE TITLE
Combine maybeDeferred() and ensureDeferred() in new method

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9794]
|[<img alt="sveinse's avatar" src="https://avatars.githubusercontent.com/u/13770135?s=50" width="50" height="50">](https://github.com/sveinse)| @sveinse reported|
|-|-|
|Trac ID|trac#9794|
|Type|enhancement|
|Created|2020-04-07 14:34:53Z|

`t.w.i.d.maybeDeferred()` provides a way to run a regular function that might or might not return a deferred. `t.w.i.d.ensureDeferred()` allows a coroutine object to become a deferred. If the coro object is already a deferred it will be passed through.

I'd like to suggest a combination of these two. A method that allows calling a function that might return a) a regular value, b) a coroutine object or c) a deferred, and that it always returns a `Deferred()`. It will allow calling and awaiting async coroutines as well as regular functions alike. Note that it is not possible to use `maybeDeferred()` and `ensureDeferred()` in combination to do this from user code.

Below is the function I'd like to propose added. I do not have any opinions about its naming.

```python
def maybeAsync(f, *args, **kw):
    ''' Call f where it can be returning an immediate value, a deferred
        or a coroutine object. The function returns a deferred.

        For non-coroutine functions, it is equivalent of maybeDeferred(f,...).
        For coroutines it is equivalent of ensureDeferred(f(...))
    '''

    # This code is copied from twisted.internet.defer.maybeDeferred()
    # with alterations for when f returns a coroutine.
    try:
        result = f(*args, **kw)
    except:
        return defer.fail(defer.failure.Failure(captureVars=defer.Deferred.debug))

    if isinstance(result, types.CoroutineType):
        return defer.ensureDeferred(result)
    elif isinstance(result, defer.Deferred):
        return result
    elif isinstance(result, defer.failure.Failure):
        return defer.fail(result)
    else:
        return defer.succeed(result)
```

<details><summary>Searchable metadata</summary>

```
trac-id__9794 9794
type__enhancement enhancement
reporter__sveinse sveinse
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1586270093162065 1586270093162065
changetime__1588142551491441 1588142551491441
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
It seems like #10327 has resolved this adequately.  There is no new method, but `maybeDeferred` now handles coroutines and still gives back a `Deferred`.

Is there any use to providing anything further?

**Comment by adiroiban** [comment]
For the tickets imported from Trac, the original reporter is not already CCed / subscribed.

If you want to notify a person like @sveinse  you need to mention them.

--------

I think this can be closed.

I am not happy to see a new API method.

And maybe, at some point `ensureDeferred` can be deprecated, and only have `maybeDeferred`

---------

But maybe is easy to just close the ticket as "not planned", and we can reopen it later

![image](https://user-images.githubusercontent.com/204609/193405305-6d13a22b-42d5-4369-8e31-1c82de4523ba.png)
