### ISSUE TITLE
maybeDeferred passes through coroutines

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9813]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9813|
|Type|defect|
|Created|2020-05-05 20:56:33Z|

`twisted.internet.defer.maybeDeferred` passes through coroutines rather than coercing them to a `Deferred` like `ensureDeferred`:

```
>>> from twisted.internet import defer
>>> async def foo():
...    return 1
... 
>>> d = defer.maybeDeferred(foo)
>>> print(d)
<Deferred at 0x7efdae2a93c8 current result: <coroutine object foo at 0x7efdad5b78e0>>
```

This behavior is surprising. I cannot imagine a use case for it.

It is also inconvenient. Assuming we want users of Twisted APIs to be able to use the `async def` syntax anywhere they could use `@inlineCallbacks` it forces either:

* Every user of `maybeDeferred` to add an additional check for coroutines
* The caller to manually convert a coroutine to a `Deferred` before passing it to any API
* Some mix of the two

See also [#9794](https://github.com/twisted/twisted/issues/9794), which suggests adding a new function that combines `maybeDeferred` and `ensureDeferred`. That would mean updating every caller of `mabeDeferred` to call the new function.

<details><summary>Searchable metadata</summary>

```
trac-id__9813 9813
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1588712193307608 1588712193307608
changetime__1588712193307608 1588712193307608
version__None None
owner__None None

```
</details>

**Comment by exarkun** [comment]
#10327 was a duplicate of this.
