### ISSUE TITLE
twisted.web.util.ChildRedirector is broken

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9838]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9838|
|Type|defect|
|Created|2020-05-31 02:21:14Z|

`twisted.web.util.ChildRedirector` is broken:

* It freely mixes `str` and `bytes` in a way that obviously won't work.
* It doesn't escape path segments when building URLs. This could result in a nonsensical _Location_ header (e.g., for a path segment that contains a space) and appears to have been a header injection vulnerability prior to the introduction of header sanitization.

Its purpose appears to be to redirect one URL tree to another, but the implementation of that seems... less than efficient, since it builds up a URL one path segment at a time and creates lots of `ChildRedirector` instances when it could do a bit of URL manipulation instead.

Also, it has no documentation.

See also [#9835](https://github.com/twisted/twisted/issues/9835).

<details><summary>Searchable metadata</summary>

```
trac-id__9838 9838
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__None None
time__1590891674631888 1590891674631888
changetime__1590891674631888 1590891674631888
version__None None
owner__None None

```
</details>

**Comment by twm** [comment]
Duplicate of #9591.
