### ISSUE TITLE
twisted.web.util.redirectTo should HTML-escape URL

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9839]
|[<img alt="twm's avatar" src="https://avatars.githubusercontent.com/u/43662?s=50" width="50" height="50">](https://github.com/twm)| @twm reported|
|-|-|
|Trac ID|trac#9839|
|Type|defect|
|Created|2020-05-31 02:57:01Z|

The `redirectTo` function interpolates a URL into HTML without escaping the URL. This may produce invalid HTML as URLs can contain `&` characters.

Also you could combine this with [#9838](https://github.com/twisted/twisted/issues/9838) on Python 2.7 to inject arbitrary HTML into the redirect page. Browsers don't seem to actually render that page, though.

<details><summary>Searchable metadata</summary>

```
trac-id__9839 9839
type__defect defect
reporter__twm twm
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__web web
keywords__None None
time__1590893821712289 1590893821712289
changetime__1590895509146936 1590895509146936
version__None None
owner__None None

```
</details>

**Comment by adiroiban** [comment]
This was done in https://github.com/twisted/twisted/security/advisories/GHSA-cf56-g6w6-pqq2

This was merged here https://github.com/twisted/twisted/commit/046a164f89a0f08d3239ecebd750360f8914df33

This was a security bugfix fork and PR and the PR was lost
