### ISSUE TITLE
twisted.protocols.test.test_tls not run on CI systems

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9944]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)| @exarkun reported|
|-|-|
|Trac ID|trac#9944|
|Type|defect|
|Created|2020-08-21 15:56:21Z|

According to a recent coveralls.io report:

https://coveralls.io/builds/32817266/source?filename=src/twisted/protocols/test/test_tls.py

`twisted.protocols.test.test_tls` is essentially completely unexecuted across coverage-gathering CI jobs.

This appears to be due to a change in pyOpenSSL 19.1.0 which removed `ConnectionType`.  The whole `test_tls` module is skipped if this can't be imported.

This suggests the module may have been skipped on CI since sometime in 2019.

<details><summary>Searchable metadata</summary>

```
trac-id__9944 9944
type__defect defect
reporter__exarkun exarkun
priority__normal normal
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1598025381182652 1598025381182652
changetime__1626935726362504 1626935726362504
version__None None
owner__adiroiban adiroiban

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_1"></a>|@adiroiban commented|
|-|-|

Tentative PR at https://github.com/twisted/twisted/pull/1484

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_3"></a>|@adiroiban commented|
|-|-|

We have a PR... we did our best to enable the tests.

Most of the tests are green without any main code changes... only the test code was updated.

For ALPN I ran manual tests and it works.

I think that this will be merged soon... but I don't think it's a release blocker.

**Comment by twisted-trac** [comment]
|[<img alt="exarkun's avatar" src="https://avatars.githubusercontent.com/u/254565?s=50" width="50" height="50">](https://github.com/exarkun)|@exarkun set owner to @adiroiban|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)|@adiroiban removed owner|
|-|-|

**Comment by twisted-trac** [comment]
|[<img alt="glyph's avatar" src="https://avatars.githubusercontent.com/u/716529?s=50" width="50" height="50">](https://github.com/glyph)<a name="note_6"></a>|@glyph set owner to @adiroiban|
|-|-|

Hey Adi,

Thanks for doing this, but it looks like we have merge conflicts. I'm trying to prune the review queue down to immediately actionable stuff. Can you address those and resubmit?

**Comment by exarkun** [comment]
https://github.com/twisted/twisted/pull/1484 is merged.  Is this resolved?

**Comment by exarkun** [comment]
https://app.codecov.io/gh/twisted/twisted/blob/trunk/src%2Ftwisted%2Fprotocols%2Ftest%2Ftest_tls.py shows the majority of this module as covered and a recent CI run shows twisted.protocols.test.test_tls as executed.

So I suppose this is resolved.
