### ISSUE TITLE
epub Read The Docs builds fail due to "WARNING: duplicated ToC entry found"

### ISSUE THREAD

**Issue by twisted-trac** [twisted/twisted#9996]
|[<img alt="graingert's avatar" src="https://avatars.githubusercontent.com/u/413772?s=50" width="50" height="50">](https://github.com/graingert)| @graingert reported|
|-|-|
|Trac ID|trac#9996|
|Type|release blocker: release process bug|
|Created|2020-10-04 19:13:21Z|

currently readthedocs only builds the html docs in CI readthedocs/readthedocs.org#7116 howerver the trunk epub Read The Docs builds fail due to "WARNING: duplicated ToC entry found"

We could:

1. disable the epub build on rtd,
2. ignore the duplicated ToC entry warning (blocked by https://github.com/sphinx-doc/sphinx/pull/8289)
3. ignore all RTD doc build warnings
4. try and fix it and build epub on PRs with github actions, I've got a PR repro here: https://github.com/twisted/twisted/pull/1424/checks?check_run_id=1205117871#step:7:896

I don't know what a ToC is or how to de-duplicate them

<details><summary>Searchable metadata</summary>

```
trac-id__9996 9996
type__release_blocker__release_process_bug release blocker: release process bug
reporter__graingert graingert
priority__highest highest
milestone__None None
branch__ 
branch_author__ 
status__new new
resolution__None None
component__core core
keywords__None None
time__1601838801882459 1601838801882459
changetime__1602063902559176 1602063902559176
version__None None
owner__None None

```
</details>

**Comment by twisted-trac** [comment]
|[<img alt="adiroiban's avatar" src="https://avatars.githubusercontent.com/u/204609?s=50" width="50" height="50">](https://github.com/adiroiban)<a name="note_4"></a>|@adiroiban commented|
|-|-|

I would go for option 1.

If someone needs epub format, they can submit a fix for that :)

You can also go with option 3  which is what I am doing at https://github.com/twisted/twisted/pull/1422

**Comment by adiroiban** [comment]
I think this is fixed... I don't know since when... But I don't think that is important :)

I see the latest build is green https://readthedocs.org/projects/twisted/builds/17488496/

and we have PDF and EPUB
